{================     E-Tales  Simulation  Files  Names     ==================================================================}

Const

{=======  Data  Files  Names  ================================================================================================}

  ProducersDecisionsFilesNames : array[1..ProsMaxPlus] of String =
      ( 'Producer 1 Decisions.', 'Producer 2 Decisions.', 'Producer 3 Decisions.', 'Producer Plus Decisions.' );

  RetailersDecisionsFilesNames : array[1..BMRetsMax] of String =
      ( 'Retailer 1 Decisions.', 'Retailer 2 Decisions.', 'Traditional Trade Decisions.' );

  NegotiationsFileName = 'Negotiations.';

  ResultsFileName = 'Results.';

  InternalDataFileName = 'InternalData.';

