{================     E-Tales  Simulation  Universe  Declarations     ========================================================}

Const

{=======  Total  Universe  of  Markets  ======================================================================================}

  UniverseMarketsNames    : array[TMarketsUniverse] of String =
                              ( 'PRC_Urban_',
                                'PRC_Rural_',
                                '',
                                '',
                                '',
                                '',
                                '',
                                '',
                                '' );


  UniverseCategoriesNames : array[TCategoriesUniverse] of String =
                              ( 'Elecsories',
                                'HealthBeauties',
                                '',
                                '',
                                '',
                                '',
                                '',
                                '',
                                '' );

