var getLabelBase = function(){
	return [
		{id:'Manual popInfo',  ENG:'Remark: If it is not specified otherwise in this simulation game, the monetary unit is RMB Million, the unit price is RMB Yuan and the volume unit is Million Package.',  CHN:'备注：除非特别说明，本模拟游戏中使用的货币单位均为人民币（百万元），产品单价均为人民币（元），产品数量单位均为百万包。 ',  RUS:''},	
		/*retail report new label */
		/*line chart page */
		{id:'e-Mall',  ENG:'E-Mall',  CHN:'网上商城',  RUS:''},
        {id:'Retail Market Sales (Value)',  ENG:'Retail Market Sales (Value)',  CHN:'各零售商的销售额',  RUS:''},        
        {id:'Retail Market Share (Value)',  ENG:'Retail Market Share (Value)',  CHN:'各零售商的市场份额（按销售额计）',  RUS:''},        
        {id:'Retail Market Sales (Volume)',  ENG:'Retail Market Sales (Volume)',  CHN:'各零售商的市场销量',  RUS:''},        
        {id:'Retail Market Share (Volume)',  ENG:'Retail Market Share (Volume)',  CHN:'各零售商的市场份额（按销量计）',  RUS:''},        
		{id:'Wholesales Market Results',  ENG:'Sales Value/Volume & Share',  CHN:'销售额/量和份额（到各渠道）',  RUS:''},
		{id:'Wholesales Market Results Info',  ENG:'Wholesales Market Results Info',  CHN:'各生产商的销售情况信息（到各渠道）',  RUS:''},
		{id:'Wholesale Sales Value',  ENG:'Wholesale Sales Value',  CHN:'各生产商的销售额（到各渠道）',  RUS:''},        
		{id:'Wholesale Share (Value)',  ENG:'Wholesale Sales Share (Value)',  CHN:'各生产商的份额（按销售额计）',  RUS:''},        
		{id:'Wholesale Sales Volume',  ENG:'Wholesale Sales Volume',  CHN:'各生产商的销量（到各渠道）',  RUS:''},        
		{id:'Wholesale Share (Volume)',  ENG:'Wholesale Sales Share (Volume)',  CHN:'各生产商的份额（按销量计）',  RUS:''},        
		{id:'Consumer Market Results',  ENG:'Market Sales Value/Volume & Share',  CHN:'市场销售额/量和份额（到消费者）',  RUS:''},
		{id:'Consumer Market Result Info',  ENG:'Consumer Market Result Info',  CHN:'各生产商的销售情况信息（到消费者）',  RUS:''},
		{id:'Consumer Sales (Value)',  ENG:'Consumer Sales (Value)',  CHN:'各生产商的市场销售额（到消费者）',  RUS:''},
		{id:'Consumer Market Share (Value)',  ENG:'Consumer Market Share (Value)',  CHN:'各生产商的市场份额（按销售额计）',  RUS:''},
		{id:'Consumer Sales (Volume)',  ENG:'Consumer Sales (Volume)',  CHN:'各生产商的市场销量（到消费者）',  RUS:''},
		{id:'Consumer Market Sales (Volume)',  ENG:'Consumer Market Sales (Volume)',  CHN:'各生产商的市场份额（按销量计）',  RUS:''},
		{id:'Export Excel',  ENG:'Export Excel',  CHN:'Excel导出',  RUS:''},

		{id:'Net Sales Value',  ENG:'Net Sales Value',  CHN:'净销售额',  RUS:''},	
		{id:'Expenses',  ENG:'Cost and Expenses',  CHN:'成本和费用',  RUS:''},

		{id:'Retail Market Results',  ENG:'Sales Value/Volume & Share',  CHN:'各零售商的销售情况',  RUS:''},
		{id:'Retail Market Results Info',  ENG:'Retail Market Results Info',  CHN:'各零售商的销售情况信息',  RUS:''},
		{id:'Gross Profit',  ENG:'Gross Profit',  CHN:'毛利润额',  RUS:''},	
		{id:'Operating Profit',  ENG:'Operating Profit',  CHN:'营业利润额',  RUS:''},	
		{id:'Net Profit',  ENG:'Net Profit',  CHN:'净利润额',  RUS:''},	
		{id:'Gross Profit Margin',  ENG:'Gross Profit Margin',  CHN:'毛利润率',  RUS:''},	
		{id:'Operating Profit Margin',  ENG:'Operating Profit Margin',  CHN:'营业利润率',  RUS:''},	
		{id:'Net Profit Margin',  ENG:'Net Profit Margin',  CHN:'净利润率',  RUS:''},	
		{id:'Total Material Cost',  ENG:'Total Material Cost',  CHN:'总材料成本',  RUS:''},	
		{id:'Total Advertising',  ENG:'Total Advertising',  CHN:'广告总投入',  RUS:''},	
		{id:'Total Trade (Producer) Support',  ENG:'Total Trade (Supplier) Support',  CHN:'（生产商）渠道支持合计',  RUS:''},	
		{id:'Total General Expenses',  ENG:'Total General Expenses',  CHN:'经常性开支总额',  RUS:''},
		{id:'Profitability Absolute RMB',  ENG:'Profit in Value',  CHN:'利润额',  RUS:''},
		{id:'Profitability Absolute RMB Info',  ENG:'Profitability Absolute RMB Info',  CHN:'利润额信息',  RUS:''},
		{id:'Profitability as percentage of Sales',  ENG:'Profit in % of Sales',  CHN:'利润率',  RUS:''},
		{id:'Profitability as percentage of Sales Info',  ENG:'Profitability as percentage of Sales Info',  CHN:'利润率信息',  RUS:''},

		{id:'Team',  ENG:'Team',  CHN:'团队',  RUS:''},	
		{id:'Producer 1',  ENG:'Supplier 1',  CHN:'生厂商 1',  RUS:''},	
		{id:'Producer 2',  ENG:'Supplier 2',  CHN:'生厂商 2',  RUS:''},	
		{id:'Producer 3',  ENG:'Supplier 3',  CHN:'生厂商 3',  RUS:''},	
		{id:'Producer 4',  ENG:'Supplier 4',  CHN:'生厂商 4',  RUS:''},	
		{id:'Chart',  ENG:'Chart',  CHN:'图表',  RUS:''},
		{id:'Chart Info',  ENG:'Charts show you visually where your business stands in comparison to your competitors.',  CHN:'图表帮助你一目了然地比较自己和竞争对手的情况。',  RUS:''},
		{id:'Chart popInfo',  ENG:'You may look at other industry (retail or manufacturing) for benchmarking if you change role selector. You may change details level using category and market selectors. To see numbers behind the trends use your mouse over the lines.',  CHN:'可以选择 \"品类\" 或 \"市场\"，从不同层级查看信息。把鼠标放在趋势线上，可以看到相应的数字。',  RUS:''},
		{id:'Total',  ENG:'Total',  CHN:'总计',  RUS:''},
		{id:'TOTAL',  ENG:'TOTAL',  CHN:'总计',  RUS:''},
		{id:'Amount Info',  ENG:'Amount Info',  CHN:'Amount输入提示',  RUS:''},

		{id:'Net Sales Value Info',  ENG:'Net Sales Value Info',  CHN:'Net Sales Value Info',  RUS:''},	
		{id:'Gross Profit Info',  ENG:'Gross Profit Info',  CHN:'Gross Profit Info',  RUS:''},	
		{id:'Operating Profit Info',  ENG:'Operating Profit Info',  CHN:'Operating Profit Info',  RUS:''},	
		{id:'Net Profit Info',  ENG:'Net Profit Info',  CHN:'Net Profit Info',  RUS:''},	
		{id:'Gross Profit Margin Info',  ENG:'Gross Profit Margin Info',  CHN:'Gross Profit Margin Info',  RUS:''},	
		{id:'Operating Profit Margin Info',  ENG:'Operating Profit Margin Info',  CHN:'Operating Profit Margin Info',  RUS:''},	
		{id:'Net Profit Margin Info',  ENG:'Net Profit Margin Info',  CHN:'Net Profit Margin Info',  RUS:''},	
		{id:'Total Material Cost Info',  ENG:'Total Material Cost Info',  CHN:'Total Material Cost Info',  RUS:''},	
		{id:'Total Advertising Info',  ENG:'Total Advertising Info',  CHN:'Total Advertising Info',  RUS:''},	
		{id:'Total Trade (Producer) Support Info',  ENG:'Total Trade (Supplier) Support Info',  CHN:'Total Trade (Supplier) Support Info',  RUS:''},	
		{id:'Total General Expenses Info',  ENG:'Total General Expenses Info',  CHN:'Total General Expenses Info',  RUS:''},	
		{id:'Wholesale Sales Value Info',  ENG:'Wholesale Sales Value Info',  CHN:'Wholesale Sales Value Info',  RUS:''},	
		{id:'Wholesale Sales Volume Info',  ENG:'Wholesale Sales Volume Info',  CHN:'Wholesale Sales Volume Info',  RUS:''},	
		{id:'Wholesale Market Share (Value)',  ENG:'Wholesale Market Share (Value)',  CHN:'Wholesale Market Share (Value)',  RUS:''},	
		{id:'Wholesale Market Share (Value) Info',  ENG:'Wholesale Market Share (Value) Info',  CHN:'Wholesale Market Share (Value) Info',  RUS:''},	
		{id:'Wholesale Market Share (Volume)',  ENG:'Wholesale Market Share (Volume)',  CHN:'Wholesale Market Share (Volume)',  RUS:''},	
		{id:'Wholesale Market Share (Volume) Info',  ENG:'Wholesale Market Share (Volume) Info',  CHN:'Wholesale Market Share (Volume) Info',  RUS:''},	
		{id:'Retail Market Sales (Value) Info',  ENG:'Retail Market Sales (Value) Info',  CHN:'Retail Market Sales (Value) Info',  RUS:''},	
		{id:'Retail Market Sales (Volume) Info',  ENG:'Retail Market Sales (Volume) Info',  CHN:'Retail Market Sales (Volume) Info',  RUS:''},
		{id:'Retail Market Share (Value) Info',  ENG:'Retail Market Share (Value) Info',  CHN:'Retail Market Share (Value) Info',  RUS:''},
		{id:'Retail Market Share (Volume) Info',  ENG:'Retail Market Share (Volume) Info',  CHN:'Retail Market Share (Volume) Info',  RUS:''},
		{id:'Volume Info',  ENG:'Volume Info',  CHN:'Volume介绍',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},

		/*Login page*/
		{id:'eTales Info',  ENG:'Best-in-class professional development tool among the world’s most respected companies and leading business schools',  CHN:'首次呈现和探索零售商、供应商、电商和消费者在社交媒体盛行时代的生存和胜出之道。',  RUS:''},
		{id:'Get started',  ENG:'Get started',  CHN:'现在开始',  RUS:''},
		{id:'Admin entrance',  ENG:'Admin entrance',  CHN:'管理员入口',  RUS:''},
		{id:'Currently',  ENG:'Currently',  CHN:'当前版本',  RUS:''},
		{id:'User Login',  ENG:'User Login',  CHN:'学员登录',  RUS:''},	
		{id:'Role',  ENG:'Role',  CHN:'小组',  RUS:''},	
		{id:'Password',  ENG:'Password',  CHN:'密码',  RUS:''},	
		{id:'Seminar Code',  ENG:'Seminar Code',  CHN:'课程编号',  RUS:''},	
		{id:'Login',  ENG:'Login',  CHN:'登录',  RUS:''},	
		{id:'Admin Login',  ENG:'Admin Login',  CHN:'管理员登录',  RUS:''},	
		{id:'Facilitator',  ENG:'Facilitator',  CHN:'讲师',  RUS:''},	
		{id:'Guest',  ENG:'Guest',  CHN:'访客',  RUS:''},	

		/*Perception map page*/
		{id:'Ease of use',  ENG:'Ease of use',  CHN:'易用性',  RUS:''},	
		{id:'Quality',  ENG:'Quality',  CHN:'质量',  RUS:''},	
		{id:'Price',  ENG:'Price',  CHN:'价格',  RUS:''},	
		{id:'Market Share',  ENG:'Market Share',  CHN:'市场份额',  RUS:''},	
		{id:'Visibility Share',  ENG:'Visibility Share',  CHN:'可见度份额',  RUS:''},	
		{id:'Company summary',  ENG:'Company summary',  CHN:'公司信息汇总',  RUS:''},
		{id:'Company summary Info',  ENG:'',  CHN:'公司信息汇总',  RUS:''},
		{id:'Perception Map',  ENG:'Perception Map',  CHN:'感知图',  RUS:''},
		{id:'Perception Map Info',  ENG:'A type of chart widely used in marketing to graphically show how consumers perceive brands. In some cases brand positioning is compared with consumer segments ideal points. In eTales however vector positioning model is used. It means that having no ideal point as such, all segments will prefer brands with higher (or lower) perception if this perception dimension is of relative importance to consumers of this segment.',  CHN:'市场营销中广泛使用的一种图表，显示消费者如何感知你的品牌。 在有些情况下， 会把品牌定位和消费者细分的理想感知点进行对比。而在\“零售风暴\”中，采用了\“向量定位\”的模式，没有所谓的\“理想感知点\”，根据品牌在某个维度感知值的高低来显示该品牌的位置，细分市场的消费者会根据某维度对其的相对重要性，选择该维度较高或较低的品牌。',  RUS:''},		
		{id:'Perception Map popInfo',  ENG:'Position your mouse over brand name to see change dinamics and additional market information.',  CHN:'把鼠标放在品牌名称上， 你会看到该品牌的变化和额外的市场信息。 ',  RUS:''},		
		{id:'Check All',  ENG:'Check All',  CHN:'选择全部',  RUS:''},
		{id:'Un-Check All',  ENG:'Un-Check All',  CHN:'取消全部',  RUS:''},
		{id:'Generate Map',  ENG:'Generate Map',  CHN:'生成图表',  RUS:''},
		{id:'Period',  ENG:'Period',  CHN:'阶段',  RUS:''},
		{id:'Reason',  ENG:"For some reason,something in this page can't translate immediately",  CHN:'For some reason,something in this page cannot translate immediately。',  RUS:''},
		{id:'Performance',  ENG:"Performance",  CHN:'效果',  RUS:''},
		{id:'Gentleness',  ENG:"Gentleness",  CHN:'亲柔度',  RUS:''},
		{id:'Perceptions Map',  ENG:'Perceptions Map',  CHN:'感知图',  RUS:''},
		{id:'Ease of Use perception',  ENG:'Ease of Use perception',  CHN:'易用性感知',  RUS:''},
		{id:'Quality perception',  ENG:'Quality perception',  CHN:'质量感知',  RUS:''},
		{id:'Performance perception',  ENG:'Performance perception',  CHN:'效果感知',  RUS:''},
		{id:'Gentleness perception',  ENG:'Gentleness perception',  CHN:'亲柔度感知',  RUS:''},
		{id:'PricePerception',  ENG:'PricePerception',  CHN:'价格感知',  RUS:''},
		{id:'Price Sensitive',  ENG:'Price Sensitive',  CHN:'价格敏感型',  RUS:''},
		{id:'Value for Money',  ENG:'Value for Money',  CHN:'物有所值型',  RUS:''},
		{id:'Value For Money',  ENG:'Value For Money',  CHN:'物有所值型',  RUS:''},
		{id:'Health Conscious',  ENG:'Health Conscious',  CHN:'注重健康型',  RUS:''},
		{id:'Impatient',  ENG:'Impatient',  CHN:'急躁型',  RUS:''},
		{id:'Retailer 1',  ENG:'Retailer 1',  CHN:'零售商1',  RUS:''},
		{id:'Retailer 2',  ENG:'Retailer 2',  CHN:'零售商2',  RUS:''},
		{id:'eMall',  ENG:'eMall',  CHN:'网上商城',  RUS:''},
		{id:'Producer',  ENG:'Supplier ',  CHN:'生产商',  RUS:''},
		{id:'Retailer',  ENG:'Retailer ',  CHN:'零售商',  RUS:''},
		{id:'switchLanguage',  ENG:'Switch Language',  CHN:'切换语言',  RUS:''},

		/*navbar*/
		{id:'Participant manual',  ENG:'Participant manual',  CHN:'学员手册',  RUS:''},
		{id:'My company',  ENG:'My company',  CHN:'我的公司',  RUS:''},
		{id:'Charts',  ENG:'Charts',  CHN:'图表',  RUS:''},
		{id:'Make Decision',  ENG:'Make Decision',  CHN:'制订决策',  RUS:''},
		{id:'Get result of lastest period',  ENG:'Get result of lastest perio',  CHN:'更新决策',  RUS:''},
		{id:'Log out',  ENG:'Log out',  CHN:'退出',  RUS:''},

		/*fin report*/
		{id:'Reports',  ENG:'Reports',  CHN:'报告',  RUS:''},
		{id:'Reports Info',  ENG:'Here you will find financial statements and other reports giving operating results of your company and its departments.',  CHN:'这里你可以查看公司各方面的财务信息。',  RUS:''},
		{id:'Reports popInfo',  ENG:' Looking at the reports, try to change perspective or detail level from global (company) or category to brand or even variant (SKU).',  CHN:'可以从整个市场（公司）、分市场、分品类、分品牌甚至单品查看信息。',  RUS:''},
		{id:'Profit and Loss Statement',  ENG:'Profit and Loss Statement',  CHN:'损益表',  RUS:''},
		{id:'Profit and Loss Statement Info',  ENG:'One of the major financial reports of the company. It indicates how the revenues (money received from the sale of products and services before expenses are taken out, also known as the "top line") are transformed into the net income (the result after all revenues and expenses have been accounted for, also known as \"net profit\" or the \"bottom line\")',  CHN:'这是你们公司主要财务报告之一。它显示了销售额到净利润的转化过程，销售额指来自产品和服务的销售收入，也叫“top line”，净利润指扣除所有费用的结果， 也叫“bottom line”。',  RUS:''},
		{id:'Prices per unit',  ENG:'Prices per unit',  CHN:'单价',  RUS:''},
		{id:'Prices per unit Info',  ENG:'Relevant pricing information',  CHN:'相关的定价信息。',  RUS:''},
		{id:'Volumes Report',  ENG:'Volumes Report',  CHN:'销量报告',  RUS:''},
		{id:'Volumes Report Info',  ENG:'Inventory report',  CHN:'库存信息。',  RUS:''},
		{id:'Profitability by Channel',  ENG:'Profitability by Channel',  CHN:'品类在各渠道的盈利分析',  RUS:''},
		{id:'Profitability by Channel Info',  ENG:'Simplified profit and loss statement used to compare profit generated by each channel after every type of expenses spent on distribution channel is accounted for',  CHN:'按渠道提供的损益表，各渠道产生的销售收入减去在该渠道花费的各种费用后的盈利结果。',  RUS:''},
		{id:'Performance Indices',  ENG:'Performance Indices',  CHN:'绩效指标',  RUS:''},
		{id:'Performance Indices Info',  ENG:'Performance Indices Info',  CHN:'绩效指标信息。',  RUS:''},
		{id:'Profitability by Supplier',  ENG:'Profitability by Supplier',  CHN:'各供应商提供的品类的盈利分析',  RUS:''},
		{id:'Profitability by Supplier Info',  ENG:'Simplified profit and loss statement used to compare profit generated by each supplier after every type of expense and revenue is allocated by supplier and accounted for',  CHN:'按供应商提供的损益表，各供应商带来的销售收入减去相应费用后的盈利结果。',  RUS:''},
		{id:'Detail',  ENG:'Detail',  CHN:'细节信息',  RUS:''},
		{id:'Global',  ENG:'Global',  CHN:'整个市场',  RUS:''},
		{id:'Traditional Trade',  ENG:'Traditional Trade',  CHN:'传统渠道',  RUS:''},
		{id:'E-Mall',  ENG:'E-Mall',  CHN:'网上商城',  RUS:''},
		{id:'Item',  ENG:'Item',  CHN:'条款',  RUS:''},

		/*Producer Reports*/
		{id:'Sales value($mln)',  ENG:'Sales value($mln)',  CHN:'销售额',  RUS:''},
		{id:'(%) change versus previous period',  ENG:'(%) change versus previous period',  CHN:'（%）相对于上阶段的变化',  RUS:''},
		{id:'Share In Category Total Sales Value (%)',  ENG:'Share In Category Total Sales Value （%）',  CHN:'占品类总销售额比例（%）',  RUS:''},
		{id:'Total material costs($mln)',  ENG:'Total material costs($mln)',  CHN:'总成本',  RUS:''},
		{id:'Cost of Goods Sold ($mln)',  ENG:'Cost of Goods Sold ($mln)',  CHN:'售出产品成本',  RUS:''},
		{id:'Discontinued Goods Cost($mln)',  ENG:'Discontinued Goods Cost($mln)',  CHN:'停产产品成本',  RUS:''},
		{id:'Inventory Holding Cost($mln)',  ENG:'Inventory Holding Cost($mln)',  CHN:'库存持有成本',  RUS:''},
		{id:'Gross Profit($mln)',  ENG:'Gross Profit($mln)',  CHN:'毛利额',  RUS:''},
		{id:'Gross Profit margin (%)',  ENG:'Gross Profit margin (%)',  CHN:'毛利率（%）',  RUS:''},
		{id:'Share in Category Gross Profit/Losses (%)',  ENG:'Share in Category Gross Profit/Losses （%）',  CHN:'占品类毛利/损失的比例（%）',  RUS:''},		
		{id:'Advertising Total ($mln)',  ENG:'Advertising Total ($mln)',  CHN:'广告投入合计',  RUS:''},
		{id:'National Off-line ($mln)',  ENG:'National Off-line ($mln)',  CHN:'全国性传统广告',  RUS:''},
		{id:'National On-line ($mln)',  ENG:'National On-line ($mln)',  CHN:'全国性网络广告',  RUS:''},
		{id:'Local Tier 1 ($mln)',  ENG:'Local Tier 1 ($mln)',  CHN:'城市地区广告',  RUS:''},
		{id:'Local Tier 2 ($mln)',  ENG:'Local Tier 2 ($mln)',  CHN:'农村地区广告',  RUS:''},
		{id:'Total Trade Support ($mln)',  ENG:'Total Trade Support ($mln)',  CHN:'渠道支持合计',  RUS:''},
		{id:'Price Promotions ($mln)',  ENG:'Price Promotions ($mln)',  CHN:'价格促销',  RUS:''},
		{id:'Volume Discounts ($mln)',  ENG:'Volume Discounts ($mln)',  CHN:'数量折扣',  RUS:''},
		{id:'Performance Bonus ($mln)',  ENG:'Performance Bonus ($mln)',  CHN:'业绩奖励',  RUS:''},
		{id:'Other Support ($mln)',  ENG:'Other Support ($mln)',  CHN:'其他支持',  RUS:''},
		{id:'Total Trade and Marketing Expenses($mln)',  ENG:'Total Trade and Marketing Expenses($mln)',  CHN:'广告投入和渠道支持合计',  RUS:''},
		{id:'Trade and Marketing Expenses as a (%) of Sales',  ENG:'Trade and Marketing Expenses as a (%) of Sales',  CHN:'广告投入和渠道支持合计占销售额的比例(%)',  RUS:''},
		{id:'General Expenses($mln)',  ENG:'General Expenses($mln)',  CHN:'经常性开支',  RUS:''},
		{id:'Amortisation ($mln)',  ENG:'Amortisation ($mln)',  CHN:'折旧和摊销费用',  RUS:''},
		{id:'Operating Profit ($mln)',  ENG:'Operating Profit ($mln)',  CHN:'营业利润',  RUS:''},
		{id:'Operating Profit margin (%)',  ENG:'Operating Profit margin (%)',  CHN:'营业利润率（%）',  RUS:''},
		{id:'Share in Category Operating Profit/Losses (%)',  ENG:'Share in Category Operating Profit/Losses (%)',  CHN:'占该品类营业利润/亏损的比例（%）',  RUS:''},
		{id:'Interests($mln)',  ENG:'Interests($mln)',  CHN:'财务费用（利息）',  RUS:''},
		{id:'Taxes($mln)',  ENG:'Taxes($mln)',  CHN:'所得税',  RUS:''},
		{id:'Exceptional Costs/Profits($mln)',  ENG:'Exceptional Costs/Profits($mln)',  CHN:'营业外支出/收入',  RUS:''},
		{id:'Net Profit($mln)',  ENG:'Net Profit($mln)',  CHN:'净利润',  RUS:''},
		{id:'Net Profit margin (%)',  ENG:'Net Profit margin (%)',  CHN:'净利润率(%)',  RUS:''},
		{id:'Share of Trade and Marketing Expenses in Category Total (%)',  ENG:'Share of Trade and Marketing Expenses in Category Total (%)',  CHN:'占该品类广告投入和渠道支持合计的比例（%）',  RUS:''},	
		{id:'Share In Category Net Profit/Losses (%)',  ENG:'Share In Category Net Profit/Losses (%)',  CHN:'占该品类净利润/亏损的比例（%）',  RUS:''},
		{id:'Production Cost',  ENG:'Production Cost',  CHN:'生产成本',  RUS:''},
		{id:'Current List price BM',  ENG:'Current List price B&M',  CHN:'当前阶段对实体零售店的报价',  RUS:''},
		{id:'Next List Price BM',  ENG:'Next List Price B&M',  CHN:'下阶段对实体零售店的报价',  RUS:''},
		{id:'Current List Price eMall',  ENG:'Current List Price eMall',  CHN:'当前网店的零售价',  RUS:''},
		{id:'Next List Price eMall',  ENG:'Next List Price eMall',  CHN:'下阶段网店的零售价',  RUS:''},
		{id:'Production',  ENG:'Production',  CHN:'本阶段产量',  RUS:''},
		{id:'Sales',  ENG:'Sales',  CHN:'本阶段销量',  RUS:''},
		{id:'Discontinued Goods',  ENG:'Discontinued Goods',  CHN:'停产产品',  RUS:''},
		{id:'Order volume (mln. Units)',  ENG:'Order volume (mln. Units)',  CHN:'订货量',  RUS:''},
		{id:'Sales volume (mln. Units)',  ENG:'Sales volume (mln. Units)',  CHN:'销售量',  RUS:''},
		{id:'Share in sales volume (%)',  ENG:'Share in sales volume (%)',  CHN:'占销量的比例（%）',  RUS:''},
		{id:'Sales value (RMB 000)',  ENG:'Sales value (RMB 000)',  CHN:'销售额',  RUS:''},
		{id:'Share in gross sales value (%)',  ENG:'Share in gross sales value (%)',  CHN:'占总销售额的比例（%）',  RUS:''},
		{id:'Cost of goods sold (RMB 000)',  ENG:'Cost of goods sold (RMB 000)',  CHN:'售出产品成本',  RUS:''},
		{id:'Quantity discounts costs (RMB 000)',  ENG:'Quantity discounts costs (RMB 000)',  CHN:'数量折扣成本',  RUS:''},
		{id:'(delay of payment) (RMB 000)',  ENG:'(delay of payment) (RMB 000)',  CHN:'延期付款',  RUS:''},
		{id:'Other compensation (RMB 000)',  ENG:'Other compensation (RMB 000)',  CHN:'其他支持',  RUS:''},
		{id:'Total trade support (RMB 000)',  ENG:'Total trade support (RMB 000)',  CHN:'渠道支持合计',  RUS:''},
		{id:'Gross profit after PUSH (RMB 000)',  ENG:'Gross profit after PUSH (RMB 000)',  CHN:'扣除渠道支持费用后的毛利额',  RUS:''},
		{id:'Share in gross profit (%)',  ENG:'Share in gross profit (%)',  CHN:'占毛利额比例（%）',  RUS:''},
		{id:'Performance bonus cost (RMB 000)',  ENG:'Performance bonus cost (RMB 000)',  CHN:'业绩奖励成本',  RUS:''},
		{id:'In store activities fees (RMB 000)',  ENG:'In store activities fees (RMB 000)',  CHN:'店内营销活动费用',  RUS:''},
		{id:'Inventory holding cost compensation (RMB 000)',  ENG:'Inventory holding cost compensation (RMB 000)',  CHN:'库存持有成本补偿',  RUS:''},
		{id:'Promotional support (RMB 000)',  ENG:'Promotional support (RMB 000)',  CHN:'促销支持',  RUS:''},
		{id:'Financial Cost (delay of payment) (RMB 000)',  ENG:'Financial Cost (delay of payment) (RMB 000)',  CHN:'财务成本（延期支付）',  RUS:''},
		{id:'Company total',  ENG:'Company total',  CHN:'公司总计',  RUS:''},	
		
		/*Retailer Reports */
		{id:'Sales value ($mln)',  ENG:'Sales value ($mln)',  CHN:'销售额',  RUS:''},
		{id:'- Cost of Price Promotions ($mln)',  ENG:'- Cost of Price Promotions ($mln)',  CHN:'价格促销成本',  RUS:''},
		{id:'Promotional Support from Supplier ($mln)',  ENG:'Promotional Support from Supplier ($mln)',  CHN:'生产商提供的促销支持',  RUS:''},
		{id:'Other Compensation ($mln)',  ENG:'Other Compensation ($mln)',  CHN:'生产商提供的其他补偿',  RUS:''},
		{id:'Net Sales Value ($mln)',  ENG:'Net Sales Value ($mln)',  CHN:'净销售额',  RUS:''},
		{id:'-Total material costs($mln)',  ENG:'Total material costs($mln)',  CHN:'总材料成本',  RUS:''},
		{id:'-Cost of Goods Sold ($mln)',  ENG:'Cost of Goods Sold ($mln)',  CHN:'售出商品成本',  RUS:''},
		{id:'Value of Quantity Discounts ($mln)',  ENG:'Value of Quantity Discounts ($mln)',  CHN:'数量折扣',  RUS:''},
		{id:'Value of Performance Bonus ($mln)',  ENG:'Value of Performance Bonus ($mln)',  CHN:'业绩奖励',  RUS:''},
		{id:'-Discontinued Goods Cost($mln)',  ENG:'Discontinued Goods Cost($mln)',  CHN:'停售商品成本',  RUS:''},
		{id:'-Inventory Holding Cost($mln)',  ENG:'Inventory Holding Cost($mln)',  CHN:'库存持有成本',  RUS:''},
		{id:'-General Expenses($mln)',  ENG:'General Expenses($mln)',  CHN:'经常性开支',  RUS:''},
		{id:'-Taxes($mln)',  ENG:'Taxes($mln)',  CHN:'所得税',  RUS:''},
		{id:'Value Rotation Index  Sales value per 1% of shelf space',  ENG:'Value Rotation Index Sales value per 1% of shelf space',  CHN:'每1%货架的销售额',  RUS:''},
		{id:'Volume Rotation Index  Sales volume per 1% of shelf space',  ENG:'Volume Rotation Index Sales volume per 1% of shelf space',  CHN:'每1%货架的销量',  RUS:''},
		{id:'Profitability Index  Gross Profit per 1% of shelf space',  ENG:'Profitability Index Gross Profit per 1% of shelf space',  CHN:'每1%货架的毛利额',  RUS:''},
		{id:'Stock Cover  Closing Inventory Volume / weekly Sales volume',  ENG:'Stock Cover Closing Inventory Volume / weekly Sales volume',  CHN:'期末库存数量/每周销量',  RUS:''},
		{id:'Market Price',  ENG:'Market Price',  CHN:'零售价',  RUS:''},
		{id:'Purchase Price',  ENG:'Purchase Price',  CHN:'采购价',  RUS:''},
		{id:'Effective Net Purchase Price',  ENG:'Effective Net Purchase Price',  CHN:'实际净采购价',  RUS:''},
		{id:'Supplier Current List price',  ENG:'Supplier Current List price',  CHN:'生产商当前报价',  RUS:''},
		{id:'Supplier Next List Price',  ENG:'Supplier Next List Price',  CHN:'生产商下阶段报价',  RUS:''},
		{id:'Total shelf space (%)',  ENG:'Total shelf space (%)',  CHN:'总货架空间（%）',  RUS:''},
		{id:'Net sales (RMB 000)',  ENG:'Net sales (RMB 000)',  CHN:'净销售额',  RUS:''},
		{id:'share in total (%)',  ENG:'share in total (%)',  CHN:'占总销售额的比例（%）',  RUS:''},
		{id:'Gross contribution (RMB 000)',  ENG:'Gross contribution (RMB 000)',  CHN:'毛利贡献额',  RUS:''},
		{id:'Financial revenue (RMB 000)',  ENG:'Financial revenue (RMB 000)',  CHN:'财务收入',  RUS:''},
		{id:'Adjusted gross contribution (RMB 000)',  ENG:'Adjusted gross contribution (RMB 000)',  CHN:'调整后的毛利贡献额',  RUS:''},
		{id:'Terms of payment (days)',  ENG:'Terms of payment (days)',  CHN:'帐期（天数）',  RUS:''},
		{id:'Purchases',  ENG:'Purchases',  CHN:'本阶段采购量',  RUS:''},
		{id:'per 1% of shelf space (RMB 000)',  ENG:'per 1% of shelf space',  CHN:'每1%货架的销量',  RUS:''},
		{id:'as % of net sales (%)',  ENG:'as % of net sales (%)',  CHN:'调整后的毛利率（%）',  RUS:''},
		{id:'- Advertising Total ($mln)',  ENG:'Advertising Total ($mln)',  CHN:'广告投入合计',  RUS:''},
		{id:'-National Off-line ($mln)',  ENG:'National Off-line ($mln)',  CHN:'全国性传统广告',  RUS:''},
		{id:'-National On-line ($mln)',  ENG:'National On-line ($mln)',  CHN:'全国性网络广告',  RUS:''},
		{id:'-Local Tier T ($mln)',  ENG:'Local Tier T ($mln)',  CHN:'本地广告投入',  RUS:''},
		{id:'-Stores Operating Costs ($mln)',  ENG:'Stores Operating Costs ($mln)',  CHN:'门店运营费用',  RUS:''},
		{id:'-Amortisation ($mln)',  ENG:'Amortisation ($mln)',  CHN:'折旧和摊销费用',  RUS:''},
		{id:'Manufacturer 1',  ENG:'Manufacturer 1',  CHN:'生产商 1',  RUS:''},	
		{id:'Manufacturer 2',  ENG:'Manufacturer 2',  CHN:'生产商 2',  RUS:''},	
		{id:'Manufacturer 3',  ENG:'Manufacturer 3',  CHN:'生产商 3',  RUS:''},	
		{id:'Private label',  ENG:'Private label',  CHN:'自有品牌',  RUS:''},	
		/*market report*/
		{id:'Market popInfo',  ENG:'Click on column header to sort the table.',  CHN:'点击顶部的标题栏，可以对数据进行排序。',  RUS:''},
		{id:'Market studies',  ENG:'Market studies',  CHN:'市场研究',  RUS:''},
		{id:'Market studies Info',  ENG:'Basic market facts collected here in numerical form. They will help you in your analysis of market characteristics and trends as well as consumer preferences, purchasing power by market, category and segment.',  CHN:'这里提供基本的市场数据，支持你分析市场特征和趋势，消费者偏好，不同市场、不同品类和不同细分的的购买力。',  RUS:''},	
		{id:'Brand Awareness',  ENG:'Brand Awareness',  CHN:'品牌认知度',  RUS:''},
		{id:'Brand Awareness Info',  ENG:'Extent to which consumers are aware of a particular product measured as percentage of total. Gives you an idea how your promotional expenses and investments into visibility paid off.',  CHN:'品牌认知度指该产品在消费者所有认知的品牌中所占的份额，反映你在促销和渠道可见度方面投资的回报。',  RUS:''},
		{id:'Market Share (Volume)',  ENG:'Market Share (Volume)',  CHN:'市场份额（以销量计）',  RUS:''},
		{id:'Market Share (Volume) Info',  ENG:'Percentage of a total market, in terms of volume, accounted for by the sales of a specific brand.',  CHN:'该品牌占总市场销量的份额。',  RUS:''},
		{id:'Market Share (Value)',  ENG:'Market Share (Value)',  CHN:'市场份额（以销售额计）',  RUS:''},
		{id:'Market Share (Value) Info',  ENG:'Percentage of a total market, in terms of value, accounted for by the sales of a specific brand.',  CHN:'该品牌占市场总销售额的份额',  RUS:''},
		{id:'Average Net Market Price',  ENG:'Average Net Market Price',  CHN:'平均净市场价',  RUS:''},
		{id:'Average Net Market Price Info',  ENG:'Price at which a product is selling in the open market. It is averaged across all channels. Promotional discounts off normal retail price are also accounted for.',  CHN:'该产品在市场中的公开零售价格，平均了它在各个渠道的价格，包括扣除了促销折扣的因素。',  RUS:''},
		{id:'Brand Visibility Share',  ENG:'Brand Visibility Share',  CHN:'品牌可见度份额',  RUS:''},
		{id:'Brand Visibility Share Info',  ENG:'An integral measure that averages brand space share and marketing activities increasing brand visibility at a given channel.',  CHN:'一个综合性指标，平衡考虑了品牌份额和特定渠道可见度活动。',  RUS:''},
		{id:'Consumer off-take',  ENG:'Consumer off-take',  CHN:'市场销量',  RUS:''},
		{id:'Consumer off-take Info',  ENG:'This measure indicates how many units of a product have been sold to the consumer.',  CHN:'衡量消费者实际购买数量的指标',  RUS:''},
		
		{id:'Retailer Perceptions',  ENG:'Retailer Perceptions',  CHN:'零售商感知',  RUS:''},
		{id:'Retailer Perceptions Info',  ENG:'Shows how shoppers perceive retail players in terms of price (lower cheaper, higher more expensive), convenience and assortment.',  CHN:'表现购买者对零售商的感知，包括其价格（便宜低价，较贵高价），便利性和产品丰富性。',  RUS:''},
		{id:'Shopper Behavior',  ENG:'Shopper Behavior',  CHN:'购物者行为',  RUS:''},
		{id:'Shopper Behavior Info',  ENG:'Registers where consumers from different segments prefer to go shopping',  CHN:'表现不同细分市场的消费者对于购物渠道的偏好。',  RUS:''},

		{id:'Channel',  ENG:'Channel',  CHN:'分销渠道',  RUS:''},
		{id:'Assortment',  ENG:'Assortment',  CHN:'产品丰富性',  RUS:''},
		{id:'Convenience',  ENG:'Convenience',  CHN:'便利性',  RUS:''},
		{id:'Freaks',  ENG:'Freaks',  CHN:'狂热型',  RUS:''},
		{id:'Fashion',  ENG:'Fashion',  CHN:'时尚型',  RUS:''},


		/*Negotiation*/
		{id:'Negotiation',  ENG:'Negotiation',  CHN:'谈判',  RUS:''},
		{id:'Negotiation Info',  ENG:'Manufacturer initiates draft proposal and negotiations process. Deal is concluded when both Manufacturer and Retailer confirm agreement. System checks concluded deals automatically, so use computer logic to set verifiable criteria. ',  CHN:'由生产商启动谈判，并起草合同。当生产商和零售商达成一致时，合同生效。本模拟游戏采用计算机的逻辑来确定合同生效的标准，系统会按照这个标准，核查合同的有效性。',  RUS:''},
		{id:'Negotiation hints',  ENG:'Time is limited! No deals after time’s out are accepted!',  CHN:'时间有限！超时达成的协议将不被接受！',  RUS:''},		
		{id:'Contract List',  ENG:'Contract List',  CHN:'合同汇总',  RUS:''},
		{id:'Contract List Info',  ENG:'All your contracts (pending and concluded) are in the list below. You may use any of them as a sample, copy its structure to change only essential details.',  CHN:'如下为所有的合同清单（包括正在谈判和已经签署的），你可以复制任一合同并在此基础上修改核心内容以生成一份新合同。',  RUS:''},
		{id:'Contract Name',  ENG:'Contract Name',  CHN:'合同名称',  RUS:''},
		{id:'Drafted By',  ENG:'Drafted By',  CHN:'甲方（提出协议的一方）',  RUS:''},
		{id:'Details',  ENG:'Details',  CHN:'细节',  RUS:''},
		{id:'Duplicate',  ENG:'Duplicate',  CHN:'复制',  RUS:''},
		{id:'New Contract',  ENG:'New Contract',  CHN:'新合同',  RUS:''},
		{id:'New Negotiation',  ENG:'New Negotiation',  CHN:'新谈判',  RUS:''},
		{id:'New contract name',  ENG:'New contract name',  CHN:'新合同名称',  RUS:''},
		{id:'Contract with',  ENG:'Contract with',  CHN:'乙方（接受协议的一方）',  RUS:''},
		{id:'Duplicate Negotiation',  ENG:'Duplicate Negotiation',  CHN:'复制谈判',  RUS:''},
		{id:'isLock',  ENG:'isLock',  CHN:'锁定',  RUS:''},
		{id:'Lock',  ENG:'Lock',  CHN:'锁定',  RUS:''},
		{id:'UnLock',  ENG:'UnLock',  CHN:'解锁',  RUS:''},
		{id:'isDraftFinished',  ENG:'isDraftFinished',  CHN:'完成',  RUS:''},

		/*Contract Details*/
		{id:'Contract Details',  ENG:'Contract Details',  CHN:'合同细节',  RUS:''},
		{id:'Contract Details Info',  ENG:'You can view your peer proposal and make your suggestions on the part belonging to your business. ',  CHN:'这里显示你和生产商（零售商）达成协议或正在谈判的条款细节',  RUS:''},
		{id:'ContractDetails hints',  ENG:'Use View button to see peer proposal details. Use Edit button to make your proposal.',  CHN:'点击“查看”浏览合同提案细节。点击“编辑”编辑合同提案。',  RUS:''},
		{id:'Contract Name',  ENG:'Contract Name',  CHN:'合同名称',  RUS:''},
		{id:'Seminar',  ENG:'Seminar',  CHN:'课程',  RUS:''},
		{id:'Loading',  ENG:'Loading',  CHN:'加载中',  RUS:''},
		{id:'Items (Producer Input)',  ENG:'Items (Supplier Input)',  CHN:'谈判条款（生产商提案）',  RUS:''},
		{id:'Items (Retailer Input)',  ENG:'Items (Retailer Input)',  CHN:'谈判条款（零售商提案）',  RUS:''},
		{id:'Minimum Order & Discount Rate',  ENG:'Minimum Order & Discount Rate',  CHN:'最低订货量和折扣率',  RUS:''},
		{id:'Minimum Order',  ENG:'Minimum Order',  CHN:'最低订货量',  RUS:''},
		{id:'Discount Rate',  ENG:'Discount Rate',  CHN:'折扣率',  RUS:''},
		{id:'Edit',  ENG:'Edit',  CHN:'编辑',  RUS:''},
		{id:'View',  ENG:'View',  CHN:'查看',  RUS:''},
		{id:'Sales Target Volume & Bonus',  ENG:'Sales Target Volume & Bonus',  CHN:'目标销量和奖励',  RUS:''},
		{id:'Sales Target',  ENG:'Sales Target',  CHN:'目标销量',  RUS:''},
		{id:'Bonus',  ENG:'Bonus',  CHN:'奖励',  RUS:''},
		{id:'Payment Days',  ENG:'Payment Days',  CHN:'帐期',  RUS:''},
		{id:'Other Compensation',  ENG:'Other Compensation',  CHN:'其他支持',  RUS:''},
		{id:'Compare and Refresh',  ENG:'Compare and Refresh',  CHN:'比较和更新',  RUS:''},
		{id:'Copy from peer proposal',  ENG:'Copy from peer proposal',  CHN:'复制生产商的提案（将覆盖已存在的零售商提案）',  RUS:''},
		{id:'Please choose decision level',  ENG:'Please choose decision level',  CHN:'请选择决策层级',  RUS:''},
		{id:'Please choose bonus way',  ENG:'Please choose bonus way',  CHN:'请选择激励方式',  RUS:''},
		{id:'Amount',  ENG:'Amount',  CHN:'金额',  RUS:''},
		{id:'Rate',  ENG:'Rate',  CHN:'折扣比例',  RUS:''},
		{id:'Close',  ENG:'Close',  CHN:'关闭',  RUS:''},
		{id:'Warning Info',  ENG:"Time's up, this contract has been locked",  CHN:'已超过截止时间，合同被锁定。',  RUS:''},
		{id:'Check Warning',  ENG:"Check fail. Time's up, this contract has been locked",  CHN:'验证失败。已超过截止时间，合同被锁定。',  RUS:''},
		/*producerstep1*/
		{id:'Products portfolio',  ENG:'Products portfolio',  CHN:'产品组合',  RUS:''},
		{id:'Products portfolio Info',  ENG:'determine your products portfolio, i.e. brand names, variant(s) of each brand with their respective name(s) and product composition or product specification, including packaging format.',  CHN:'决定你的产品组合，如品牌名称、配方、包装等',  RUS:''},
		{id:'Step 1 of 4',  ENG:'Step 1 of 4',  CHN:'步骤 1 / 4',  RUS:''},
		{id:'Producer Step 1 of 4 Info',  ENG:'Products Portfolio Management',  CHN:'产品组合管理',  RUS:''},
		{id:'Category',  ENG:'Category',  CHN:'品类',  RUS:''},
		{id:'Elecssories',  ENG:'Elecssories',  CHN:'电子配件品类',  RUS:''},
		{id:'HealthBeauty',  ENG:'HealthBeauty',  CHN:'美容健康品类',  RUS:''},
		{id:'Elecsories',  ENG:'Elecsories',  CHN:'电子配件品类',  RUS:''},
		{id:'HealthBeauties',  ENG:'HealthBeauties',  CHN:'美容健康品类',  RUS:''},
		{id:'Health&Beauty',  ENG:'HealthBeauties',  CHN:'美容健康品类',  RUS:''},		
		{id:'Available Budget',  ENG:'Total Available Budget for Remaing Period',  CHN:'剩余阶段可用的总预算',  RUS:''},
		{id:'Producer Available Capacity',  ENG:'Current Period Available Capacity',  CHN:'当前阶段可用的产能',  RUS:''},
		{id:'Brand',  ENG:'Brand',  CHN:'品牌',  RUS:''},
		{id:'Variant',  ENG:'Variant',  CHN:'单品',  RUS:''},
		{id:'More',  ENG:'More',  CHN:'更多',  RUS:''},
		{id:'Delete',  ENG:'Delete',  CHN:'删除',  RUS:''},	
		{id:'Pack Format',  ENG:'Pack Format',  CHN:'包装规格',  RUS:''},
		{id:'Pack Format Info',  ENG:'is one value from the list ECONOMY, STANDARD, PREMIUM. Influences price and quality perceptions of a brand. Affects production cost. ',  CHN:'有三种包装规格选择：a)经济包，b)标准包，c)豪华包，包装会影响品牌价格感知和质量感知，也会影响生产成本。',  RUS:''},
		{id:'Technology Level',  ENG:'Technology Level',  CHN:'技术水平',  RUS:''},
		{id:'Technology Level Info',  ENG:'an Elecsorries and Health/Beauty product attribute; an index from 1 to 20 defining quality level of a product; in Elecsorries influences quality and ease of use perceptions; in Health/Beauty allows successful merging of active agent with smoothener; affects production cost. ',  CHN:'两个品类共有的属性特征，用指数1-20代表技术水平。在电子配件品类，技术水平影响质量和易用性感知，在美容健康品类，技术水平影响活力因子和光滑因子的融合程度。技术水平会影响生产成本。',  RUS:''},
		{id:'Design Level',  ENG:'Design Level',  CHN:'设计水平',  RUS:''},
		{id:'Design Level Info',  ENG:'an Elecsorries product attribute; an index from 1 to 20 defining design of a product; influences ease of use and quality perceptions; affects product cost. ',  CHN:'电子配件品类拥有的属性特征，用指数1-20表示，影响产品的易用性感知和质量感知，会影响生产成本。',  RUS:''},
		{id:'Quality-of-Raw-Materials',  ENG:'Quality-of-Raw-Materials',  CHN:'原材料质量',  RUS:''},
		{id:'Quality-of-Raw-Materials Info',  ENG:'an Elecsorries product attribute; an index from 1 to 22 defining quality of raw materials of a product; influences quality perception; affects product cost. ',  CHN:'电子配件品类拥有的属性特征，用指数1-22表示，影响产品的质量感知，会影响生产成本。',  RUS:''},
		{id:'Active agent',  ENG:'Active agent',  CHN:'活力因子',  RUS:''},
		{id:'Active agent Info',  ENG:'a Health/Beauties product attribute; an index from 1 to 20; influences performance perception; affects gentleness perception and product cost.',  CHN:'美容健康品类的属性特征，用指数1-20表示，影响产品效果和柔和度感知，也会影响生产成本。',  RUS:''},
		{id:'Smoothener Level',  ENG:'Smoothener Level',  CHN:'光滑因子',  RUS:''},
		{id:'Smoothener Level Info',  ENG:'a Health/Beauties product attribute; an index from 1 to 20; influences gentleness perception; affects product cost.',  CHN:'美容健康品类的属性特征，用指数1-20表示，影响柔和度感知及生产成本。',  RUS:''},
		{id:'Estimated Production Volume',  ENG:'Estimated Production Volume',  CHN:'预计产量',  RUS:''},
		{id:'Estimated Production Volume Info',  ENG:'used to calculate estimated product cost with given product composition; on step 2 you will have to put final decision on order. ',  CHN:'预计产量主要用于计算生产成本，即根据当前的产品配方要求得出的预计生产成本，你可以在下一步最终确认产量。',  RUS:''},
		{id:'Discontinue this product',  ENG:'Discontinue this product',  CHN:'停止生产',  RUS:''},
		{id:'Discontinue this product Info',  ENG:'take this decision with caution: all unsold stocks of this product will be automatically returned to your warehouse and scrapped at a cost to your business.',  CHN:'请注意:　所有期末未销售完的库存将退回到你的仓库进行销毁，成为你的成本。',  RUS:''},
		{id:'DisContinue',  ENG:'DisContinue',  CHN:'停产',  RUS:''},
		{id:'Continue',  ENG:'Continue',  CHN:'继续生产',  RUS:''},
		{id:'Current Price BM',  ENG:'Current Price B&M',  CHN:'当前对实体零售店的报价',  RUS:''},
		{id:'Current Price BM Info',  ENG:'list price for brick&mortar trade in current period; applicable for new launches only.',  CHN:'当前阶段对实体零售店的报价，只适用于新推出的产品。',  RUS:''},
		{id:'Current Price Emall',  ENG:'Current Price Emall',  CHN:'当前网上商城的零售价',  RUS:''},
		{id:'Current Price Emall Info',  ENG:'list and wholesale price for eMall in current period; applicable for new launches only. ',  CHN:'当前阶段在网上商城的零售价，只适用于新推出的产品。',  RUS:''},
		{id:'New Product',  ENG:'New Product',  CHN:'新产品',  RUS:''},
		{id:'Commit Portflio decision',  ENG:'Commit Portflio decision',  CHN:'提交产品组合决策',  RUS:''},
		{id:'Next',  ENG:'Next',  CHN:'下一步',  RUS:''},
		{id:'Launch New Brand',  ENG:'Launch New Brand',  CHN:'推出新品牌',  RUS:''},
		{id:'Under Existed Brand',  ENG:'Add new product under existed Brand',  CHN:'在现有品牌下推出新单品',  RUS:''},
		{id:'Choose Catagory',  ENG:'Choose Catagory',  CHN:'选择品类',  RUS:''},
		{id:'Choose Brand',  ENG:'Choose Brand',  CHN:'选择品牌',  RUS:''},
		{id:'Enter New Variant Name',  ENG:'Enter New Variant Name',  CHN:'输入新单品名称',  RUS:''},
		{id:'Enter New Brand Name',  ENG:'Enter New Brand Name',  CHN:'输入新品牌名称',  RUS:''},
		{id:'Add',  ENG:'Add',  CHN:'增加',  RUS:''},
		{id:'Cancel',  ENG:'Cancel',  CHN:'取消',  RUS:''},	
		{id:'Current period',  ENG:'Current period',  CHN:'当前阶段',  RUS:''},
		{id:'Previous period',  ENG:'Previous period',  CHN:'上一阶段',  RUS:''},
		{id:'Next period',  ENG:'Next period',  CHN:'下一阶段',  RUS:''},
		
		{id:'Current period Awareness achieve',  ENG:'Current period Awareness achieve',  CHN:'当前阶段收获',  RUS:''},
		{id:'Current period Investment Achieved Perception',  ENG:'Current period Investment Achieved Perception',  CHN:'当前投入收获感知',  RUS:''},
		{id:'Previous period Investment',  ENG:'Previous period Investment',  CHN:'上一阶段投入',  RUS:''},
		{id:'Convenience Perception',  ENG:'Convenience Perception',  CHN:'便利性感知',  RUS:''},
		{id:'Price Perception',  ENG:'Price Perception',  CHN:'价格感知',  RUS:''},


		{id:'Unit Cost',  ENG:'Unit Production Cost',  CHN:'单位生产成本',  RUS:''},
		{id:'Acquired Technology Level',  ENG:'Acquired Technology Level',  CHN:'当前拥有最高技术水平',  RUS:''},
		{id:'Acquired Design Level',  ENG:'Acquired Design Level',  CHN:'当前拥有最高设计水平',  RUS:''},
		{id:'Acquired Active agent',  ENG:'Acquired Active agent',  CHN:'当前拥有活力因子',  RUS:''},
		{id:'Acquired Quality-of-Raw-Materials',  ENG:'Acquired Quality-of-Raw-Materials',  CHN:'当前可用的最高原材料质量',  RUS:''},
		{id:'Acquired Smoothener Level',  ENG:'Acquired Smoothener Level',  CHN:'当前拥有最高光滑因子',  RUS:''},
		{id:'Sales Volume',  ENG:'Sales Volume',  CHN:'销量',  RUS:''},
		{id:'Unit Production Cost',  ENG:'Unit Production Cost',  CHN:'单位生产成本',  RUS:''},
		{id:'Production Volume',  ENG:'Production Volume',  CHN:'产量',  RUS:''},
		{id:'Initial Inventory',  ENG:'Initial Inventory',  CHN:'期初库存',  RUS:''},
		{id:'ECONOMY',  ENG:'ECONOMY',  CHN:'经济包',  RUS:''},
		{id:'STANDARD',  ENG:'STANDARD',  CHN:'标准包',  RUS:''},
		{id:'PREMIUM',  ENG:'PREMIUM',  CHN:'豪华包',  RUS:''},
		{id:'SL_BASE',  ENG:'BASE',  CHN:'基础',  RUS:''},
		{id:'SL_FAIR',  ENG:'FAIR',  CHN:'一般',  RUS:''},
		{id:'SL_MEDIUM',  ENG:'MEDIUM',  CHN:'中等',  RUS:''},
		{id:'SL_ENHANCED',  ENG:'ENHANCED',  CHN:'好',  RUS:''},
		{id:'SL_PREMIUM',  ENG:'PREMIUM',  CHN:'优质',  RUS:''},
		{id:'BASE',  ENG:'BASE',  CHN:'基础',  RUS:''},
		{id:'FAIR',  ENG:'FAIR',  CHN:'一般',  RUS:''},
		{id:'MEDIUM',  ENG:'MEDIUM',  CHN:'中等',  RUS:''},
		{id:'ENHANCED',  ENG:'ENHANCED',  CHN:'好',  RUS:''},
		{id:'PREMIUM',  ENG:'PREMIUM',  CHN:'优质',  RUS:''},
		{id:'Check Error',  ENG:"Check fail. This decision has been locked",  CHN:'验证失败。决策已经被锁定。',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'Warning! Commit confirmation',  ENG:'Warning! Commit confirmation',  CHN:'注意！提交确认',  RUS:''},
		{id:'Producer portfolio confirm info',  ENG:'You and your team member will not be able to modify portfolio decision this period after submitting the decision.',  CHN:'选择提交之后，你和你所在小组的其他成员本阶段将无法再次修改产品组合决策。',  RUS:''},
		{id:'Take this action',  ENG:'Take this action',  CHN:'确认提交',  RUS:''},
		{id:'Cancel',  ENG:'Cancel',  CHN:'取消',  RUS:''},

		/*producerstep2*/
		{id:'Production and pricing',  ENG:'Production and pricing',  CHN:'生产和定价',  RUS:''},
		{id:'Production and pricing Info',  ENG:'after you have finalized you product portfolio for coming period, you should tell the system volumes to be produced this period and wholesale prices for next period',  CHN:'确定完产品组合后，你需要确定本阶段的产量，并为下阶段制订价格。',  RUS:''},
		{id:'Next Price BM',  ENG:'Next Price B&M',  CHN:'下阶段对实体零售店的报价',  RUS:''},
		{id:'Next Price BM Info',  ENG:'list price for brick&mortar trade in next period.',  CHN:'下阶段对实体零售店的报价信息',  RUS:''},
		{id:'Next Price Emall',  ENG:'Next Price Emall',  CHN:'下阶段网上商城的零售价',  RUS:''},
		{id:'Next Price Emall Info',  ENG:'list and wholesale price for eMall in next period.',  CHN:'下阶段网上商城的零售价信息',  RUS:''},
		{id:'Step 2 of 4',  ENG:'Step 2 of 4',  CHN:'步骤 2 / 4',  RUS:''},
		{id:'Production Volume Info',  ENG:'volume you order from your factory; check your production capacity for the limits of your order.',  CHN:'你要求工厂生产的数量。注意查看你的产能信息，这是你生产订单的上限。',  RUS:''},
		{id:'Back',  ENG:'Back',  CHN:'上一步',  RUS:''},

		/*producer step 3*/
		{id:'Advertising',  ENG:'Advertising',  CHN:'广告',  RUS:''},
		{id:'Producer Advertising Info',  ENG:'After setting production volumes and future wholesale prices you need to take some marketing decisions both market related and national.',  CHN:'现在你需要制订广告决策，包括全国市场和本地市场。',  RUS:''},
		{id:'Step 3 of 4',  ENG:'Step 3 of 4',  CHN:'步骤 3 / 4',  RUS:''},
		{id:'Urban',  ENG:'Urban',  CHN:'城市',  RUS:''},
		{id:'Rural',  ENG:'Rural',  CHN:'农村',  RUS:''},
		{id:'brand awareness',  ENG:'brand awareness',  CHN:'品牌认知度',  RUS:''},
		{id:'brand visibility share',  ENG:'brand visibility share',  CHN:'品牌可见度份额',  RUS:''},
		{id:'Urban Advertising Off-Line',  ENG:'Urban Advertising Off-Line',  CHN:'城市地区传统广告',  RUS:''},
		{id:'Urban Advertising Off-Line Info',  ENG:'budget you spend to advertise your brands in conventional media (printed and TV) in Urban market.',  CHN:'你在城市地区的传统媒体广告投入（如平面媒体和电视）',  RUS:''},
		{id:'Urban Traditional Trade Support',  ENG:'Urban Traditional Trade Support',  CHN:'城市地区传统渠道支持',  RUS:''},
		{id:'Traditional Trade Support',  ENG:'Traditional Trade Support',  CHN:'传统渠道支持',  RUS:''},
		{id:'Urban Traditional Trade Support Info',  ENG:'budget you invest to support of Traditional Trade in Urban market; it increases visibility of your brands at Traditional Trade. ',  CHN:'你在城市地区传统渠道的投入，提高品牌在传统渠道的可见度份额。',  RUS:''},
		{id:'Rural Advertising Off-Line',  ENG:'Rural Advertising Off-Line',  CHN:'农村地区传统广告',  RUS:''},
		{id:'Rural Advertising Off-Line Info',  ENG:'budget you spend to advertise your brands in conventional media (printed and TV) in Rural market. ',  CHN:'你在农村地区的传统媒体广告投入（如平面媒体和电视）',  RUS:''},
		{id:'Rural Traditional Trade Support',  ENG:'Rural Traditional Trade Support',  CHN:'农村地区传统渠道支持',  RUS:''},
		{id:'Rural Traditional Trade Support Info',  ENG:'budget you invest to support of Traditional Trade in Rural market; it increases visibility of your brands at Traditional Trade. ',  CHN:'你在农村地区传统渠道的投入，提高品牌在传统渠道的可见度份额。',  RUS:''},
		{id:'National advertising online',  ENG:'National advertising online',  CHN:'全国性网络广告',  RUS:''},
		{id:'E-Mall visibility investment',  ENG:'E-Mall visibility investment',  CHN:'网上商城的可见度投资',  RUS:''},
		{id:'E-Mall visibility investment Info',  ENG:'budget invested in increasing visibility of your brands at eMall.',  CHN:'用于提高品牌在网上商城可见度的投资',  RUS:''},
		{id:'On-line Advertising',  ENG:'On-line Advertising',  CHN:'网络广告',  RUS:''},
		{id:'On-line Advertising Info',  ENG:'budget spent to advertise your brands on the Internet, including social media.',  CHN:'你在网络包括社交媒体上用于提高品牌知名度的投资',  RUS:''},

		/*producer step 4*/
		{id:'Category Decision',  ENG:'Category Decision',  CHN:'品类决策',  RUS:''},
		{id:'Category Decision Info',  ENG:'At last you have to make decisions influencing whole category. These decisions are long-term investments, that is why they are not taken from your limited operational budget, you borrow these investments from capital market at a cost. Keep in mind that your long-term investments increase your fixed assets and consequently costs of running business. ',  CHN:'制订品类层面的决策，这属于公司长期决策，这部分投资不占用你有限的营业预算，而是以一定成本从资本市场获得。请注意长期投资会增加你的固定资产，最终会增加你的营业资本。',  RUS:''},
		{id:'Step 4 of 4',  ENG:'Step 4 of 4',  CHN:'步骤 4 / 4',  RUS:''},
		{id:'in capacity change',  ENG:'Investment in Capacity Change',  CHN:'产能投资',  RUS:''},
		{id:'in capacity change Info',  ENG:"to extend your capacity you have to invest a period before it gets ready; current period extension is also possible but at 50% higher charge; your capacity increases your fixed assets and labor cost; you cannot sell out or lease your capacity to other players.",  CHN:'通常需要提前一个阶段投资下阶段的产能。你也可以选择在当前阶段立刻提高产能，但是成本增加50%，你的固定资产和劳动力成本也会因此增加。产能一旦增加，你不能出售或租赁给其他公司。',  RUS:''},
		{id:'improve Available Technology',  ENG:'Investment to improve Available Technology',  CHN:'技术水平投资',  RUS:''},
		{id:'improve Available Technology Info',  ENG:'applies to both categories; you start with level 7 and can increase it to 20 by the session end; increases your fixed assets.',  CHN:'技术水平适用于两个品类，每家公司的最高技术水平在开始阶段都是７，到模拟结束时最高可以增加到20。提高技术水平会增加你的固定资产。',  RUS:''},
		{id:'improve Flexibility',  ENG:'Investment to improve Flexibility',  CHN:'灵活性投资',  RUS:''},
		{id:'improve Flexibility Info',  ENG:"applies to both categories; helps you to automatically adjust your production to correspond to orders placed by retailers; affects your fixed assets. ",  CHN:'灵活性适用于两个品类，它能根据零售商实际订单数量自动调整产量。灵活性投资会增加你的固定资产。',  RUS:''},
		{id:'improve Design Know-How',  ENG:'Investment to improve Design Know-How',  CHN:'对行业知识技能的投资',  RUS:''},
		{id:'improve Design Know-How Info',  ENG:'Health/Beauties; you start with level 7 and can increase it to 20 by the session end; increases your fixed assets.',  CHN:'适用于美容健康品类，每家公司的最高水平在开始阶段都为７，到模拟结束时最高可以增加到20。提高know how水平，会增加你的固定资产。',  RUS:''},
		{id:'Production capacity',  ENG:'Production capacity',  CHN:'产能',  RUS:''},
		{id:'Acquired production flexibility',  ENG:'Acquired production flexibility',  CHN:'所拥有的生产灵活性',  RUS:''},

		/*retailer step 1*/
		{id:'Rteailer Advertising Info',  ENG:'define your marketing investments. These investments are given to online and offline agencies that carry out marketing campaigns for you. You can also define what slogan your agency promotes for you, you just need to allocate your budget between three shopper perceptions (convenience, assortment and price) in such a way that dimension you promote most gets more money.',  CHN:'制订你的市场决策。第三方网络和传统广告机构会根据你的要求完成市场活动。你只需确定在三个感知维度（便利性，产品组合和价格）上的预算分配。',  RUS:''},
		{id:'More information',  ENG:'More information',  CHN:'更多信息',  RUS:''},
		{id:'Convenience Off-line',  ENG:'Convenience Off-line',  CHN:'传统广告 - 便利性',  RUS:''},
		{id:'Convenience Off-line Info',  ENG:'budget you give offline advertising agencies to promote convenience of your store chain. ',  CHN:'给传统广告机构的预算，用于宣传门店的便利性。',  RUS:''},
		{id:'Assortment Off-line',  ENG:'Assortment Off-line',  CHN:'传统广告 - 产品丰富性',  RUS:''},
		{id:'Assortment Off-line Info',  ENG:'budget you give offline advertising agencies to promote assortment of your store chain. ',  CHN:'给传统广告机构的预算，用于宣传门店的产品丰富性。',  RUS:''},
		{id:'Price Off-line',  ENG:'Price Off-line',  CHN:'传统广告 - 价格',  RUS:''},
		{id:'Price Off-line Info',  ENG:'budget you give offline advertising agencies to promote price level of your store chain. ',  CHN:'给传统广告机构的预算，用于宣传门店的价格水平。',  RUS:''},
		{id:'Convenience On-line',  ENG:'Convenience On-line',  CHN:'网络广告 - 便利性',  RUS:''},
		{id:'Convenience On-line Info',  ENG:'budget you give online advertising agencies to promote convenience of your store chain.',  CHN:'给网络告机构的预算，用于宣传门店的便利性。',  RUS:''},
		{id:'Assortment On-line',  ENG:'Assortment On-line',  CHN:'网络广告 - 产品丰富性',  RUS:''},
		{id:'Assortment On-line Info',  ENG:'budget you give online advertising agencies to promote assortment of your store chain.',  CHN:'给网络广告机构的预算，用于宣传门店的产品丰富性。',  RUS:''},
		{id:'Price On-line',  ENG:'Price On-line',  CHN:'网络广告 - 价格',  RUS:''},
		{id:'Price On-line Info',  ENG:'budget you give online advertising agencies to promote price level of your store chain. ',  CHN:'给网络广告机构的预算，用于宣传门店的价格水平。',  RUS:''},

		/*retailer step 2*/
		{id:'Market',  ENG:'Market',  CHN:'市场',  RUS:''},
		{id:'Market Info',  ENG:'After completing national set of decisions, it would be logical to work on the decisions specific for each of the markets. They will be of a strategic essence and influence your store chain positioning on the market. ',  CHN:'制订本地市场的决策，这将影响门店在当地市场的定位。',  RUS:''},
		{id:'In-Store Service Level',  ENG:'In-Store Service Level',  CHN:'店内服务水平',  RUS:''},
		{id:'In-Store Service',  ENG:'In-Store Service',  CHN:'店内服务水平',  RUS:''},
		{id:'In-store Service Level Info',  ENG:'one of the following BASE, FAIR, MEDIUM, ENHANCED, PREMIUM; represents integrally expenditures of a retail chain on its service (labor costs, equipment and fixtures, lighting, etc.); influences convenience and assortment directly and price perception in reverse',  CHN:'提供“基础”、“一般”、“中等”、“好”和“优质”五种选择，直接影响购物者对你门店的便利性和产品组合感知，对价格感知起反作用。',  RUS:''},
		{id:'Elecssories Selling surface',  ENG:'Elecssories Shelf space',  CHN:'电子配件品类的货架份额',  RUS:''},
		{id:'Elecssories Selling surface Info',  ENG:'you may decide to increase store space allocated for one category and decrease accordingly another; total space allocated to both categories should be 100%; you must not kill any category, provisionally minimum store space must be 35%, therefore maximum store space per category could be 65%.',  CHN:'你可以灵活分配两个品类的货架份额比例，两个品类加起来等于100%。为了避免扼杀任一品类，分配给一个品类的货架份额至少为35%，即任一品类能分配的货架份额最高为65%。',  RUS:''},
		{id:'HealthBeauty Selling surface',  ENG:'HealthBeauty Shelf space',  CHN:'美容健康品类的货架份额',  RUS:''},
		{id:'HealthBeauty Selling surface Info',  ENG:'you may decide to increase store space allocated for one category and decrease accordingly another; total space allocated to both categories should be 100%; you must not kill any category, provisionally minimum store space must be 35%, therefore maximum store space per category could be 65%. ',  CHN:'你可以灵活分配两个品类占据的货架比例，两个品类加起来等于100%。为了避免扼杀任一品类，分配给一个品类的货架份额至少为35%，即任一品类能分配的货架份额最高为65%。',  RUS:''},
		{id:'Local Convenience Advertising',  ENG:'Local Convenience Advertising',  CHN:'本地市场广告 - 便利性',  RUS:''},
		{id:'Local Convenience Perception',  ENG:'Local Convenience Perception',  CHN:'本地广告期望',  RUS:''},
		{id:'Local Convenience Advertising Info',  ENG:'budget you spend to advertise your store chain locally (outdoors Advertising, leaflets); promotes convenience of your stores.',  CHN:'门店在本地投放的广告（户外广告，宣传单页等），宣传门店的便利性。',  RUS:''},
		{id:'Local Assortment Advertising',  ENG:'Local Assortment Advertising',  CHN:'本地市场广告 - 产品丰富性',  RUS:''},
		{id:'Local Assortment Advertising Info',  ENG:'budget you spend to advertise your store chain locally (outdoors advertising, leaflets); promotes assortment of your stores.',  CHN:'门店在本地投放的广告（户外广告，宣传单页等），宣传门店的产品丰富性。',  RUS:''},
		{id:'Local Price Advertising',  ENG:'Local Price Advertising',  CHN:'本地市场广告 - 价格',  RUS:''},
		{id:'Local Price Perception',  ENG:'Local Price Perception',  CHN:'本地价格期望',  RUS:''},
		{id:'Local Price Advertising Info',  ENG:'budget you spend to advertise your store chain locally (outdoors advertising, leaflets); promotes price perception of your stores. ',  CHN:'门店在本地投放的广告（户外广告，宣传单页等），宣传门店的价格水平。',  RUS:''},
		{id:'Allocate Empty Place',  ENG:'Allocate Empty Place',  CHN:'分配空的货架',  RUS:''},
		{id:'Allocate Empty Place Info',  ENG:'Allocate Empty Place Info',  CHN:'分配空的货架',  RUS:''},
		{id:'Allocate',  ENG:'Allocate',  CHN:'分配',  RUS:''},
		{id:'No',  ENG:'No',  CHN:'不分配',  RUS:''},

		/*retailer step 3*/
		{id:'Private Labels Composition',  ENG:'Private Labels Composition',  CHN:'自有品牌决策',  RUS:''},
		{id:'Private Labels Composition Info',  ENG:'At this step you have to think about and take your decision on the portfolio of your private labels. You start with one PL per category per market. You may have three PLs per category per market.',  CHN:'制订你的自有品牌组合决策。你在开始阶段每个市场每个品类各有一个自有品牌，最多可以在每个市场每个品类各拥有三个自有品牌。',  RUS:''},
		{id:'Unit Production Cost',  ENG:'Unit Production Cost',  CHN:'单位生产成本',  RUS:''},
		{id:'Retailer Discontinue this product',  ENG:'Discontinue this product',  CHN:'停止销售',  RUS:''},
		{id:'Retailer Discontinue this product Info',  ENG:'take this decision with caution: all unsold stocks of this product will be automatically returned to your warehouse and scrapped at a cost to your business.',  CHN:'请注意:　所有期末未销售完的库存将退回到你的仓库进行销毁，成为你的成本。',  RUS:''},
		{id:'Retailer DisContinue',  ENG:'DisContinue',  CHN:'停止销售',  RUS:''},
		{id:'Retailer Continue',  ENG:'Continue',  CHN:'继续销售',  RUS:''},
		{id:'Inventory Design Level',  ENG:'Inventory Design Level',  CHN:'库存中产品的设计水平',  RUS:''},	
		{id:'Inventory Active agent',  ENG:'Inventory Active agent',  CHN:'库存中产品的活力因子',  RUS:''},	
		{id:'Inventory Technology Level',  ENG:'Inventory Technology Level',  CHN:'库存中产品的技术水平',  RUS:''},	
		{id:'Inventory Quality-of-Raw-Materials',  ENG:'Inventory Quality-of-Raw-Materials',  CHN:'库存中产品的原材料质量',  RUS:''},	
		{id:'Inventory Smoothener Level',  ENG:'Inventory Smoothener Level',  CHN:'库存中产品的光滑因子',  RUS:''},											

		/*retailer step 4*/
		{id:'Order Pricing Shelf',  ENG:'Order, Pricing and Shelf Allocation',  CHN:'订货、定价和货架分配',  RUS:''},
		{id:'Order Pricing Shelf Info',  ENG:'placing orders with suppliers, allocating shelf space, setting retail price and defining promotions for each brand (both supplier and private label) at each market.',  CHN:'确定向生产商的定货量，制订零售价，分市场、按品类为每个单品（包括生产商和你的自有品牌）分配货架空间，制订促销计划。',  RUS:''},
		{id:'Available ShelfSpace',  ENG:'Available ShelfSpace',  CHN:'可分配的货架空间',  RUS:''},
		{id:'Private Label',  ENG:'Private Label',  CHN:'自有品牌',  RUS:''},		
		{id:'List Price',  ENG:'List Price',  CHN:'供应商报价',  RUS:''},
		{id:'Order Price',  ENG:'Order Price',  CHN:'供应商报价',  RUS:''},
		{id:'Closing Inventory',  ENG:'Closing Inventory',  CHN:'期末库存',  RUS:''},
		{id:'Sales Volume at your store',  ENG:'Sales Volume at your store',  CHN:'门店的销量',  RUS:''},
		{id:'Shelf Space at your store',  ENG:'Shelf Space at your store',  CHN:'占门店的货架空间',  RUS:''},
		{id:'Market Price at your store',  ENG:'Market Price at your store',  CHN:'门店的零售价',  RUS:''},
		{id:'Net Price at your store',  ENG:'Net Price at your store',  CHN:'门店的净零售价',  RUS:''},
		{id:'Net Price',  ENG:'Net Price',  CHN:'门店的净零售价',  RUS:''},
		{id:'weeks',  ENG:'weeks',  CHN:'周数',  RUS:''},
		{id:'Order Volume',  ENG:'Order Volume',  CHN:'订货量',  RUS:''},
		{id:'Order Volume Info',  ENG:'volume your order from manufacturer; you need to take into account brand potential, your current stocks and negotiated volumes/discounts to make a balanced decision.',  CHN:'你向生产商的下单量，建议综合考虑品牌的潜力、前期库存、你和生产商约定的数量／折扣协议等。',  RUS:''},
		{id:'Shelf Space',  ENG:'Shelf Space',  CHN:'货架份额',  RUS:''},
		{id:'Shelf Space Info',  ENG:'you may give a brand 5% of shelf space minimum. ',  CHN:'每个品牌最低分配的货架份额不能低于5%',  RUS:''},
		{id:'Retail Price',  ENG:'Retail Price',  CHN:'零售价',  RUS:''},
		{id:'Retail Price Info',  ENG:'your normal retail price which is the basis for promotional discounts. ',  CHN:'这是做促销时的正常基础价格。',  RUS:''},
		{id:'Promotions Frequency',  ENG:'Promotions Frequency',  CHN:'促销频率',  RUS:''},
		{id:'Frequency',  ENG:'Frequency',  CHN:'频率',  RUS:''},
		{id:'Promotions',  ENG:'Promotions',  CHN:'促销',  RUS:''},
		{id:'Promotions Frequency Info',  ENG:'number of weeks out of 26 in each period when you plan to make your promotion campaign effective.',  CHN:'26周中促销的周数',  RUS:''},
		{id:'Reduction Rate',  ENG:'Promotion Rate',  CHN:'折扣率',  RUS:''},
		{id:'Reduction Rate Info',  ENG:'discount percent off normal retail price effective during promotions.',  CHN:'在促销期间提供的优惠折扣比率',  RUS:''},
		{id:'Add Order',  ENG:'Add Order',  CHN:'增加订单',  RUS:''},
		{id:'Order Product',  ENG:'Order Product',  CHN:'选择商品',  RUS:''},
		{id:'Produced by',  ENG:'Produced by',  CHN:'生产厂家',  RUS:''},
		/*error message need some time to clear up*/

		/*decision*/
		{id:'Not set',  ENG:'Not set',  CHN:'请选择',  RUS:''},
		{id:'Input a number',  ENG:'Enter a negative number(Allow two decimal places)',  CHN:'请输入非负数(可保留两位小数)',  RUS:''},
		{id:'fail',  ENG:'check fail,please call the admin',  CHN:'验证失败,请联系管理员',  RUS:''},
		{id:'Input a Integer',  ENG:'Input a nonnegative integer',  CHN:'请输入非负整数',  RUS:''},
		{id:'Input range',  ENG:'Input range',  CHN:'输入范围',  RUS:''},
		{id:'Error',  ENG:'Error',  CHN:'错误',  RUS:''},
		{id:'Success',  ENG:'Success',  CHN:'成功',  RUS:''},
		{id:'Warning',  ENG:'Warning',  CHN:'警告',  RUS:''},
		{id:'Add new brand successful',  ENG:'Add new brand successful',  CHN:'添加新品牌成功',  RUS:''},
		{id:'Add new brand fail',  ENG:'Add new brand fail',  CHN:'添加新品牌失败',  RUS:''},
		{id:'more than 5',  ENG:'There is more than 5 in this category',  CHN:'此品类下已有5个品牌',  RUS:''},
		{id:'another brand',  ENG:'There is another brand in this category',  CHN:'此品类下已有同名品牌',  RUS:''},
		{id:'Add new variant successful',  ENG:'Add new variant successful',  CHN:'添加新单品成功',  RUS:''},
		{id:'Add new variant fail',  ENG:'Add new variant fail',  CHN:'添加新单品失败',  RUS:''},
		{id:'more than 3',  ENG:'There is more than 3 in this brand',  CHN:'此品牌下已有3个单品',  RUS:''},	
		{id:'another variant',  ENG:'There is another variant in this brand',  CHN:'此品牌下已有同名单品',  RUS:''},	
		{id:'more than 4',  ENG:'There is more than 4 in this category',  CHN:'此品类下已有4个品牌',  RUS:''},
		/*contract*/
		{id:'Add contratct successful',  ENG:'Add contratct successful',  CHN:'添加合同成功',  RUS:''},	
		{id:'Add contratct fail',  ENG:'Add contratct fail',  CHN:'添加合同失败',  RUS:''},	
		{id:'another contract',  ENG:'There is another contract with this retailer this period',  CHN:'本轮已有一份与此供应商的合同',  RUS:''},	
		{id:'Duplicate contratct successful',  ENG:'Duplicate contratct successful',  CHN:'合同复制成功',  RUS:''},	
		{id:'Duplicate contratct fail',  ENG:'Duplicate contratct fail',  CHN:'合同复制失败',  RUS:''},	
		{id:'another contractCode',  ENG:'There is another contractCode in this game',  CHN:'此游戏中已存在同名合同',  RUS:''},	
		{id:'Choose Player',  ENG:'Choose Player',  CHN:'选择角色',  RUS:''},	
		/*login*/
		{id:'Login successful',  ENG:'Login successful',  CHN:'登录成功',  RUS:''},	
		{id:'Login fail',  ENG:'Login fail',  CHN:'登录失败',  RUS:''},	
		/*reject*/
		{id:'load brands fail',  ENG:'load brands fail,please call the admin',  CHN:'加载品牌失败，请联系管理员',  RUS:''},	
		{id:'load products fail',  ENG:'load products fail,please call the admin',  CHN:'加载单品失败，请联系管理员',  RUS:''},	
		{id:'load categorys fail',  ENG:'load categorys fail,please call the admin',  CHN:'加载品类失败，请联系管理员',  RUS:''},	
		{id:'showView fail',  ENG:'showView fail,please call the admin',  CHN:'加载页面失败，请联系管理员',  RUS:''},	
		{id:'Check ProducersDecision status fail',  ENG:'Check SuppliersDecision status fail,please call the admin',  CHN:'验证用户决策失败，请联系管理员',  RUS:''},	
		{id:'start to show view',  ENG:'start to show view',  CHN:'加载页面',  RUS:''},	
		{id:'Facilitator Decision',  ENG:'Facilitator Decision',  CHN:'Facilitator Decision',  RUS:''},	
		{id:'Facilitator Decision Info',  ENG:'Facilitator Decision Info',  CHN:'Facilitator Decision Info',  RUS:''},	
		{id:'Choose Your Role',  ENG:'Choose Your Role',  CHN:'请选择角色',  RUS:''},	
		{id:'Choose Period',  ENG:'Choose Period',  CHN:'请选择阶段',  RUS:''},	
		{id:'OK',  ENG:'OK',  CHN:'确定',  RUS:''},	
		
		/*summaryReport*/
		{id:'Summary Report',  ENG:'Summary Report',  CHN:'总结报告',  RUS:''},	
		{id:'Summary Report Info',  ENG:'Summary Report Info',  CHN:'总结报告介绍',  RUS:''},	
		{id:'Summary Report popInfo',  ENG:'This table is the consolidated profit/loss statement of both categories at SKU level.',  CHN:'总结报告介绍',  RUS:''},	
		{id:'Performance Highlights',  ENG:'Performance Highlights',  CHN:'突出业界',  RUS:''},	
		{id:'Performance Highlights Info',  ENG:'This table summarizes key performance indicators for suppliers and retailers. For suppliers, the sales figures refer to sales to the retailers. All market share figures are consumer market shares.',  CHN:'Performance Highlights Info 介绍',  RUS:''},	
		{id:'Market Shares',  ENG:'Market Shares',  CHN:'市场份额',  RUS:''},	
		{id:'Market Shares Info',  ENG:'These graphs show the consumer market shares for suppliers and retailers (private label) by market, consumer segment and shopper segment. More detailed information can be obtained by moving the cursor over the colors in the bar charts.',  CHN:'市场份额介绍',  RUS:''},	
		{id:'Market Sales',  ENG:'Market Sales.',  CHN:'市场销售',  RUS:''},	
		{id:'Market Sales Info',  ENG:'These graphs show the consumer sales figures for suppliers and retailers (private label) by market, consumer segment and shopper segment. More detailed information can be obtained by moving the cursor over the colors in the bar charts.',  CHN:'市场销售介绍',  RUS:''},	
		{id:'Segment Leadership',  ENG:'Segment Leadership',  CHN:'领导力',  RUS:''},	
		{id:'Segment Leadership Info',  ENG:'This table shows the top two consumer share leaders by category, consumer segment and shopper segment.',  CHN:'领导力介绍',  RUS:''},			
		{id:'Cross-Segment Sales Volumes',  ENG:'Cross-Segment Sales Volumes',  CHN:'跨段销售量',  RUS:''},	
		{id:'Cross-Segment Sales Volumes Info',  ENG:'These graphs show, by category and by market, the sales volume bought by each shopper segment.',  CHN:'跨段销售量',  RUS:''},	
		{id:'Product Portfolio',  ENG:'Product Portfolio',  CHN:'产品组合',  RUS:''},	
		{id:'Product Portfolio Info',  ENG:'This table shows the technical design specifications of all SKUs in the market.',  CHN:'产品组合介绍',  RUS:''},	
		{id:'eMall Prices and Promotion Intensity',  ENG:'eMall Prices & Promotion Intensity',  CHN:'网上价格和促销强度',  RUS:''},	
		{id:'eMall Prices and Promotion Intensity Info',  ENG:'This table shows the net online retail prices and promotion intensity.',  CHN:'网上价格和促销强度介绍',  RUS:''},	
		{id:'Financial Results',  ENG:'Financial Results',  CHN:'财务业绩',  RUS:''},	
		{id:'Consolidated Profit & Loss Statement',  ENG:'Consolidated Profit & Loss Statement',  CHN:'合并盈利和亏损声明',  RUS:''},	
		{id:'B&M Business Profit & Loss Statement',  ENG:'B&M Business Profit & Loss Statement',  CHN:'领头企业盈利和亏损声明',  RUS:''},	
		{id:'Online Business Profit & Loss Statement',  ENG:'Online Business Profit & Loss Statement',  CHN:'在线业务盈利和亏损声明',  RUS:''},	
		{id:'Profitability by Channel',  ENG:'Profitability by Channel',  CHN:'盈利通道',  RUS:''},	
		{id:'Last Period Negotiations',  ENG:'Last Period Negotiations',  CHN:'最后一期的谈判',  RUS:''},	
		{id:'Last Period Negotiations Info',  ENG:'This table summarizes the negotiation agreements made during the last period and whether or not those agreements were honored.',  CHN:'最后一期的谈判介绍',  RUS:''},	
		{id:'Situation Report',  ENG:'Situation Report',  CHN:'情况报告',  RUS:''},
		{id:'Key Performance Indicators',  ENG:'Key Performance Indicators',  CHN:'关键性能指标',  RUS:''},
		{id:'Awareness',  ENG:'Awareness',  CHN:'认知度',  RUS:''},
		{id:'Perceptions',  ENG:'Perceptions',  CHN:'认知',  RUS:''},
		{id:'Behavior',  ENG:'Behavior',  CHN:'行为',  RUS:''},
		{id:'Retailer Prices and Promotion Intensity',  ENG:'Retailer Prices & Promotion Intensity',  CHN:'零售商的价格和促销强度',  RUS:''},
		{id:'Supplier Intelligence',  ENG:'Supplier Intelligence',  CHN:'供应商情报',  RUS:''},
		{id:'Supplier Intelligence Info',  ENG:'Supplier Intelligence Info',  CHN:'供应商情报介绍',  RUS:''},
		{id:'Retailer Intelligence',  ENG:'Retailer Intelligence',  CHN:'零售商情报',  RUS:''},
		{id:'Retailer Intelligence Info',  ENG:'This table summarizes retailer intelligence information. Online and Offline advertising are national expenditures (ie, not broken down my market) and we repeat the national figures under both markets. Shelf space allocations are shown by brand but moving the cursor on any brand name will reveal the shelf space allocations for all the variants of that brand (SKU level).',  CHN:'零售商情报介绍',  RUS:''},
		{id:'Forecasts',  ENG:'Forecasts',  CHN:'预测',  RUS:''},

		{id:'Volume',  ENG:'Volume',  CHN:'销售量',  RUS:''},
		{id:'Value',  ENG:'Value',  CHN:'销售额',  RUS:''},
		{id:'Consumer Market Shares',  ENG:'Consumer Market Shares',  CHN:'消费者市场份额',  RUS:''},
		{id:'Value Market Shares',  ENG:'Value Market Shares',  CHN:'Value Market Shares',  RUS:''},
		{id:'Volume Market Shares',  ENG:'Volume Market Shares',  CHN:'Volume Market Shares',  RUS:''},
		{id:'Cumulative Investments',  ENG:'Cumulative Investments',  CHN:'累计投资',  RUS:''},
		{id:'Promotion Intensity',  ENG:'Promotion Intensity',  CHN:'促销强度',  RUS:''},
		{id:'Promotion Intensity Info',  ENG:'Promotion Intensity Info',  CHN:'促销强度介绍',  RUS:''},
		{id:'Net Online Retail Price',  ENG:'Net Online Retail Price',  CHN:'网上售价',  RUS:''},
		{id:'Change over the Previous Period',  ENG:'Change over the Previous Period',  CHN:'对比上一轮改变',  RUS:''},
		{id:'Change from Previous Period',  ENG:'Change over the Previous Period',  CHN:'对比上一轮改变',  RUS:''},
		{id:'Length of Promotion',  ENG:'Length of Promotion',  CHN:'推广力度',  RUS:''},
		{id:'Depth of Promotion',  ENG:'Depth of Promotion',  CHN:'推广深度',  RUS:''},
		{id:'Facilitator Report',  ENG:'Facilitator Report',  CHN:'讲师报告',  RUS:''},
		{id:'B&M Only',  ENG:'B&M Only',  CHN:'实体店',  RUS:''},
		{id:'Online Only',  ENG:'Online Only',  CHN:'网上商城',  RUS:''},
		{id:'Mixed',  ENG:'Mixed',  CHN:'混合',  RUS:''},
		{id:'over previous period',  ENG:'over previous period',  CHN:'对比上一轮',  RUS:''},
		{id:'Number 1',  ENG:'Number 1',  CHN:'第一名',  RUS:''},
		{id:'Number 2',  ENG:'Number 2',  CHN:'第二名',  RUS:''},
		{id:'SKU name',  ENG:'SKU name',  CHN:'商品名称',  RUS:''},
		{id:'Share',  ENG:'Share',  CHN:'份额',  RUS:''},
		{id:'Consumer Segments',  ENG:'Consumer Segments',  CHN:'消费者细分',  RUS:''},
		{id:'Shopper Segments',  ENG:'Shopper Segments',  CHN:'顾客细分',  RUS:''},
		{id:'Volume Sales',  ENG:'Volume Sales',  CHN:'销量',  RUS:''},
		{id:'Value Sales',  ENG:'Value Sales',  CHN:'销售额',  RUS:''},
		{id:'Market Shares by Consumer Segment',  ENG:'Market Shares by Consumer Segment',  CHN:'通过消费者细分市场份额',  RUS:''},
		{id:'Market Shares by Shopper Segment',  ENG:'Market Shares by Shopper Segment',  CHN:'通过购买者细分市场份额',  RUS:''},
		{id:'Consolidated Profit & Loss Statement Info',  ENG:'This table gives a consolidated Profit & Loss statement by category in each channel.',  CHN:'Consolidated Profit & Loss Statement介绍',  RUS:''},
		{id:'B&M Business',  ENG:'B&M Business',  CHN:'实体零售店',  RUS:''},
		{id:'Online Business',  ENG:'Online Business',  CHN:'网上销售',  RUS:''},
		{id:'Material Costs',  ENG:'Material Costs',  CHN:'成本',  RUS:''},
		{id:'Trade and Marketing Expenses',  ENG:'Trade and Marketing Expenses',  CHN:'广告投入和渠道支持',  RUS:''},
		{id:'General Expenses',  ENG:'General Expenses',  CHN:'经常性开支',  RUS:''},
		{id:'Amortisation',  ENG:'Amortisation',  CHN:'折旧和摊销费用',  RUS:''},
		{id:'Inventory Holding Cost',  ENG:'Inventory Holding Cost',  CHN:'库存持有成本',  RUS:''},
		{id:'Discontinued Goods Cost',  ENG:'Discontinued Goods Cost',  CHN:'停产产品成本',  RUS:''},
		{id:'Cost of Goods Sold',  ENG:'Cost of Goods Sold',  CHN:'售出产品成本',  RUS:''},
		{id:'Interest',  ENG:'Interest',  CHN:'财务费用（利息）',  RUS:''},
		{id:'Taxes',  ENG:'Taxes',  CHN:'所得税',  RUS:''},
		{id:'Exceptional Costs/Profits',  ENG:'Exceptional Costs/Profits',  CHN:'营业外支出/收入',  RUS:''},
		{id:'as % of sales',  ENG:'as % of sales',  CHN:'销售百分比',  RUS:''},
		{id:'B&M Business Profit Info',  ENG:'These two tables give the B&M business Profit & Loss statements for both categories by brand. When moving the cursor on the brand name, the Profit & Loss statement of that brand and all its variants will appear.',  CHN:'B&M Business Profit 介绍',  RUS:''},
		{id:'Online Business Profit Info',  ENG:'These two tables give the online business Profit & Loss statements for both categories by brand. When moving the cursor on the brand name, the Profit & Loss statement of that brand and all its variants will appear.',  CHN:'Online Business Profit 介绍',  RUS:''},
		{id:'Online Store',  ENG:'Online Store',  CHN:'网上商城',  RUS:''},
		{id:'Share of Trade Profit',  ENG:'Share of Trade Profit',  CHN:'贸易利润份额',  RUS:''},
		{id:'Share of Gross Sales',  ENG:'Share of Gross Sales',  CHN:'销售总额份额',  RUS:''},
		{id:'Share of Volume Sales',  ENG:'Share of Volume Sales',  CHN:'销量份额',  RUS:''},
		{id:'Gross Sales',  ENG:'Gross Sales',  CHN:'销售总额',  RUS:''},
		{id:'Trade Expenses',  ENG:'Trade Expenses',  CHN:'交易费用',  RUS:''},
		{id:'Trade Profit',  ENG:'Trade Profit',  CHN:'贸易利润',  RUS:''},
		{id:'Minimum Order Quantity',  ENG:'Minimum Order Quantity',  CHN:'最小订量',  RUS:''},
		{id:'Target Sales Volume',  ENG:'Target Sales Volume',  CHN:'目标销售额',  RUS:''},
		{id:'Bonus Rate',  ENG:'Bonus Rate',  CHN:'红利率',  RUS:''},
		{id:'Payment Terms',  ENG:'Payment Terms',  CHN:'付款条件',  RUS:''},
		{id:'days',  ENG:'days',  CHN:'天数',  RUS:''},
		{id:'Contract Honored',  ENG:'Contract Honored',  CHN:'合同授予',  RUS:''},
		{id:'Market Shares by Consumer Segment Info',  ENG:'This table shows the volume and value sales for all the HealthBeauties brands sold in the urban market. When moving the cursor on any brand name, the results for all its variants will pop up.',  CHN:'消费者细分市场份额介绍',  RUS:''},
		{id:'Market Shares by Shopper Segment Info',  ENG:'This table shows the volume and value sales for all the Elecssories brands sold in the rural market. When moving the cursor on any brand name, the results for all its variants will pop up.',  CHN:'购买者细分市场份额介绍',  RUS:''},
		{id:'Volume Share',  ENG:'Volume Share',  CHN:'销售份额',  RUS:''},
		{id:'Change',  ENG:'Change',  CHN:'变化',  RUS:''},
		{id:'Discontinued Goods Volume',  ENG:'Discontinued Goods Volume',  CHN:'停产产品销量',  RUS:''},
		{id:'Offline',  ENG:'OffLine',  CHN:'传统渠道',  RUS:''},
		{id:'Online',  ENG:'Online',  CHN:'网上商城',  RUS:''},
		{id:'Key Performance Indicators Info',  ENG:'Key Performance Indicators Info',  CHN:'关键性能指标介绍',  RUS:''},
		{id:'Effectiveness of Trade Spending',  ENG:'Effectiveness of Trade Spending',  CHN:'贸易支出的有效性',  RUS:''},
		{id:'Effectiveness of Marketing Spending',  ENG:'Effectiveness of Marketing Spending',  CHN:'营销支出的有效性',  RUS:''},
		{id:'Portfolio Strength',  ENG:'Portfolio Strength',  CHN:'投资力度',  RUS:''},
		{id:'Channel Strength',  ENG:'Channel Strength',  CHN:'渠道强度',  RUS:''},
		{id:'B&M Channel',  ENG:'B&M Channel',  CHN:'领头企业渠道',  RUS:''},
		{id:'Online Channel',  ENG:'Online Channel',  CHN:'在线渠道',  RUS:''},
		{id:'Share of Value Sales',  ENG:'Share of Value Sales',  CHN:'销售份额',  RUS:''},
		{id:'Share of Shoppers',  ENG:'Share of Shoppers',  CHN:'消费者份额',  RUS:''},
		{id:'Value Share in Category',  ENG:'Value Share in Category',  CHN:'类别份额',  RUS:''},
		{id:'Trade Support',  ENG:'Trade Support',  CHN:'渠道支持',  RUS:''},
		{id:'Advertising Online',  ENG:'Advertising Online',  CHN:'网络广告',  RUS:''},
		{id:'Advertising Offline',  ENG:'Advertising Offline',  CHN:'线下广告',  RUS:''},
		{id:'Share of Gross Profit/Loss in Category',  ENG:'Share of Gross Profit/Loss in Category',  CHN:'占类别总利润/损失份额',  RUS:''},
		{id:'Marketing Expenses',  ENG:'Marketing Expenses',  CHN:'营销费用',  RUS:''},
		{id:'Share of Marketing Expenses in Category',  ENG:'Share of Marketing Expenses in Category',  CHN:'营销费用份额',  RUS:''},
		{id:'Share of Operating Profit/Loss in Category',  ENG:'Share of Operating Profit/Loss in Category',  CHN:'营业利润/损失份额',  RUS:''},
		{id:'Share of Net Profit/Loss in Category',  ENG:'Share of Net Profit/Loss in Category',  CHN:'净收益/损失份额',  RUS:''},
		{id:'Value of Quantity Discounts',  ENG:'Value of Quantity Discounts',  CHN:'数量折扣的价值',  RUS:''},
		{id:'Value of Performance Bonus',  ENG:'Value of Performance Bonus',  CHN:'绩效奖金的价值',  RUS:''},
		{id:'Cost of Price Promotions',  ENG:'Cost of Price Promotions',  CHN:'价格促销成本',  RUS:''},
		{id:'Rural Profit & Loss Statement',  ENG:'Rural Profit & Loss Statement',  CHN:'城市盈利和亏损的声明',  RUS:''},
		{id:'Urban Profit & Loss Statement',  ENG:'Urban Profit & Loss Statement',  CHN:'乡村盈利和亏损的声明',  RUS:''},
		{id:'Rural Profit & Loss Statement Info',  ENG:'This table gives the Profit & Loss statement for both categories by brand level in the rural market. When moving the cursor on the brand name, the Profit & Loss statement of that brand and all its variants will appear.',  CHN:'城市盈利和亏损的声明介绍',  RUS:''},
		{id:'Urban Profit & Loss Statement Info',  ENG:'This table gives the Profit & Loss statement for both categories by brand level in the urban market. When moving the cursor on the brand name, the Profit & Loss statement of that brand and all its variants will appear.',  CHN:'乡村盈利和亏损的声明介绍',  RUS:''},
		{id:'Suppliers',  ENG:'Suppliers',  CHN:'生产商',  RUS:''},
		{id:'Supplier',  ENG:'Supplier',  CHN:'生产商',  RUS:''},
		{id:'Sales Per 1% of Shelf Space',  ENG:'Sales Per 1% of Shelf Space',  CHN:'销售货架空间百分比',  RUS:''},
		{id:'Gross Contribution',  ENG:'Gross Contribution',  CHN:'生产总值的贡献',  RUS:''},
		{id:'Gross Contribution Per 1% of Shelf Space',  ENG:'Gross Contribution Per 1% of Shelf Space',  CHN:'生产总值贡献的货架空间百分比',  RUS:''},
		{id:'As % of Value Sales',  ENG:'As % of Value Sales',  CHN:'销售价值百分比',  RUS:''},
		{id:'Share of Gross Contribution',  ENG:'Share of Gross Contribution',  CHN:'总值的份额贡献',  RUS:''},
		{id:'Terms of Payment',  ENG:'Terms of Payment',  CHN:'付款条件',  RUS:''},
		{id:'Value Share',  ENG:'Value Share',  CHN:'市场份额',  RUS:''},
		{id:'Ordered Volume',  ENG:'Ordered Volume',  CHN:'订货量',  RUS:''},
		{id:'Rotation Index',  ENG:'Rotation Index',  CHN:'旋转指针',  RUS:''},
		{id:'Profitability Index',  ENG:'Profitability Index',  CHN:'获利指数',  RUS:''},
		{id:'Stock Cover',  ENG:'Stock Cover',  CHN:'期末',  RUS:''},
		{id:'B&M Shoppers',  ENG:'B&M Shoppers',  CHN:'领头零售店',  RUS:''},
		{id:'All Shoppers',  ENG:'All Shoppers',  CHN:'所有零售店',  RUS:''},
		{id:'Consumer Segment Size',  ENG:'Consumer Segment Size',  CHN:'消费者市场规模',  RUS:''},
		{id:'Shopper Segment Size',  ENG:'Shopper Segment Size',  CHN:'购物者市场规模',  RUS:''},
		{id:'Segment Size',  ENG:'Segment Size',  CHN:'市场规模',  RUS:''},
		{id:'Category Volume s by Market',  ENG:'Category Volume s by Market',  CHN:'市场类别',  RUS:''},
		{id:'Internet Penetration Rates',  ENG:'Internet Penetration Rates',  CHN:'互联网普及率',  RUS:''},
		{id:'Awareness Info',  ENG:'The bar charts show the levels of awareness for each SKU in each market. The red section of the bar shows the drop in awareness over the last two periods; hence, the grey section is the level of awareness in the last period. The green section of the bar shows the increase in awareness over the last two periods; hence, the grey section plus the green section is the level of awareness in the last period. Moving the cursor on the bar segments gives the exact values.',  CHN:'awareness 介绍',  RUS:''},
		{id:'Brand Perceptions Info',  ENG:'These graphs show the perceptual positions of the SKUs by category and market. The positions are color-coded by supplier and retailer (for private label SKUs). Moving the cursor on any of the circles will identify the SKU and the exact perceptual coordinates of that SKU.',  CHN:'Brand Perceptions介绍',  RUS:''},
		{id:'Retailer Perceptions Info',  ENG:'These graphs show the perceptual positions of the retailers by market. Moving the cursor on the positions shows the exact coordinates of the position.',  CHN:'Retailer Perceptions介绍',  RUS:''},
		{id:'Sales by Consumer Segment',  ENG:'Sales by Consumer Segment',  CHN:'销售的消费市场',  RUS:''},
		{id:'Sales by Consumer Segment Info',  ENG:'Sales by Consumer Segment Info',  CHN:'销售的消费市场介绍',  RUS:''},
		{id:'Sales by Shopper Segment',  ENG:'Sales by Shopper Segment',  CHN:'销售顾客细分',  RUS:''},
		{id:'Sales by Shopper Segment Info',  ENG:'Sales by Shopper Segment Info',  CHN:'销售顾客细分介绍',  RUS:''},
		{id:'Brand Perceptions',  ENG:'Brand Perceptions',  CHN:'品牌认知',  RUS:''},
		{id:'Online Only',  ENG:'',  CHN:'',  RUS:''},
		{id:'B&M Retail Prices',  ENG:'B&M Retail Prices',  CHN:'零售价格',  RUS:''},
		{id:'B&M Retail Prices Info',  ENG:'B&M Retail Prices Info',  CHN:'零售价格介绍',  RUS:''},
		{id:'Net Retail Price',  ENG:'Net Retail Price',  CHN:'网络零售价格',  RUS:''},
		{id:'Length',  ENG:'Length',  CHN:'推广力度',  RUS:''},
		{id:'Depth',  ENG:'Depth',  CHN:'推广深度',  RUS:''},
		{id:'Negotiated',  ENG:'Negotiated',  CHN:'谈判',  RUS:''},
		{id:'Assets',  ENG:'Assets',  CHN:'资产',  RUS:''},
		{id:'Capacity',  ENG:'Capacity',  CHN:'能力',  RUS:''},
		{id:'min',  ENG:'min',  CHN:'最小',  RUS:''},
		{id:'max',  ENG:'max',  CHN:'最大',  RUS:''},
		{id:'Actual',  ENG:'Actual',  CHN:'目前',  RUS:''},
		{id:'Online Investments',  ENG:'Online Investments',  CHN:'网上投资',  RUS:''},
		{id:'Visibility',  ENG:'Visibility',  CHN:'可见性',  RUS:''},
		{id:'Other',  ENG:'Other',  CHN:'其他',  RUS:''},
		{id:'Production',  ENG:'Production',  CHN:'生产',  RUS:''},
		{id:'Capacity',  ENG:'Capacity',  CHN:'产能',  RUS:''},
		{id:'Utilization Rate',  ENG:'Utilization Rate',  CHN:'利用率',  RUS:''},
		{id:'Flexibility',  ENG:'Flexibility',  CHN:'灵活性',  RUS:''},
		{id:'Supplier 1 Online',  ENG:'Supplier 1 Online',  CHN:'生产商1在线',  RUS:''},
		{id:'Supplier 2 Online',  ENG:'Supplier 2 Online',  CHN:'生产商2在线',  RUS:''},
		{id:'Supplier 3 Online',  ENG:'Supplier 3 Online',  CHN:'生产商3在线',  RUS:''},
		{id:'Shelf Space Allocation',  ENG:'Shelf Space Allocation',  CHN:'货架空间分配',  RUS:''},
		{id:'Local',  ENG:'Local',  CHN:'当地',  RUS:''},
		{id:'Consumer Segment Size Info',  ENG:'These graphs show the historical values and the two-period ahead forecasts of the consumer segment sizes by category and market. Moving the cursor on the forecasted areas will reveal the optimistic and pessimistic forecast values for each of the next two periods.',  CHN:'Consumer Segment Size介绍',  RUS:''},
		{id:'Shopper Segment Size Info',  ENG:'These graphs show the historical values and the two-period ahead forecasts of the shopper segment sizes by category and market. Moving the cursor on the forecasted areas will reveal the optimistic and pessimistic forecast values for each of the next two periods.',  CHN:'Shopper segment Size介绍',  RUS:''},
		{id:'Two-Period Ahead Forecasts',  ENG:'Two-Period Ahead Forecasts',  CHN:'两期提前预测',  RUS:''},
		{id:'Category Volumes by Market Info',  ENG:'This graph shows the historical values and the two-period ahead forecasts of category volumes by market. Moving the cursor on the forecasted areas will reveal the optimistic and pessimistic forecast values for each of the next two periods.',  CHN:'Category Volumes by Market介绍',  RUS:''},
		{id:'Internet Penetration Rates Info',  ENG:'These graphs show the historical values and the two-period ahead forecasts of the internet penetration rates by market. Moving the cursor on the forecasted areas will reveal the optimistic and pessimistic forecast values for each of the next two periods.',  CHN:'Internet Penetration Rates介绍',  RUS:''},
		{id:'Penetration Level',  ENG:'Penetration Level',  CHN:'渗透水平',  RUS:''},
		{id:'Price Appeal',  ENG:'Price Appeal',  CHN:'价格的吸引力',  RUS:''},
		{id:'Easy of Use',  ENG:'Easy of Use',  CHN:'易用性',  RUS:''},
		{id:'Category Volumes by Market',  ENG:'Category Volumes by Market',  CHN:'市场类别',  RUS:''},
		{id:'Product Portfolio Management Info',  ENG:'<p>This decision form allows supplier to manage their product portfolio. More specifically, supplier can decide to discontinue specific SKUs, add new brands/variants, add new variants under existing brands and modify the specifications of variants in supplier’s Elecssories portfolio. The product portfolio from the last period appears by default.</p>',  CHN:'',  RUS:''},
		{id:'Product Portfolio Management',  ENG:'Product Portfolio Management',  CHN:'产品组合管理',  RUS:''},
		{id:'B&M List Prices',  ENG:'B&M List Prices',  CHN:'价格列表',  RUS:''},
		{id:'B&M List Prices Pop Info',  ENG:'B&M List Prices Info',  CHN:'B&M List Prices介绍',  RUS:''},
		{id:'B&M List Prices Info',  ENG:'This decision form allows supplier to decide the B&M List prices for the SKUs in supplier’s Elecssories portfolio. The list prices from previous period are shown by default and the supplier can change it. All the changes are highlighted in red. If the decisions are not validated within the deadline, those from the previous period are entered with the old list prices adjusted for inflation.',  CHN:'介绍',  RUS:''},
		{id:'Negotiation Agreements',  ENG:'Negotiation Agreements',  CHN:'谈判协议',  RUS:''},
		{id:'Production Volumes',  ENG:'Production Volumes',  CHN:'产量',  RUS:''},
		{id:'General Report',  ENG:'General Report',  CHN:'综合报告',  RUS:''},
		{id:'Market Report',  ENG:'Market Report',  CHN:'市场报告',  RUS:''},
		{id:'Confidential Report',  ENG:'Confidential Report',  CHN:'保密报告',  RUS:''},
		{id:'Facilitator Confidential Report',  ENG:'Facilitator Confidential Report',  CHN:'讲师保密报告',  RUS:''},
		{id:'Facilitator Confidential Report Info',  ENG:'Facilitator Confidential Report Info',  CHN:'讲师保密报告介绍',  RUS:''},
		{id:'General Marketing',  ENG:'General Marketing',  CHN:'综合市场',  RUS:''},
		{id:'General Marketing Info',  ENG:'This decision form allows supplier to decide the General Marketing spending for each SKU in the supplier’s Elecssories portfolio. The values from previous period are shown by default and the supplier can change it. All the changes are highlighted in red. If the decisions are not validated within the deadline, those from the previous period are submitted.',  CHN:'综合市场介绍',  RUS:''},
		{id:'Online Store Management',  ENG:'Online Store Management',  CHN:'在线销售',  RUS:''},
		{id:'Store Management',  ENG:'Store Management',  CHN:'销售',  RUS:''},
		{id:'Online Store Management Info',  ENG:'This decision form allows supplier to decide the online store spending for each SKU in the supplier’s Elecssories portfolio. The values from previous period are shown by default and the supplier can change it. All the changes are highlighted in red. If the decisions are not validated within the deadline, those from the previous period are submitted.',  CHN:'在线销售介绍',  RUS:''},
		{id:'Asset Investments',  ENG:'Asset Investments',  CHN:'资产投资',  RUS:''},
		{id:'Asset Investments Info',  ENG:'This decision form allows supplier to decide the investments in assets at category level. When the cursor hover over these items, a pop-up showing the feasible range of values appears. The values from previous period are shown by default and the supplier can change it. All the changes are highlighted in red. If the decisions are not validated by the deadline, those from the previous period are submitted.',  CHN:'Asset Investments介绍',  RUS:''},
		{id:'Market Research Orders',  ENG:'Market Research Orders',  CHN:'市场研究订单',  RUS:''},
		{id:'Market Research Orders Info',  ENG:'This decision form allows supplier to order market reports for the next period. By hovering the cursor on each study title, an a pop-up will appear which explaining the contents of that study',  CHN:'市场研究订单介绍',  RUS:''},
		{id:'Order Volumes',  ENG:'Order Volumes',  CHN:'订单量',  RUS:''},
		{id:'Prices',  ENG:'Prices',  CHN:'价格',  RUS:''},
		{id:'Technology',  ENG:'Technology',  CHN:'技术',  RUS:''},
		{id:'Design',  ENG:'Design',  CHN:'设计',  RUS:''},
		{id:'Marketing',  ENG:'Marketing',  CHN:'市场',  RUS:''},
		{id:'Marketing Info',  ENG:'This decision form allows retailers to decide the spending for advertising and the In-Store service levels. The values from previous period are shown by default and the retailer can change it. All the changes are highlighted in red. If the decisions are not validated within the deadline, those from the previous period are submitted. The range of values for In-Store levels is displayed when cursor hovers over the “In-Store Service Level” label.',  CHN:'市场介绍',  RUS:''},
		{id:'Private Label Portfolio Management',  ENG:'Private Label Portfolio Management',  CHN:'自有品牌组合管理',  RUS:''},
		{id:'Private Label Portfolio Management Info',  ENG:'This decision form allows retailers to manage their private label product portfolio. More specifically, retailer can decide to discontinue specific SKUs, add new brands/variants, add new variants under existing brands and modify the specifications of variants in retailer’s private label portfolio. The product portfolio from the last period appears by default.',  CHN:'自有品牌组合管理介绍',  RUS:''},
		{id:'Buy',  ENG:'Buy',  CHN:'购买',  RUS:''},
		{id:'Cost',  ENG:'Cost',  CHN:'售价',  RUS:''},
		{id:'Report',  ENG:'Report',  CHN:'报告',  RUS:''},
		{id:'SubmitOrder',  ENG:'SubmitOrder',  CHN:'提交订单',  RUS:''},
		{id:'Total Budget',  ENG:'Total Budget',  CHN:'总预算',  RUS:''},
		{id:'Available Period Capacity',  ENG:'Available Period Capacity',  CHN:'可用时间能力',  RUS:''},
		{id:'Time Left',  ENG:'Time Left',  CHN:'剩余时间',  RUS:''},
		{id:'mins',  ENG:'mins',  CHN:'分钟',  RUS:''},
		{id:'Decision Info',  ENG:'Decision Info',  CHN:'决策介绍',  RUS:''},
		{id:'Shelf Space Left',  ENG:'Shelf Space Left',  CHN:'货架剩余空间',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},

		{id:'',  ENG:'',  CHN:'',  RUS:''}
	]
}

