var getLabelBase = function(){
	return [
		/*retail report new label */
		{id:'- Advertising Total ($mln)',  ENG:'- Advertising Total ($mln)',  CHN:'-广告总投入(￥百万元)',  RUS:''},
		{id:'-National Off-line ($mln)',  ENG:'-National Off-line ($mln)',  CHN:'-全国性传统广告(￥百万元)',  RUS:''},
		{id:'-National On-line ($mln)',  ENG:'-National On-line ($mln)',  CHN:'-全国性网络广告(￥百万元)',  RUS:''},
		{id:'-Local Tier T ($mln)',  ENG:'-Local Tier T ($mln)',  CHN:'-地域广告投入(￥百万元)',  RUS:''},
		{id:'-Stores Operating Costs ($mln)',  ENG:'-Stores Operating Costs ($mln)',  CHN:'-卖场运营费用(￥百万元)',  RUS:''},
		{id:'-Amortisation ($mln)',  ENG:'-Amortisation ($mln)',  CHN:'-折旧费用(￥百万元)',  RUS:''},
		{id:'Manufacturer 1',  ENG:'Manufacturer 1',  CHN:'生产商 1',  RUS:''},	
		{id:'Manufacturer 2',  ENG:'Manufacturer 2',  CHN:'生产商 2',  RUS:''},	
		{id:'Manufacturer 3',  ENG:'Manufacturer 3',  CHN:'生产商 3',  RUS:''},	
		{id:'Private label',  ENG:'Private label',  CHN:'自有品牌',  RUS:''},	
		{id:'',  ENG:'',  CHN:'',  RUS:''},

		/*line chart page */
		{id:'e-Mall',  ENG:'E-Mall',  CHN:'网上商城',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
        {id:'Retail Market Sales (Value)',  ENG:'Retail Market Sales (Value)',  CHN:'零售市场销售额',  RUS:''},        
        {id:'Retail Market Share (Value)',  ENG:'Retail Market Share (Value)',  CHN:'零售市场份额(按销售额计)',  RUS:''},        
        {id:'Retail Market Sales (Volume)',  ENG:'Retail Market Sales (Volume)',  CHN:'零售市场销量',  RUS:''},        
        {id:'Retail Market Share (Volume)',  ENG:'Retail Market Share (Volume)',  CHN:'零售市场份额(按销量计)',  RUS:''},        
		{id:'Wholesale Sales Value',  ENG:'Wholesale Sales Value',  CHN:'经销商市场销售额',  RUS:''},        
		{id:'Wholesale Market Share (Value)',  ENG:'Wholesale Market Share (Value)',  CHN:'经销商市场份额(按销售额计)',  RUS:''},        
		{id:'Wholesale Sales Volume',  ENG:'Wholesale Sales Volume',  CHN:'经销商市场销量',  RUS:''},        
		{id:'Wholesale Market Share (Volume)',  ENG:'Wholesale Market Share (Volume)',  CHN:'经销商市场份额(按销量计)',  RUS:''},        
		{id:'Net Sales Value',  ENG:'Net Sales Value',  CHN:'净销售额',  RUS:''},	
		{id:'Expenses',  ENG:'Expenses',  CHN:'费用',  RUS:''},
		{id:'Expenses Info',  ENG:'Expenses Info',  CHN:'费用信息',  RUS:''},
		{id:'Wholesales Market Results',  ENG:'Wholesales Market Results',  CHN:'经销商市场结果',  RUS:''},
		{id:'Wholesales Market Results Info',  ENG:'Wholesales Market Results Info',  CHN:'经销商市场信息',  RUS:''},
		{id:'Retail Market Results',  ENG:'Retail Market Results',  CHN:'零售市场结果',  RUS:''},
		{id:'Retail Market Results Info',  ENG:'Retail Market Results Info',  CHN:'零售市场结果信息',  RUS:''},
		{id:'Gross Profit',  ENG:'Gross Profit',  CHN:'毛利润',  RUS:''},	
		{id:'Operating Profit',  ENG:'Operating Profit',  CHN:'运营利润',  RUS:''},	
		{id:'Net Profit',  ENG:'Net Profit',  CHN:'净利润',  RUS:''},	
		{id:'Gross Profit Margin',  ENG:'Gross Profit Margin',  CHN:'毛利率',  RUS:''},	
		{id:'Operating Profit Margin',  ENG:'Operating Profit Margin',  CHN:'营运利润率',  RUS:''},	
		{id:'Net Profit Margin',  ENG:'Net Profit Margin',  CHN:'净利润率',  RUS:''},	
		{id:'Total Material Cost',  ENG:'Total Material Cost',  CHN:'总材料成本',  RUS:''},	
		{id:'Total Advertising',  ENG:'Total Advertising',  CHN:'广告总投入',  RUS:''},	
		{id:'Total Trade (Producer) Support',  ENG:'Total Trade (Producer) Support',  CHN:'总通路(生产商)投入费用',  RUS:''},	
		{id:'Total General Expenses',  ENG:'Total General Expenses',  CHN:'一般开支总额',  RUS:''},
		{id:'Profitability Absolute RMB',  ENG:'Profitability Absolute RMB',  CHN:'利润额',  RUS:''},
		{id:'Profitability Absolute RMB Info',  ENG:'Profitability Absolute RMB Info',  CHN:'利润额信息',  RUS:''},
		{id:'Profitability as percentage of Sales',  ENG:'Profitability as percentage of Sales',  CHN:'利润占销售额的比例',  RUS:''},
		{id:'Profitability as percentage of Sales Info',  ENG:'Profitability as percentage of Sales Info',  CHN:'利润率信息',  RUS:''},

		{id:'Team',  ENG:'Team',  CHN:'团队',  RUS:''},	
		{id:'Producer 1',  ENG:'Producer 1',  CHN:'生厂商 1',  RUS:''},	
		{id:'Producer 2',  ENG:'Producer 2',  CHN:'生厂商 2',  RUS:''},	
		{id:'Producer 3',  ENG:'Producer 3',  CHN:'生厂商 3',  RUS:''},	
		{id:'Producer 4',  ENG:'Producer 4',  CHN:'生厂商 4',  RUS:''},	
		{id:'Chart',  ENG:'Chart',  CHN:'图表',  RUS:''},
		{id:'Chart Info',  ENG:'Charts show you visually where your business stands in comparison to your competitors.',  CHN:'图表帮助你一目了然地比较自己和竞争对手的情况',  RUS:''},
		{id:'Chart popInfo',  ENG:'You may look at other industry (retail or manufacturing) for benchmarking if you change role selector. You may change details level using category and market selectors. To see numbers behind the trends use your mouse over the lines.',  CHN:'可以选择 \"品类\" 或 \"市场\"，从不同层级查看信息. 把鼠标放在趋势线上, 可以看到相应的数字。',  RUS:''},
		{id:'Total',  ENG:'Total',  CHN:'总计',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},

		/*Login page*/
		{id:'eTales Info',  ENG:'Best-in-class professional development tool among the world’s most respected companies and leading business schools',  CHN:'首次呈现和探索零售商、供应商、电商和消费者在社交媒体盛行时代的生存和胜出之道。',  RUS:''},
		{id:'Get started',  ENG:'Get started',  CHN:'现在开始',  RUS:''},
		{id:'Admin entrance',  ENG:'Admin entrance',  CHN:'管理员入口',  RUS:''},
		{id:'Currently',  ENG:'Currently',  CHN:'当前版本',  RUS:''},
		{id:'User Login',  ENG:'User Login',  CHN:'用户登陆',  RUS:''},	
		{id:'Role',  ENG:'Role',  CHN:'角色',  RUS:''},	
		{id:'Password',  ENG:'Password',  CHN:'密码',  RUS:''},	
		{id:'Seminar Code',  ENG:'Seminar Code',  CHN:'课程ID',  RUS:''},	
		{id:'Login',  ENG:'Login',  CHN:'登陆',  RUS:''},	
		{id:'Admin Login',  ENG:'Admin Login',  CHN:'管理员登陆',  RUS:''},	
		{id:'Facilitator',  ENG:'Facilitator',  CHN:'讲师',  RUS:''},	
		{id:'Guest',  ENG:'Guest',  CHN:'',  RUS:''},	

		/*Perception map page*/
		{id:'Ease of use',  ENG:'Ease of use',  CHN:'易用性',  RUS:''},	
		{id:'Quality',  ENG:'Quality',  CHN:'质量',  RUS:''},	
		{id:'Price',  ENG:'Price',  CHN:'价格',  RUS:''},	
		{id:'Market Share',  ENG:'Market Share',  CHN:'市场份额',  RUS:''},	
		{id:'Visibility Share',  ENG:'Visibility Share',  CHN:'可见度份额',  RUS:''},	
		{id:'Company summary',  ENG:'Company summary',  CHN:'公司信息汇总',  RUS:''},
		{id:'Company summary Info',  ENG:'',  CHN:'公司信息汇总',  RUS:''},
		{id:'Perception Map',  ENG:'Perception Map',  CHN:'感知图',  RUS:''},
		{id:'Perception Map Info',  ENG:'A type of chart widely used in marketing to graphically show how consumers perceive brands. In some cases brand positioning is compared with consumer segments\' ideal points. In eTales however vector positioning model is used. It means that having no ideal point as such, all segments will prefer brands with higher (or lower) perception if this perception dimension is of relative importance to consumers of this segment.',  CHN:'市场营销中广泛使用的一种图表, 显示消费者如何感知你的品牌。 在有些情况下， 会把品牌定位和消费者细分的理想感知点进行对比。 但是在\“零售风暴\”中， 没有所谓的\“理想感知点\”， 所有细分市场在相关的感知维度上希望更高或更低的感知。',  RUS:''},		
		{id:'Perception Map popInfo',  ENG:'Position your mouse over brand name to see change dinamics and additional market information.',  CHN:'把鼠标放在品牌名称上， 你会看到该品牌的变化和额外的市场信息。 ',  RUS:''},		
		{id:'Check All',  ENG:'Check All',  CHN:'选择全部',  RUS:''},
		{id:'Un-Check All',  ENG:'Un-Check All',  CHN:'取消全部',  RUS:''},
		{id:'Generate Map',  ENG:'Generate Map',  CHN:'生成图表',  RUS:''},
		{id:'Period',  ENG:'Period',  CHN:'阶段',  RUS:''},
		{id:'Reason',  ENG:"For some reason,something in this page can't translate immediately",  CHN:'For some reason,something in this page cannot translate immediately。',  RUS:''},
		{id:'Perceptions Map',  ENG:'Perceptions Map',  CHN:'感知图',  RUS:''},
		{id:'Ease of Use perception',  ENG:'Ease of Use perception',  CHN:'易用性感知',  RUS:''},
		{id:'Quality perception',  ENG:'Quality perception',  CHN:'质量感知',  RUS:''},
		{id:'Performance perception',  ENG:'Performance perception',  CHN:'效果感知',  RUS:''},
		{id:'Gentleness perception',  ENG:'Gentleness perception',  CHN:'亲柔度感知',  RUS:''},
		{id:'PricePerception',  ENG:'PricePerception',  CHN:'价格感知',  RUS:''},
		{id:'Price Sensitive',  ENG:'Price Sensitive',  CHN:'价格敏感型',  RUS:''},
		{id:'Value for Money',  ENG:'Value for Money',  CHN:'物有所值型',  RUS:''},
		{id:'Health Conscious',  ENG:'Health Conscious',  CHN:'注重健康型',  RUS:''},
		{id:'Impatient',  ENG:'Impatient',  CHN:'急躁型',  RUS:''},
		{id:'Retailer 1',  ENG:'Retailer 1',  CHN:'零售商1',  RUS:''},
		{id:'Retailer 2',  ENG:'Retailer 2',  CHN:'零售商2',  RUS:''},
		{id:'eMall',  ENG:'eMall',  CHN:'网上商城',  RUS:''},
		{id:'Producer',  ENG:'Producer ',  CHN:'生产商 ',  RUS:''},
		{id:'Retailer',  ENG:'Retailer ',  CHN:'零售商 ',  RUS:''},
		{id:'switchLanguage',  ENG:'Switch Language',  CHN:'切换语言',  RUS:''},

		/*navbar*/
		{id:'Participant manual',  ENG:'Participant manual',  CHN:'学员手册',  RUS:''},
		{id:'My company',  ENG:'My company',  CHN:'我的公司',  RUS:''},
		{id:'Charts',  ENG:'Charts',  CHN:'图表',  RUS:''},
		{id:'Make Decision',  ENG:'Make Decision',  CHN:'制订决策',  RUS:''},
		{id:'Get result of lastest period',  ENG:'Get result of lastest perio',  CHN:'更新决策',  RUS:''},
		{id:'Log out',  ENG:'Log out',  CHN:'退出',  RUS:''},

		/*fin report*/
		{id:'Reports',  ENG:'Reports',  CHN:'报告',  RUS:''},
		{id:'Reports Info',  ENG:'Here you will find financial statements and other reports giving operating results of your company and its departments.',  CHN:'这里你可以查看公司各方面的财务信息。',  RUS:''},
		{id:'Reports popInfo',  ENG:' Looking at the reports, try to change perspective or detail level from global (company) or category to brand or even variant (SKU).',  CHN:'可以从整个市场(公司）、分市场、分品类、分品牌甚至单品查看信息。',  RUS:''},
		{id:'Profit and Loss Statement',  ENG:'Profit and Loss Statement',  CHN:'损益表',  RUS:''},
		{id:'Profit and Loss Statement Info',  ENG:'Profit and Loss Statement Info',  CHN:'损益表信息',  RUS:''},
		{id:'Prices per unit',  ENG:'Prices per unit',  CHN:'单价',  RUS:''},
		{id:'Prices per unit Info',  ENG:'Prices per unit Info',  CHN:'单价信息',  RUS:''},
		{id:'Volumes Report',  ENG:'Volumes Report',  CHN:'销量报告',  RUS:''},
		{id:'Volumes Report Info',  ENG:'Volumes Report Info',  CHN:'销量报告信息',  RUS:''},
		{id:'Profitability by Channel',  ENG:'Profitability by Channel',  CHN:'渠道盈利分析',  RUS:''},
		{id:'Profitability by Channel Info',  ENG:'Profitability by Channel Info',  CHN:'渠道盈利分析信息',  RUS:''},
		{id:'Performance Indices',  ENG:'Performance Indices',  CHN:'绩效指标',  RUS:''},
		{id:'Performance Indices Info',  ENG:'Performance Indices Info',  CHN:'绩效指标信息',  RUS:''},
		{id:'Profitability by Supplier',  ENG:'Profitability by Supplier',  CHN:'供应商盈利',  RUS:''},
		{id:'Profitability by Supplier Info',  ENG:'Profitability by Supplier Info',  CHN:'供应商盈利信息',  RUS:''},
		{id:'Detail',  ENG:'Detail',  CHN:'细节信息',  RUS:''},
		{id:'Global',  ENG:'Global',  CHN:'整个市场',  RUS:''},
		{id:'Traditional Trade',  ENG:'Traditional Trade',  CHN:'传统渠道',  RUS:''},
		{id:'E-Mall',  ENG:'E-Mall',  CHN:'网上商城',  RUS:''},
		{id:'Item',  ENG:'Item',  CHN:'条款',  RUS:''},

		/*Producer Reports*/
		{id:'Sales value($mln)',  ENG:'Sales value($mln)',  CHN:'销售额(￥百万元)',  RUS:''},
		{id:'(%) change versus previous period',  ENG:'(%) change versus previous period',  CHN:'(%)相对于上阶段的改变',  RUS:''},
		{id:'Share In Category Total Sales Value (%)',  ENG:'Share In Category Total Sales Value (%)',  CHN:'占品类总销售额比例(%)',  RUS:''},
		{id:'Total material costs($mln)',  ENG:'Total material costs($mln)',  CHN:'总成本(￥百万元)',  RUS:''},
		{id:'Cost of Goods Sold ($mln)',  ENG:'Cost of Goods Sold ($mln)',  CHN:'售出产品成本(￥百万元)',  RUS:''},
		{id:'Discontinued Goods Cost($mln)',  ENG:'Discontinued Goods Cost($mln)',  CHN:'停产产品成本（￥百万元)',  RUS:''},
		{id:'Inventory Holding Cost($mln)',  ENG:'Inventory Holding Cost($mln)',  CHN:'库存持有成本（￥百万元)',  RUS:''},
		{id:'Gross Profit($mln)',  ENG:'Gross Profit($mln)',  CHN:'毛利额(￥百万元)',  RUS:''},
		{id:'Gross Profit margin (%)',  ENG:'Gross Profit margin (%)',  CHN:'毛利率(%)',  RUS:''},
		{id:'Share in Category Gross Profit/Losses (%)',  ENG:'Share in Category Gross Profit/Losses (%)',  CHN:'占品类毛利/损失的比例(%)',  RUS:''},		
		{id:'Advertising Total ($mln)',  ENG:'Advertising Total ($mln)',  CHN:'广告总投入(￥百万元)',  RUS:''},
		{id:'National Off-line ($mln)',  ENG:'National Off-line ($mln)',  CHN:'全国性传统广告(￥百万元)',  RUS:''},
		{id:'National On-line ($mln)',  ENG:'National On-line ($mln)',  CHN:'全国性网络广告(￥百万元)',  RUS:''},
		{id:'Local Tier 1 ($mln)',  ENG:'Local Tier 1 ($mln)',  CHN:'城市本地广告(￥百万元)',  RUS:''},
		{id:'Local Tier 2 ($mln)',  ENG:'Local Tier 2 ($mln)',  CHN:'农村本地广告(￥百万元)',  RUS:''},
		{id:'Total Trade Support ($mln)',  ENG:'Total Trade Support ($mln)',  CHN:'总的通路支持(￥百万元)',  RUS:''},
		{id:'Price Promotions ($mln)',  ENG:'Price Promotions ($mln)',  CHN:'价格促销(￥百万元)',  RUS:''},
		{id:'Volume Discounts ($mln)',  ENG:'Volume Discounts ($mln)',  CHN:'数量折扣(￥百万元)',  RUS:''},
		{id:'Performance Bonus ($mln)',  ENG:'Performance Bonus ($mln)',  CHN:'销售达标激励(￥百万元)',  RUS:''},
		{id:'Other Support ($mln)',  ENG:'Other Support ($mln)',  CHN:'其他支持(￥百万元)',  RUS:''},
		{id:'Total Trade and Marketing Expenses($mln)',  ENG:'Total Trade and Marketing Expenses($mln)',  CHN:'总的营销和通路费用（￥百万元)',  RUS:''},
		{id:'Trade and Marketing Expenses as a (%) of Sales',  ENG:'Trade and Marketing Expenses as a (%) of Sales',  CHN:'总营销通路费用占销售额的比例(%)',  RUS:''},
		{id:'General Expenses($mln)',  ENG:'General Expenses($mln)',  CHN:'一般性开支(￥百万元)',  RUS:''},
		{id:'Amortisation ($mln)',  ENG:'Amortisation ($mln)',  CHN:'折旧费用(￥百万元)',  RUS:''},
		{id:'Operating Profit ($mln)',  ENG:'Operating Profit ($mln)',  CHN:'营运利润(￥百万元)',  RUS:''},
		{id:'Operating Profit margin (%)',  ENG:'Operating Profit margin (%)',  CHN:'营运利润率(%)',  RUS:''},
		{id:'Share in Category Operating Profit/Losses (%)',  ENG:'Share in Category Operating Profit/Losses (%)',  CHN:'占品类运营运利润/损失的比例(%)',  RUS:''},
		{id:'Interests($mln)',  ENG:'Interests($mln)',  CHN:'利息(￥百万元)',  RUS:''},
		{id:'Taxes($mln)',  ENG:'Taxes($mln)',  CHN:'税(￥百万元)',  RUS:''},
		{id:'Exceptional Costs/Profits($mln)',  ENG:'Exceptional Costs/Profits($mln)',  CHN:'额外成本/利润(￥百万元)',  RUS:''},
		{id:'Net Profit($mln)',  ENG:'Net Profit($mln)',  CHN:'净利润(￥百万元)',  RUS:''},
		{id:'Net Profit margin (%)',  ENG:'Net Profit margin (%)',  CHN:'净利润率(%)',  RUS:''},
		{id:'Share of Trade and Marketing Expenses in Category Total (%)',  ENG:'Share of Trade and Marketing Expenses in Category Total (%)',  CHN:'占品类总通路和市场费用的比例(%)',  RUS:''},	
		{id:'Share In Category Net Profit/Losses (%)',  ENG:'Share In Category Net Profit/Losses (%)',  CHN:'占品类净利润/损失的比例(%)',  RUS:''},
		{id:'Production Cost',  ENG:'Production Cost',  CHN:'生产成本',  RUS:''},
		{id:'Current List price BM',  ENG:'Current List price BM',  CHN:'当前阶段对实体零售店的报价',  RUS:''},
		{id:'Next List Price BM',  ENG:'Next List Price BM',  CHN:'下阶段对实体零售店的报价',  RUS:''},
		{id:'Current List Price eMall',  ENG:'Current List Price eMall',  CHN:'当前网店的零售价',  RUS:''},
		{id:'Next List Price eMall',  ENG:'Next List Price eMall',  CHN:'下阶段网店的零售价',  RUS:''},
		{id:'Production',  ENG:'Production',  CHN:'本阶段产量',  RUS:''},
		{id:'Sales',  ENG:'Sales',  CHN:'本阶段销量',  RUS:''},
		{id:'Discontinued Goods',  ENG:'Discontinued Goods',  CHN:'停产产品',  RUS:''},
		{id:'Order volume (mln. Units)',  ENG:'Order volume (mln. Units)',  CHN:'订货量(百万件)',  RUS:''},
		{id:'Sales volume (mln. Units)',  ENG:'Sales volume (mln. Units)',  CHN:'销售量(百万件)',  RUS:''},
		{id:'Share in sales volume (%)',  ENG:'Share in sales volume (%)',  CHN:'占销量的比例(%)',  RUS:''},
		{id:'Sales value (RMB 000)',  ENG:'Sales value (RMB 000)',  CHN:'销售额(￥百万元)',  RUS:''},
		{id:'Share in gross sales value (%)',  ENG:'Share in gross sales value (%)',  CHN:'占总销售额的比例(%)',  RUS:''},
		{id:'Cost of goods sold (RMB 000)',  ENG:'Cost of goods sold (RMB 000)',  CHN:'售出产品成本(￥百万元)',  RUS:''},
		{id:'Quantity discounts costs (RMB 000)',  ENG:'Quantity discounts costs (RMB 000)',  CHN:'数量折扣成本(￥百万元)',  RUS:''},
		{id:'(delay of payment) (RMB 000)',  ENG:'(delay of payment) (RMB 000)',  CHN:'延期付款(￥百万元)',  RUS:''},
		{id:'Other compensation (RMB 000)',  ENG:'Other compensation (RMB 000)',  CHN:'其他支持(￥百万元)',  RUS:''},
		{id:'Total trade support (RMB 000)',  ENG:'Total trade support (RMB 000)',  CHN:'总的通路支持(￥百万元)',  RUS:''},
		{id:'Gross profit after PUSH (RMB 000)',  ENG:'Gross profit after PUSH (RMB 000)',  CHN:'扣除通路费用后的毛利额(￥百万元)',  RUS:''},
		{id:'Share in gross profit (%)',  ENG:'Share in gross profit (%)',  CHN:'占毛利额比例(%)',  RUS:''},
		{id:'Performance bonus cost (RMB 000)',  ENG:'Performance bonus cost (RMB 000)',  CHN:'业绩奖励成本(￥百万元)',  RUS:''},
		{id:'In store activities fees (RMB 000)',  ENG:'In store activities fees (RMB 000)',  CHN:'店内营销活动费用(￥百万元)',  RUS:''},
		{id:'Inventory holding cost compensation (RMB 000)',  ENG:'Inventory holding cost compensation (RMB 000)',  CHN:'库存持有成本补偿(￥百万元)',  RUS:''},
		{id:'Promotional support (RMB 000)',  ENG:'Promotional support (RMB 000)',  CHN:'促销支持(￥百万元)',  RUS:''},
		{id:'Financial Cost (delay of payment) (RMB 000)',  ENG:'Financial Cost (delay of payment) (RMB 000)',  CHN:'财务成本(延期支付,￥百万元)',  RUS:''},
		{id:'Company total',  ENG:'Company total',  CHN:'公司总计',  RUS:''},	
		
		/*Retailer Reports */
		{id:'Sales value ($mln)',  ENG:'Sales value ($mln)',  CHN:'销售额(￥百万元)',  RUS:''},
		{id:'- Cost of Price Promotions ($mln)',  ENG:'- Cost of Price Promotions ($mln)',  CHN:'-价格促销成本(￥百万元)',  RUS:''},
		{id:'Promotional Support from Supplier ($mln)',  ENG:'Promotional Support from Supplier ($mln)',  CHN:'生产商提供的促销支持(￥百万元)',  RUS:''},
		{id:'Other Compensation ($mln)',  ENG:'Other Compensation ($mln)',  CHN:'其他补偿(￥百万元)',  RUS:''},
		{id:'Net Sales Value ($mln)',  ENG:'Net Sales Value ($mln)',  CHN:'净销售额(￥百万元)',  RUS:''},
		{id:'-Total material costs($mln)',  ENG:'-Total material costs($mln)',  CHN:'-总材料成本(￥百万元)',  RUS:''},
		{id:'-Cost of Goods Sold ($mln)',  ENG:'-Cost of Goods Sold ($mln)',  CHN:'-售出商品成本(￥百万元)',  RUS:''},
		{id:'Value of Quantity Discounts ($mln)',  ENG:'Value of Quantity Discounts ($mln)',  CHN:'数量折扣(￥百万元)',  RUS:''},
		{id:'Value of Performance Bonus ($mln)',  ENG:'Value of Performance Bonus ($mln)',  CHN:'业绩奖励(￥百万元)',  RUS:''},
		{id:'-Discontinued Goods Cost($mln)',  ENG:'-Discontinued Goods Cost($mln)',  CHN:'-停售商品成本(￥百万元)',  RUS:''},
		{id:'-Inventory Holding Cost($mln)',  ENG:'-Inventory Holding Cost($mln)',  CHN:'-库存持有成本(￥百万元)',  RUS:''},
		{id:'-General Expenses($mln)',  ENG:'-General Expenses($mln)',  CHN:'－一般性开支(￥百万元)',  RUS:''},
		{id:'-Taxes($mln)',  ENG:'-Taxes($mln)',  CHN:'－税(￥百万元)',  RUS:''},
		{id:'Value Rotation Index  Sales value per 1% of shelf space',  ENG:'Value Rotation Index Sales value per 1% of shelf space',  CHN:'每1%货架的销售额',  RUS:''},
		{id:'Volume Rotation Index  Sales volume per 1% of shelf space',  ENG:'Volume Rotation Index Sales volume per 1% of shelf space',  CHN:'每1%货架的销量',  RUS:''},
		{id:'Profitability Index  Gross Profit per 1% of shelf space',  ENG:'Profitability Index Gross Profit per 1% of shelf space',  CHN:'每1%货架的毛利额',  RUS:''},
		{id:'Stock Cover  Closing Inventory Volume / weekly Sales volume',  ENG:'Stock Cover Closing Inventory Volume / weekly Sales volume',  CHN:'期末库存数量/每周销量',  RUS:''},
		{id:'Market Price',  ENG:'Market Price',  CHN:'零售价',  RUS:''},
		{id:'Purchase Price',  ENG:'Purchase Price',  CHN:'采购价',  RUS:''},
		{id:'Effective Net Purchase Price',  ENG:'Effective Net Purchase Price',  CHN:'实际净采购价',  RUS:''},
		{id:'Supplier Current List price',  ENG:'Supplier Current List price',  CHN:'生产商当前报价',  RUS:''},
		{id:'Supplier Next List Price',  ENG:'Supplier Next List Price',  CHN:'生产商下阶段报价',  RUS:''},
		{id:'Total shelf space (%)',  ENG:'Total shelf space (%)',  CHN:'总货架空间(%)',  RUS:''},
		{id:'Net sales (RMB 000)',  ENG:'Net sales (RMB 000)',  CHN:'净销售额(￥百万元)',  RUS:''},
		{id:'share in total (%)',  ENG:'share in total (%)',  CHN:'占总销售额的比例(%)',  RUS:''},
		{id:'Gross contribution (RMB 000)',  ENG:'Gross contribution (RMB 000)',  CHN:'毛利贡献额(￥百万元)',  RUS:''},
		{id:'Financial revenue (RMB 000)',  ENG:'Financial revenue (RMB 000)',  CHN:'财务收入(￥百万元)',  RUS:''},
		{id:'Adjusted gross contribution (RMB 000)',  ENG:'Adjusted gross contribution (RMB 000)',  CHN:'调整后的毛利贡献额(￥百万元)',  RUS:''},
		{id:'Terms of payment (days)',  ENG:'Terms of payment (days)',  CHN:'帐期(天数)',  RUS:''},
		{id:'Purchases',  ENG:'Purchases',  CHN:'本阶段采购量',  RUS:''},

		/*market report*/
		{id:'Market popInfo',  ENG:'Click on column header to sort the table.',  CHN:'点顶部的标题栏, 可以对数据进行排序',  RUS:''},
		{id:'Market studies',  ENG:'Market studies',  CHN:'市场研究',  RUS:''},
		{id:'Market studies Info',  ENG:'Basic market facts collected here in numerical form. They will help you in your analysis of market characteristics and trends as well as consumer preferences, purchasing power by market, category and segment.',  CHN:'这里提供基本的市场数据, 支持你分析市场特征和趋势, 消费者偏好,不同市场、不同品类和不同细分的的购买力。',  RUS:''},	
		{id:'Brand Awareness',  ENG:'Brand Awareness',  CHN:'品牌认知度',  RUS:''},
		{id:'Brand Awareness Info',  ENG:'Extent to which consumers are aware of a particular product measured as percentage of total. Gives you an idea how your promotional expenses and investments into visibility paid off.',  CHN:'品牌认知度指该产品在消费者所有认知的品牌中所占的份额, 反映你在促销和渠道可见度方面投资的回报。',  RUS:''},
		{id:'Market Share (Volume)',  ENG:'Market Share (Volume)',  CHN:'市场份额（以销量计）',  RUS:''},
		{id:'Market Share (Volume) Info',  ENG:'Percentage of a total market, in terms of volume, accounted for by the sales of a specific brand.',  CHN:'该品牌占总市场销量的份额。',  RUS:''},
		{id:'Market Share (Value)',  ENG:'Market Share (Value)',  CHN:'市场份额（以销售额计）',  RUS:''},
		{id:'Market Share (Value) Info',  ENG:'Percentage of a total market, in terms of value, accounted for by the sales of a specific brand.',  CHN:'该品牌占市场总销售额的份额',  RUS:''},
		{id:'Average Net Market Price',  ENG:'Average Net Market Price',  CHN:'平均净市场价',  RUS:''},
		{id:'Average Net Market Price Info',  ENG:'Price at which a product is selling in the open market. It is averaged across all channels. Promotional discounts off normal retail price are also accounted for.',  CHN:'该产品在市场中的公开零售价格,　平均了它在各个渠道的价格,包括扣除了促销折扣的因素。',  RUS:''},
		{id:'Brand Visibility Share',  ENG:'Brand Visibility Share',  CHN:'品牌可见度份额',  RUS:''},
		{id:'Brand Visibility Share Info',  ENG:'An integral measure that averages brand space share and marketing activities increasing brand visibility at a given channel.',  CHN:'一个综合性指标，平衡考虑了品牌份额和特定渠道可见度活动',  RUS:''},
		{id:'Consumer off-take',  ENG:'Consumer off-take',  CHN:'市场销量',  RUS:''},
		{id:'Consumer off-take Info',  ENG:'This measure indicates how many units of a product have been sold to the consumer.',  CHN:'衡量消费者实际购买数量的指标',  RUS:''},

		/*Negotiation*/
		{id:'Negotiation',  ENG:'Negotiation',  CHN:'谈判',  RUS:''},
		{id:'Negotiation Info',  ENG:'Oleg, we need some description here...',  CHN:'你可以在这里和生产商（零售商）基于常见的商业条款进行持续沟通。',  RUS:''},
		{id:'Contract List',  ENG:'Contract List',  CHN:'合同汇总',  RUS:''},
		{id:'Contract List Info',  ENG:'Oleg, we need some description here...',  CHN:'合同清单列出你正在或已经签约的合作协议',  RUS:''},
		{id:'Contract Name',  ENG:'Contract Name',  CHN:'合同名称',  RUS:''},
		{id:'Drafted By',  ENG:'Drafted By',  CHN:'甲方（提出协议的一方)',  RUS:''},
		{id:'Details',  ENG:'Details',  CHN:'细节',  RUS:''},
		{id:'Duplicate',  ENG:'Duplicate',  CHN:'复制',  RUS:''},
		{id:'New Contract',  ENG:'New Contract',  CHN:'新合同',  RUS:''},
		{id:'New Negotiation',  ENG:'New Negotiation',  CHN:'新谈判',  RUS:''},
		{id:'New contract name',  ENG:'New contract name',  CHN:'新合同名称',  RUS:''},
		{id:'Contract with',  ENG:'Contract with',  CHN:'乙方（接受协议的一方)',  RUS:''},
		{id:'Duplicate Negotiation',  ENG:'Duplicate Negotiation',  CHN:'复制谈判',  RUS:''},
		{id:'isLock',  ENG:'isLock',  CHN:'冻结',  RUS:''},

		/*Contract Details*/
		{id:'Contract Details',  ENG:'Contract Details',  CHN:'合同细节',  RUS:''},
		{id:'Contract Details Info',  ENG:'Oleg, we need some description here...',  CHN:'这里显示你和生产商（零售商）达成协议或正在谈判的条款细节',  RUS:''},
		{id:'Contract Name',  ENG:'Contract Name',  CHN:'合同名称',  RUS:''},
		{id:'Seminar',  ENG:'Seminar',  CHN:'课程',  RUS:''},
		{id:'Loading',  ENG:'Loading',  CHN:'加载中',  RUS:''},
		{id:'Items (Producer Input)',  ENG:'Items (Producer Input)',  CHN:'谈判条款（生产商提案）',  RUS:''},
		{id:'Items (Retailer Input)',  ENG:'Items (Retailer Input)',  CHN:'谈判条款（零售商提案）',  RUS:''},
		{id:'Minimum Order & Discount Rate',  ENG:'Minimum Order & Discount Rate',  CHN:'最低订货量和折扣率',  RUS:''},
		{id:'Minimum Order',  ENG:'Minimum Order',  CHN:'最低订货量',  RUS:''},
		{id:'Discount Rate',  ENG:'Discount Rate',  CHN:'折扣率',  RUS:''},
		{id:'Edit',  ENG:'Edit',  CHN:'编辑',  RUS:''},
		{id:'View',  ENG:'View',  CHN:'查看',  RUS:''},
		{id:'Sales Target Volume & Bonus',  ENG:'Sales Target Volume & Bonus',  CHN:'目标销量和奖励',  RUS:''},
		{id:'Sales Target',  ENG:'Sales Target',  CHN:'目标销量',  RUS:''},
		{id:'Bonus',  ENG:'Bonus',  CHN:'奖励',  RUS:''},
		{id:'Payment Days',  ENG:'Payment Days',  CHN:'帐期',  RUS:''},
		{id:'Other Compensation',  ENG:'Other Compensation',  CHN:'其他支持',  RUS:''},
		{id:'Compare and Refresh',  ENG:'Compare and Refresh',  CHN:'比较和更新',  RUS:''},
		{id:'Copy from peer proposal',  ENG:'Copy from peer proposal',  CHN:'完全复制生产商的提案',  RUS:''},
		{id:'Please choose decision level',  ENG:'Please choose decision level',  CHN:'请选择决策层级',  RUS:''},
		{id:'Please choose bonus way',  ENG:'Please choose bonus way',  CHN:'请选择激励方式',  RUS:''},
		{id:'Amount',  ENG:'Amount',  CHN:'金额',  RUS:''},
		{id:'Rate',  ENG:'Rate',  CHN:'折扣比例',  RUS:''},
		{id:'Close',  ENG:'Close',  CHN:'关闭',  RUS:''},

		/*producerstep1*/
		{id:'Products portfolio',  ENG:'Products portfolio',  CHN:'产品组合',  RUS:''},
		{id:'Products portfolio Info',  ENG:'determine your products portfolio, i.e. brand names, variant(s) of each brand with their respective name(s) and product composition or product specification, including packaging format.',  CHN:'决定你的产品组合，如品牌名称、配方、包装等',  RUS:''},
		{id:'Step 1 of 4',  ENG:'Step 1 of 4',  CHN:'步骤 1 / 4',  RUS:''},
		{id:'Producer Step 1 of 4 Info',  ENG:'Products Portfolio Management',  CHN:'产品组合管理',  RUS:''},
		{id:'Category',  ENG:'Category',  CHN:'品类',  RUS:''},
		{id:'Elecssories',  ENG:'Elecssories',  CHN:'电子配件品类',  RUS:''},
		{id:'HealthBeauty',  ENG:'HealthBeauty',  CHN:'美容健康品类',  RUS:''},
		{id:'Elecsories',  ENG:'Elecsories',  CHN:'电子配件品类',  RUS:''},
		{id:'HealthBeauties',  ENG:'HealthBeauties',  CHN:'美容健康品类',  RUS:''},
		{id:'Health&Beauty',  ENG:'HealthBeauties',  CHN:'美容健康品类',  RUS:''},		
		{id:'Available Budget',  ENG:'Total Available Budget for Remaing Period',  CHN:'剩余阶段可用的总预算',  RUS:''},
		{id:'Producer Available Capacity',  ENG:'Current Period Available Capacity',  CHN:'当前阶段可用的产能',  RUS:''},
		{id:'Brand',  ENG:'Brand',  CHN:'品牌',  RUS:''},
		{id:'Variant',  ENG:'Variant',  CHN:'单品',  RUS:''},
		{id:'More',  ENG:'More',  CHN:'更多',  RUS:''},
		{id:'Delete',  ENG:'Delete',  CHN:'删除',  RUS:''},	
		{id:'Pack Format',  ENG:'Pack Format',  CHN:'包装规格',  RUS:''},
		{id:'Pack Format Info',  ENG:'is one value from the list ECONOMY, STANDARD, PREMIUM. Influences price and quality perceptions of a brand. Affects production cost. ',  CHN:'有三种包装规格选择：a)经济包，b)标准包，c)豪华包，包装会影响品牌价格感知和质量感知，也会影响生产成本.',  RUS:''},
		{id:'Technology Level',  ENG:'Technology Level',  CHN:'技术水平',  RUS:''},
		{id:'Technology Level Info',  ENG:'an Elecsorries and Health/Beauty product attribute; an index from 1 to 20 defining quality level of a product; in Elecsorries influences quality and ease of use perceptions; in Health/Beauty allows successful merging of active agent with smoothener; affects production cost. ',  CHN:'两个品类共有的属性特征，用指数1-20代表技术水平。在电子配件品类,　技术水平影响质量和易用性感知，在美容健康品类,技术水平影响活力因子和光滑因子的融合程度.　技术水平会影响生产成本',  RUS:''},
		{id:'Design Level',  ENG:'Design Level',  CHN:'设计水平',  RUS:''},
		{id:'Design Level Info',  ENG:'an Elecsorries product attribute; an index from 1 to 20 defining design of a product; influences ease of use and quality perceptions; affects product cost. ',  CHN:'电子配件品类拥有的属性特征，用指数1-20表示,影响产品的易用性感知和质量感知，会影响生产成本',  RUS:''},
		{id:'Quality-of-Raw-Materials',  ENG:'Quality-of-Raw-Materials',  CHN:'原材料质量',  RUS:''},
		{id:'Quality-of-Raw-Materials Info',  ENG:'an Elecsorries product attribute; an index from 1 to 22 defining quality of raw materials of a product; influences quality perception; affects product cost. ',  CHN:'电子配件品类拥有的属性特征，用指数1-22表示,影响产品的质量感知，会影响生产成本',  RUS:''},
		{id:'Active agent',  ENG:'Active agent',  CHN:'活力因子',  RUS:''},
		{id:'Active agent Info',  ENG:'a Health/Beauties product attribute; an index from 1 to 20; influences performance perception; affects gentleness perception and product cost.',  CHN:'美容健康品类的属性特征，用指数1-20表示,　影响产品效果和柔和度感知，也会影响生产成本',  RUS:''},
		{id:'Smoothener Level',  ENG:'Smoothener Level',  CHN:'光滑因子',  RUS:''},
		{id:'Smoothener Level Info',  ENG:'a Health/Beauties product attribute; an index from 1 to 20; influences gentleness perception; affects product cost.',  CHN:'美容健康品类的属性特征，用指数1-20表示，影响柔和度感知及生产成本',  RUS:''},
		{id:'Estimated Production Volume',  ENG:'Estimated Production Volume',  CHN:'预计产量',  RUS:''},
		{id:'Estimated Production Volume Info',  ENG:'used to calculate estimated product cost with given product composition; on step 2 you will have to put final decision on order. ',  CHN:'预计产量主要用于计算生产成本,　即根据当前的产品配方要求得出的预计生产成本，你可以在下一步最终确认产量',  RUS:''},
		{id:'Discontinue this product',  ENG:'Discontinue this product',  CHN:'停止生产',  RUS:''},
		{id:'Discontinue this product Info',  ENG:'take this decision with caution: all unsold stocks of this product will be automatically returned to your warehouse and scrapped at a cost to your business.',  CHN:'请注意:　所有期末未销售完的库存将退回到你的仓库进行销毁，成为你的成本',  RUS:''},
		{id:'DisContinue',  ENG:'DisContinue',  CHN:'停产',  RUS:''},
		{id:'Continue',  ENG:'Continue',  CHN:'继续生产',  RUS:''},
		{id:'Current Price BM',  ENG:'Current Price BM',  CHN:'当前对实体零售店的报价',  RUS:''},
		{id:'Current Price BM Info',  ENG:'list price for brick&mortar trade in current period; applicable for new launches only.',  CHN:'当前阶段对实体零售店的报价，只适用于新推出的产品',  RUS:''},
		{id:'Current Price Emall',  ENG:'Current Price Emall',  CHN:'当前网上商城的零售价',  RUS:''},
		{id:'Current Price Emall Info',  ENG:'list and wholesale price for eMall in current period; applicable for new launches only. ',  CHN:'当前阶段在网上商城的零售价，只适用于新推出的产品',  RUS:''},
		{id:'New Product',  ENG:'New Product',  CHN:'新产品',  RUS:''},
		{id:'Commit Portflio decision',  ENG:'Commit Portflio decision',  CHN:'确认产品组合决策',  RUS:''},
		{id:'Next',  ENG:'Next',  CHN:'下一步',  RUS:''},
		{id:'Launch New Brand',  ENG:'Launch New Brand',  CHN:'推出新品牌',  RUS:''},
		{id:'Under Existed Brand',  ENG:'Add new product under existed Brand',  CHN:'在现有品牌下推出新单品',  RUS:''},
		{id:'Choose Catagory',  ENG:'Choose Catagory',  CHN:'选择品类',  RUS:''},
		{id:'Choose Brand',  ENG:'Choose Brand',  CHN:'选择品牌',  RUS:''},
		{id:'Enter New Variant Name',  ENG:'Enter New Variant Name',  CHN:'输入新单品名称',  RUS:''},
		{id:'Enter New Brand Name',  ENG:'Enter New Brand Name',  CHN:'输入新品牌名称',  RUS:''},
		{id:'Add',  ENG:'Add',  CHN:'增加',  RUS:''},
		{id:'Cancel',  ENG:'Cancel',  CHN:'取消',  RUS:''},	
		{id:'Current period',  ENG:'Current period',  CHN:'当前阶段',  RUS:''},
		{id:'Previous period',  ENG:'Previous period',  CHN:'上一阶段',  RUS:''},
		{id:'Unit Cost',  ENG:'Unit Cost',  CHN:'单位生产成本',  RUS:''},
		{id:'Acquired Technology Level',  ENG:'Acquired Technology Level',  CHN:'当前拥有最高技术水平',  RUS:''},
		{id:'Acquired Design Level',  ENG:'Acquired Design Level',  CHN:'当前拥有最高设计水平',  RUS:''},
		{id:'Sales Volume',  ENG:'Sales Volume',  CHN:'销量',  RUS:''},
		{id:'Unit Production Cost',  ENG:'Unit Production Cost',  CHN:'单位生产成本',  RUS:''},
		{id:'Production Volume',  ENG:'Production Volume',  CHN:'产量',  RUS:''},
		{id:'Initial Inventory',  ENG:'Initial Inventory',  CHN:'期初库存',  RUS:''},
		{id:'ECONOMY',  ENG:'ECONOMY',  CHN:'经济包',  RUS:''},
		{id:'STANDARD',  ENG:'STANDARD',  CHN:'标准包',  RUS:''},
		{id:'PREMIUM',  ENG:'PREMIUM',  CHN:'豪华包',  RUS:''},
		{id:'SL_BASE',  ENG:'BASE',  CHN:'基础',  RUS:''},
		{id:'SL_FAIR',  ENG:'FAIR',  CHN:'一般',  RUS:''},
		{id:'SL_MEDIUM',  ENG:'MEDIUM',  CHN:'中等',  RUS:''},
		{id:'SL_ENHANCED',  ENG:'ENHANCED',  CHN:'好',  RUS:''},
		{id:'SL_PREMIUM',  ENG:'PREMIUM',  CHN:'优质',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},

		/*producerstep2*/
		{id:'Production and pricing',  ENG:'Production and pricing',  CHN:'生产和定价',  RUS:''},
		{id:'Production and pricing Info',  ENG:'after you have finalized you product portfolio for coming period, you should tell the system volumes to be produced this period and wholesale prices for next period',  CHN:'确定完产品组合后,你需要确定本阶段的产量，并为下阶段制订价格',  RUS:''},
		{id:'Next Price BM',  ENG:'Next Price BM',  CHN:'下阶段对实体零售店的报价',  RUS:''},
		{id:'Next Price BM Info',  ENG:'list price for brick&mortar trade in next period.',  CHN:'下阶段对实体零售店的报价信息',  RUS:''},
		{id:'Next Price Emall',  ENG:'Next Price Emall',  CHN:'下阶段网上商城的零售价',  RUS:''},
		{id:'Next Price Emall Info',  ENG:'list and wholesale price for eMall in next period.',  CHN:'下阶段网上商城的零售价信息',  RUS:''},
		{id:'Step 2 of 4',  ENG:'Step 2 of 4',  CHN:'步骤 2 / 4',  RUS:''},
		{id:'Production Volume Info',  ENG:'volume you order from your factory; check your production capacity for the limits of your order.',  CHN:'你要求工厂生产的数量。注意查看你的产能信息,这是你生产订单的上限',  RUS:''},
		{id:'Back',  ENG:'Back',  CHN:'上一步',  RUS:''},

		/*producer step 3*/
		{id:'Advertising',  ENG:'Advertising',  CHN:'广告',  RUS:''},
		{id:'Producer Advertising Info',  ENG:'After setting production volumes and future wholesale prices you need to take some marketing decisions both market related and national.',  CHN:'现在你需要制订广告决策,　包括全国市场和本地市场',  RUS:''},
		{id:'Step 3 of 4',  ENG:'Step 3 of 4',  CHN:'步骤 3 / 4',  RUS:''},
		{id:'Urban',  ENG:'Urban',  CHN:'城市',  RUS:''},
		{id:'Rural',  ENG:'Rural',  CHN:'农村',  RUS:''},
		{id:'brand awareness',  ENG:'brand awareness',  CHN:'品牌认知度',  RUS:''},
		{id:'brand visibility share',  ENG:'brand visibility share',  CHN:'品牌可见度份额',  RUS:''},
		{id:'Urban Advertising Off-Line',  ENG:'Urban Advertising Off-Line',  CHN:'城市地区传统广告',  RUS:''},
		{id:'Urban Advertising Off-Line Info',  ENG:'budget you spend to advertise your brands in conventional media (printed and TV) in Urban market.',  CHN:'你在城市地区的传统媒体广告投入(如平面媒体和电视)',  RUS:''},
		{id:'Urban Traditional Trade Support',  ENG:'Urban Traditional Trade Support',  CHN:'城市地区传统渠道支持',  RUS:''},
		{id:'Urban Traditional Trade Support Info',  ENG:'budget you invest to support of Traditional Trade in Urban market; it increases visibility of your brands at Traditional Trade. ',  CHN:'你在城市地区传统渠道的投入,提高品牌在传统渠道的可见度份额',  RUS:''},
		{id:'Rural Advertising Off-Line',  ENG:'Rural Advertising Off-Line',  CHN:'农村地区传统广告',  RUS:''},
		{id:'Rural Advertising Off-Line Info',  ENG:'budget you spend to advertise your brands in conventional media (printed and TV) in Rural market. ',  CHN:'你在农村地区的传统媒体广告投入（如平面媒体和电视）',  RUS:''},
		{id:'Rural Traditional Trade Support',  ENG:'Rural Traditional Trade Support',  CHN:'农村地区传统渠道支持',  RUS:''},
		{id:'Rural Traditional Trade Support Info',  ENG:'budget you invest to support of Traditional Trade in Rural market; it increases visibility of your brands at Traditional Trade. ',  CHN:'你在农村地区传统渠道的投入,提高品牌在传统渠道的可见度份额',  RUS:''},
		{id:'National advertising online',  ENG:'National advertising online',  CHN:'全国性网络广告',  RUS:''},
		{id:'E-Mall visibility investment',  ENG:'E-Mall visibility investment',  CHN:'网上商城的可见度投资',  RUS:''},
		{id:'E-Mall visibility investment Info',  ENG:'budget invested in increasing visibility of your brands at eMall.',  CHN:'用于提高品牌在网上商城可见度的投资',  RUS:''},
		{id:'On-line Advertising',  ENG:'On-line Advertising',  CHN:'网络广告',  RUS:''},
		{id:'On-line Advertising Info',  ENG:'budget spent to advertise your brands on the Internet, including social media.',  CHN:'你在网络包括社交媒体上用于提高品牌知名度的投资',  RUS:''},

		/*producer step 4*/
		{id:'Category Decision',  ENG:'Category Decision',  CHN:'品类决策',  RUS:''},
		{id:'Category Decision Info',  ENG:'At last you have to make decisions influencing whole category. These decisions are long-term investments, that is why they are not taken from your limited operational budget, you borrow these investments from capital market at a cost. Keep in mind that your long-term investments increase your fixed assets and consequently costs of running business. ',  CHN:'制订品类层面的决策，这属于公司长期决策，这部分投资不占用你有限的运营预算,而是以一定成本从资本市场获得,请注意长期投资会增加你的固定资产,　最终会增加你的运营资本.',  RUS:''},
		{id:'Step 4 of 4',  ENG:'Step 4 of 4',  CHN:'步骤 4 / 4',  RUS:''},
		{id:'in capacity change',  ENG:'Investment in Capacity Change',  CHN:'产能投资',  RUS:''},
		{id:'in capacity change Info',  ENG:"to extend your capacity you have to invest a period before it gets ready; current period extension is also possible but at 50% higher charge; your capacity increases your fixed assets and labor cost; you cannot sell out or lease your capacity to other players.",  CHN:'通常需要提前一个阶段投资下阶段的产能,你也可以选择在当前阶段立刻提高产能,但是成本增加50%, 你的固定资产和劳动力成本也会因此增加。产能一旦增加,你不能出售或租赁给其他公司',  RUS:''},
		{id:'improve Available Technology',  ENG:'Investment to improve Available Technology',  CHN:'技术水平投资',  RUS:''},
		{id:'improve Available Technology Info',  ENG:'applies to both categories; you start with level 7 and can increase it to 20 by the session end; increases your fixed assets.',  CHN:'技术水平适用于两个品类,　每家公司的最高技术水平在开始阶段都是７，到模拟结束时最高可以增加到20。提高技术水平会增加你的固定资产.',  RUS:''},
		{id:'improve Flexibility',  ENG:'Investment to improve Flexibility',  CHN:'灵活性投资',  RUS:''},
		{id:'improve Flexibility Info',  ENG:"applies to both categories; helps you to automatically adjust your production to correspond to orders placed by retailers; affects your fixed assets. ",  CHN:'灵活性适用于两个品类,　它能根据零售商实际订单数量自动调整产量。灵活性投资会增加你的固定资产.',  RUS:''},
		{id:'improve Design Know-How',  ENG:'Investment to improve Design Know-How',  CHN:'提高Know How的投资',  RUS:''},
		{id:'improve Design Know-How Info',  ENG:'Health/Beauties; you start with level 7 and can increase it to 20 by the session end; increases your fixed assets.',  CHN:'适用于美容健康品类,每家公司的最高水平在开始阶段都为７，到模拟结束时最高可以增加到20,　提高know how水平,会增加你的固定资产。',  RUS:''},
		{id:'Production capacity',  ENG:'Production capacity',  CHN:'产能',  RUS:''},
		{id:'Acquired production flexibility',  ENG:'Acquired production flexibility',  CHN:'所拥有的生产灵活性',  RUS:''},

		/*retailer step 1*/
		{id:'Rteailer Advertising Info',  ENG:'define your marketing investments. These investments are given to online and offline agencies that carry out marketing campaigns for you. You can also define what slogan your agency promotes for you, you just need to allocate your budget between three shopper perceptions (convenience, assortment and price) in such a way that dimension you promote most gets more money.',  CHN:'制订你的市场决策。第三方网络和传统广告机构会根据你的要求完成市场活动.你只需确定在三个感知维度（便利性,　产品组合和价格)上的预算分配.',  RUS:''},
		{id:'More information',  ENG:'More information',  CHN:'更多信息',  RUS:''},
		{id:'Convenience Off-line',  ENG:'Convenience Off-line',  CHN:'便利性传统广告',  RUS:''},
		{id:'Convenience Off-line Info',  ENG:'budget you give offline advertising agencies to promote convenience of your store chain. ',  CHN:'给传统广告机构的预算,用于提高你门店的便利性感知',  RUS:''},
		{id:'Assortment Off-line',  ENG:'Assortment Off-line',  CHN:'产品组合传统广告',  RUS:''},
		{id:'Assortment Off-line Info',  ENG:'budget you give offline advertising agencies to promote assortment of your store chain. ',  CHN:'给传统广告机构的预算,用于提高你门店的产品组合感知',  RUS:''},
		{id:'Price Off-line',  ENG:'Price Off-line',  CHN:'价格传统广告',  RUS:''},
		{id:'Price Off-line Info',  ENG:'budget you give offline advertising agencies to promote price level of your store chain. ',  CHN:'给传统广告机构的预算,用于提高你门店的价格感知',  RUS:''},
		{id:'Convenience On-line',  ENG:'Convenience On-line',  CHN:'便利性网络广告',  RUS:''},
		{id:'Convenience On-line Info',  ENG:'budget you give online advertising agencies to promote convenience of your store chain.',  CHN:'给网络告机构的预算,用于提高你门店的便利性感知',  RUS:''},
		{id:'Assortment On-line',  ENG:'Assortment On-line',  CHN:'产品组合网络广告',  RUS:''},
		{id:'Assortment On-line Info',  ENG:'budget you give online advertising agencies to promote assortment of your store chain.',  CHN:'给网络广告机构的预算,用于提高你门店的产品组合感知',  RUS:''},
		{id:'Price On-line',  ENG:'Price On-line',  CHN:'价格网络广告',  RUS:''},
		{id:'Price On-line Info',  ENG:'budget you give online advertising agencies to promote price level of your store chain. ',  CHN:'给网络广告机构的预算,用于提高你门店的价格感知',  RUS:''},

		/*retailer step 2*/
		{id:'Market',  ENG:'Market',  CHN:'市场',  RUS:''},
		{id:'Market Info',  ENG:'After completing national set of decisions, it would be logical to work on the decisions specific for each of the markets. They will be of a strategic essence and influence your store chain positioning on the market. ',  CHN:'制订本地市场的决策，这将影响门店在当地市场的定位。',  RUS:''},
		{id:'In-store Service Level',  ENG:'In-store Service Level',  CHN:'店内服务水平',  RUS:''},
		{id:'In-store Service Level Info',  ENG:'one of the following BASE, FAIR, MEDIUM, ENHANCED, PREMIUM; represents integrally expenditures of a retail chain on its service (labor costs, equipment and fixtures, lighting, etc.); influences convenience and assortment directly and price perception in reverse',  CHN:'提供"基础"、“一般"、”中等"、“好"和”优质"五种选择，直接影响购物者对你门店的便利性和产品组合感知，对价格感知起反作用',  RUS:''},
		{id:'Elecssories Selling surface',  ENG:'Elecssories Selling surface',  CHN:'电子配件品类的货架份额',  RUS:''},
		{id:'Elecssories Selling surface Info',  ENG:'you may decide to increase store space allocated for one category and decrease accordingly another; total space allocated to both categories should be 100%; you must not kill any category, provisionally minimum store space must be 35%, therefore maximum store space per category could be 65%.',  CHN:'你可以灵活分配两个品类的货架份额比例,　两个品类加起来等于100%。为了避免扼杀任一品类,　分配给一个品类的货架份额至少为35%, 即任一品类能分配的货架份额最高为65%.',  RUS:''},
		{id:'HealthBeauty Selling surface',  ENG:'HealthBeauty Selling surface',  CHN:'美容健康品类的货架份额',  RUS:''},
		{id:'HealthBeauty Selling surface Info',  ENG:'you may decide to increase store space allocated for one category and decrease accordingly another; total space allocated to both categories should be 100%; you must not kill any category, provisionally minimum store space must be 35%, therefore maximum store space per category could be 65%. ',  CHN:'你可以灵活分配两个品类占据的货架比例,　两个品类加起来等于100%。为了避免扼杀任一品类,　分配给一个品类的货架份额至少为35%, 即任一品类能分配的货架份额最高为65%.',  RUS:''},
		{id:'Local Convenience Advertising',  ENG:'Local Convenience Advertising',  CHN:'本地便利性广告',  RUS:''},
		{id:'Local Convenience Advertising Info',  ENG:'budget you spend to advertise your store chain locally (outdoors Advertising, leaflets); promotes convenience of your stores.',  CHN:'门店在本地投放的广告（户外广告，宣传单页等)，提高门店的便利性感知',  RUS:''},
		{id:'Local Assortment Advertising',  ENG:'Local Assortment Advertising',  CHN:'本地市场产品组合广告',  RUS:''},
		{id:'Local Assortment Advertising Info',  ENG:'budget you spend to advertise your store chain locally (outdoors advertising, leaflets); promotes assortment of your stores.',  CHN:'门店在本地投放的广告（户外广告，宣传单页等)，提高门店的产品组合感知',  RUS:''},
		{id:'Local Price Advertising',  ENG:'Local Price Advertising',  CHN:'本地市场价格广告',  RUS:''},
		{id:'Local Price Advertising Info',  ENG:'budget you spend to advertise your store chain locally (outdoors advertising, leaflets); promotes price perception of your stores. ',  CHN:'门店在本地投放的广告（户外广告，宣传单页等)，提高门店的价格感知',  RUS:''},
		{id:'Allocate Empty Place',  ENG:'Allocate Empty Place',  CHN:'分配空的货架',  RUS:''},
		{id:'Allocate Empty Place Info',  ENG:'Allocate Empty Place Info',  CHN:'分配空的货架',  RUS:''},
		{id:'Allocate',  ENG:'Allocate',  CHN:'分配',  RUS:''},
		{id:'No',  ENG:'No',  CHN:'不分配',  RUS:''},

		/*retailer step 3*/
		{id:'Private Labels Composition',  ENG:'Private Labels Composition',  CHN:'自有品牌决策',  RUS:''},
		{id:'Private Labels Composition Info',  ENG:'At this step you have to think about and take your decision on the portfolio of your private labels. You start with one PL per category per market. You may have three PLs per category per market.',  CHN:'制订你的自有品牌组合决策.你在开始阶段每个市场每个品类各有一个自有品牌,　最多可以在每个市场每个品类各拥有三个自有品牌.',  RUS:''},
		{id:'Unit Production Cost',  ENG:'Unit Production Cost',  CHN:'单位生产成本',  RUS:''},
		{id:'Retailer Discontinue this product',  ENG:'Discontinue this product',  CHN:'停止销售',  RUS:''},
		{id:'Retailer Discontinue this product Info',  ENG:'take this decision with caution: all unsold stocks of this product will be automatically returned to your warehouse and scrapped at a cost to your business.',  CHN:'请注意:　所有期末未销售完的库存将退回到你的仓库进行销毁，成为你的成本',  RUS:''},
		{id:'Retailer DisContinue',  ENG:'DisContinue',  CHN:'停止销售',  RUS:''},
		{id:'Retailer Continue',  ENG:'Continue',  CHN:'继续销售',  RUS:''},

		/*retailer step 4*/
		{id:'Order Pricing Shelf',  ENG:'Order, Pricing and Shelf Allocation',  CHN:'订货、定价和货架分配',  RUS:''},
		{id:'Order Pricing Shelf Info',  ENG:'placing orders with suppliers, allocating shelf space, setting retail price and defining promotions for each brand (both supplier and private label) at each market.',  CHN:'确定向生产商的定货量,制订零售价，分市场、按品类为每个单品（包括生产商和你的自有品牌)分配货架空间,制订促销计划',  RUS:''},
		{id:'Available ShelfSpace',  ENG:'Available ShelfSpace',  CHN:'可分配的货架空间',  RUS:''},
		{id:'Private Label',  ENG:'Private Label',  CHN:'自有品牌',  RUS:''},		
		{id:'List Price',  ENG:'List Price',  CHN:'进货价',  RUS:''},
		{id:'Closing Inventory',  ENG:'Closing Inventory',  CHN:'期末库存',  RUS:''},
		{id:'Sales Volume at your store',  ENG:'Sales Volume at your store',  CHN:'在你门店的销量',  RUS:''},
		{id:'Shelf Space at your store',  ENG:'Shelf Space at your store',  CHN:'占你门店的货架空间',  RUS:''},
		{id:'Market Price at your store',  ENG:'Market Price at your store',  CHN:'在你门店的市场零售价',  RUS:''},
		{id:'Net Price at your store',  ENG:'Net Price at your store',  CHN:'在你门店的净零售价',  RUS:''},
		{id:'weeks',  ENG:'weeks',  CHN:'周数',  RUS:''},
		{id:'Order Volume',  ENG:'Order Volume',  CHN:'订货量',  RUS:''},
		{id:'Order Volume Info',  ENG:'volume your order from manufacturer; you need to take into account brand potential, your current stocks and negotiated volumes/discounts to make a balanced decision.',  CHN:'你向生产商的下单量,建议综合考虑品牌的潜力、前期库存、你和生产商约定的数量／折扣协议等。',  RUS:''},
		{id:'Shelf Space',  ENG:'Shelf Space',  CHN:'货架份额',  RUS:''},
		{id:'Shelf Space Info',  ENG:'you may give a brand 5% of shelf space minimum. ',  CHN:'每个品牌最低分配的货架份额不能低于5%',  RUS:''},
		{id:'Retail Price',  ENG:'Retail Price',  CHN:'零售价',  RUS:''},
		{id:'Retail Price Info',  ENG:'your normal retail price which is the basis for promotional discounts. ',  CHN:'这是你做促销时的正常基础价格。',  RUS:''},
		{id:'Promotions Frequency',  ENG:'Promotions Frequency',  CHN:'促销频率',  RUS:''},
		{id:'Promotions Frequency Info',  ENG:'number of weeks out of 26 in each period when you plan to make your promotion campaign effective.',  CHN:'26周中你决定多少周做促销',  RUS:''},
		{id:'Reduction Rate',  ENG:'Reduction Rate',  CHN:'折扣率',  RUS:''},
		{id:'Reduction Rate Info',  ENG:'discount percent off normal retail price effective during promotions.',  CHN:'在促销期间提供的优惠折扣比率',  RUS:''},
		{id:'Add Order',  ENG:'Add Order',  CHN:'增加订单',  RUS:''},
		{id:'Order Product',  ENG:'Order Product',  CHN:'选择商品',  RUS:''},
		{id:'Produced by',  ENG:'Produced by',  CHN:'生产厂家',  RUS:''},
		/*error message need some time to clear up*/
		{id:'Not set',  ENG:'Not set',  CHN:'请选择',  RUS:''},
		{id:'Input a number',  ENG:'Enter a negative number(Allow two decimal places)',  CHN:'请输入非负数(可保留两位小数)',  RUS:''},
		{id:'fail',  ENG:'check fail,please call the admin',  CHN:'验证失败,请联系管理员',  RUS:''},
		{id:'Input a Integer',  ENG:'请输入正整数',  CHN:'',  RUS:''},
		{id:'Input range',  ENG:'Input range',  CHN:'输入范围',  RUS:''},
		{id:'Error',  ENG:'Error',  CHN:'错误',  RUS:''},
		{id:'Success',  ENG:'Success',  CHN:'成功',  RUS:''},
		{id:'Warning',  ENG:'Warning',  CHN:'警告',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''}
	]
}
