var getLabelBase = function(){
	return [
		/*map*/
		{id:'Ease of Use perception',  ENG:'Ease of Use perception',  CHN:'易用度感知',  RUS:''},
		{id:'Quality perception',  ENG:'Quality perception',  CHN:'品质感知',  RUS:''},
		{id:'Performance perception',  ENG:'Performance perception',  CHN:'使用效果感知',  RUS:''},
		{id:'Gentleness perception',  ENG:'Gentleness perception',  CHN:'润滑度感知',  RUS:''},
		{id:'PricePerception',  ENG:'PricePerception',  CHN:'价格感知',  RUS:''},
		{id:'Producer',  ENG:'Producer ',  CHN:'生产商 ',  RUS:''},
		{id:'Retailer',  ENG:'Retailer ',  CHN:'零售商 ',  RUS:''},
		{id:'switchLanguage',  ENG:'Switch Language',  CHN:'切换界语言',  RUS:''},
		/*producerstep1*/
		{id:'Products portfolio',  ENG:'Products portfolio',  CHN:'',  RUS:''},
		{id:'Products portfolio Info',  ENG:'Step 1 of 4, determine your products portfolio, i.e. brand names, variant(s) of each brand with their respective name(s) and product composition or product specification, including packaging format.',  CHN:'',  RUS:''},
		{id:'Step 1 of 4',  ENG:'Step 1 of 4',  CHN:'第一步',  RUS:''},
		{id:'Step 1 of 4 Info',  ENG:'Products Portfolio Management',  CHN:'',  RUS:''},
		{id:'Category',  ENG:'Category',  CHN:'品类',  RUS:''},
		{id:'Elecssories',  ENG:'Elecssories',  CHN:'',  RUS:''},
		{id:'HealthBeauty',  ENG:'HealthBeauty',  CHN:'',  RUS:''},
		{id:'Producer Avaliable Budget',  ENG:'Total Avaliable Budget for Remaing Period',  CHN:'',  RUS:''},
		{id:'Producer Available Capacity',  ENG:'Available Capacity',  CHN:'',  RUS:''},
		{id:'Brand',  ENG:'Brand',  CHN:'品牌',  RUS:''},
		{id:'Variant',  ENG:'Variant',  CHN:'单品',  RUS:''},
		{id:'Pack Format',  ENG:'Pack Format',  CHN:'包',  RUS:''},
		{id:'Pack Format Info',  ENG:'is one value from the list ECONOMY, STANDARD, PREMIUM. Influences price and quality perceptions of a brand. Affects production cost. ',  CHN:'',  RUS:''},
		{id:'Technology Level',  ENG:'Technology Level',  CHN:'技术水平',  RUS:''},
		{id:'Technology Level Info',  ENG:'an Elecsorries and Health/Beauty product attribute; an index from 1 to 20 defining quality level of a product; in Elecsorries influences quality and ease of use perceptions; in Health/Beauty allows successful merging of active agent with smoothener; affects production cost. ',  CHN:'',  RUS:''},
		{id:'Design Level',  ENG:'Design Level',  CHN:'设计指数',  RUS:''},
		{id:'Design Level Info',  ENG:'an Elecsorries product attribute; an index from 1 to 20 defining design of a product; influences ease of use and quality perceptions; affects product cost. ',  CHN:'',  RUS:''},
		{id:'Quality-of-Raw-Materials',  ENG:'Quality-of-Raw-Materials',  CHN:'原始材料质量',  RUS:''},
		{id:'Quality-of-Raw-Materials Info',  ENG:'an Elecsorries product attribute; an index from 1 to 22 defining quality of raw materials of a product; influences quality perception; affects product cost. ',  CHN:'',  RUS:''},
		{id:'Active agent',  ENG:'Active agent',  CHN:'活性剂',  RUS:''},
		{id:'Active agent Info',  ENG:'a Health/Beauties product attribute; an index from 1 to 20; influences performance perception; affects gentleness perception and product cost.',  CHN:'',  RUS:''},
		{id:'Smoothener Level',  ENG:'Smoothener Level',  CHN:'',  RUS:''},
		{id:'Smoothener Level Info',  ENG:'a Health/Beauties product attribute; an index from 1 to 20; influences gentleness perception; affects product cost.',  CHN:'',  RUS:''},
		{id:'Estimated Production Volume',  ENG:'Estimated Production Volume',  CHN:'',  RUS:''},
		{id:'Estimated Production Volume Info',  ENG:'used to calculate estimated product cost with given product composition; on step 2 you will have to put final decision on order. ',  CHN:'',  RUS:''},
		{id:'Discontinue this product',  ENG:'Discontinue this product',  CHN:'停止生产',  RUS:''},
		{id:'Discontinue this product Info',  ENG:'take this decision with caution: all unsold stocks of this product will be automatically returned to your warehouse and scrapped at a cost to your business.',  CHN:'',  RUS:''},
		{id:'Current Price BM',  ENG:'Current Price BM',  CHN:'',  RUS:''},
		{id:'Current Price BM Info',  ENG:'list price for brick&mortar trade in current period; applicable for new launches only.',  CHN:'',  RUS:''},
		{id:'Current Price Emall',  ENG:'Current Price Emall',  CHN:'',  RUS:''},
		{id:'Current Price Emall Info',  ENG:'list and wholesale price for eMall in current period; applicable for new launches only. ',  CHN:'',  RUS:''},
		{id:'New Product',  ENG:'New Product',  CHN:'',  RUS:''},
		{id:'Commit Portflio decision',  ENG:'Commit Portflio decision',  CHN:'',  RUS:''},
		{id:'Next',  ENG:'Next',  CHN:'',  RUS:''},
		{id:'Launch New Brand',  ENG:'Launch New Brand',  CHN:'',  RUS:''},
		{id:'Under Existed Brand',  ENG:'Add new product under existed Brand',  CHN:'',  RUS:''},
		{id:'Choose Catagory',  ENG:'Choose Catagory',  CHN:'',  RUS:''},
		{id:'Choose Brand',  ENG:'Choose Brand',  CHN:'',  RUS:''},
		{id:'Enter New Variant Name',  ENG:'Enter New Variant Name',  CHN:'',  RUS:''},
		{id:'Enter New Brand Name',  ENG:'Enter New Brand Name',  CHN:'',  RUS:''},
		/*{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},*/
		/*producerstep2*/
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''},
		{id:'',  ENG:'',  CHN:'',  RUS:''}
	]
}
