var mongoose = require('mongoose'),
	http = require('http'),
	util = require('util'),
	_ = require('underscore'),
	request = require('request'),
	q = require('q');

var RCR_profitabilityBySupplierSchema = mongoose.Schema({
	period : Number,
    seminar : String,
    retailerID  : Number, //TBMRetailers : 1~3 (BMRetsMax)

    rcrps_ShelfSpace                     : [categoryInfoSchema],
    rcrps_NetSales                       : [categoryInfoSchema],
    rcrps_NetSalesPerShelfSpace          : [categoryInfoSchema],
    rcrps_NetSalesShare                  : [categoryInfoSchema],
    rcrps_GrossContribution              : [categoryInfoSchema],
    rcrps_GrossContributionPerShelfSpace : [categoryInfoSchema],
    rcrps_GrossContributionMargin        : [categoryInfoSchema],
    rcrps_GrossContributionShare         : [categoryInfoSchema],
    rcrps_PaymentTerms                   : [categoryInfoSchema],
})

var categoryInfoSchema = mongoose.Schema({
    categoryID : Number,  //TCategoriesTotal : 1~2 
    marketInfo : [marketInfoSchema]
})

var marketInfoSchema = mongoose.Schema({
    marketID : Number, //TMarketsTotal : 1~3
    factoriesInfo : [factoriesInfoSchema]
})

var factoriesInfoSchema = mongoose.Schema({
    factoriesID : Number, 
    /*    
    {                                TFactories correspond to:                                                    }
    {       [1] = Supplier_1,                                                                                     }
    {       [2] = Supplier_2,                                                                                     }
    {       [3] = Supplier_3,                                                                                     }
    {       [4] = Supplier_4, only if he is ACTIVE player and in that case can sell his brands to B&M retailers,  }
    {                         otherwise (i.e. Supplier_4 is PASSIVE) this column(s) should not be displayed       }
    {                         because Supplier_4 brands are only sold on-line                                     }
    {       [5] = Supplier_4, this time as a producer of private labels                                           }
    */    
    value : Number,
})

//new Schema, 2014-Apr-17th:
// var RCR_profitabilityBySupplierSchema = mongoose.Schema({
//     period : Number,
//     seminar : String,
//     retailerID  : Number, //TBMRetailers : 1~3 (BMRetsMax)

//     rcrps_ShelfSpace                     : [factoriesDetailsSchema],
//     rcrps_NetSales                       : [factoriesDetailsSchema],
//     rcrps_NetSalesPerShelfSpace          : [factoriesDetailsSchema],
//     rcrps_NetSalesShare                  : [factoriesDetailsSchema],
//     rcrps_GrossContribution              : [factoriesDetailsSchema],
//     rcrps_GrossContributionPerShelfSpace : [factoriesDetailsSchema],
//     rcrps_GrossContributionMargin        : [factoriesDetailsSchema],
//     rcrps_GrossContributionShare         : [factoriesDetailsSchema],
//     rcrps_PaymentTerms                   : [factoriesDetailsSchema],
// })

// var factoriesDetailsSchema = mongoose.Schema({
//     categoryID : Number,  //TCategoriesTotal : 1~2 
//     marketID : Number, //TMarketsTotal : 1~3
//     factoriesID : Number, 
    /*    
    {                                TFactories correspond to:                                                    }
    {       [1] = Supplier_1,                                                                                     }
    {       [2] = Supplier_2,                                                                                     }
    {       [3] = Supplier_3,                                                                                     }
    {       [4] = Supplier_4, only if he is ACTIVE player and in that case can sell his brands to B&M retailers,  }
    {                         otherwise (i.e. Supplier_4 is PASSIVE) this column(s) should not be displayed       }
    {                         because Supplier_4 brands are only sold on-line                                     }
    {       [5] = Supplier_4, this time as a producer of private labels                                           }
    */   
//     value : Number    
// })


var RCR_profitabilityBySupplier=mongoose.model('RCR_profitabilityBySupplier',RCR_profitabilityBySupplierSchema);

exports.addRCR_profitabilityBySupplier=function(req,res,next){
    var newRCR_profitabilityBySupplier=RCR_profitabilityBySupplier({
        period : 0,
        seminar : 'MAY',
        retailerID  : 1, //TBMRetailers : 1~3 (BMRetsMax)

        rcrps_ShelfSpace                     : [{
            categoryID:1,
            marketInfo:[{
                marketID:1,
                factoriesInfo:[{
                    factoriesID:1,
                    value:10
                },{
                    factoriesID:2,
                    value:20
                },{
                    factoriesID:3,
                    value:30
                },{
                    factoriesID:4,
                    value:40
                },{
                    factoriesID:5,
                    value:50
                }]
            },{
                marketID:2,
                factoriesInfo:[{
                    factoriesID:1,
                    value:15
                },{
                    factoriesID:2,
                    value:25
                },{
                    factoriesID:3,
                    value:35
                },{
                    factoriesID:4,
                    value:45
                },{
                    factoriesID:5,
                    value:55
                }]
            },{
                marketID:3,
                factoriesInfo:[{
                    factoriesID:1,
                    value:19
                },{
                    factoriesID:2,
                    value:29
                },{
                    factoriesID:3,
                    value:39
                },{
                    factoriesID:4,
                    value:49
                },{
                    factoriesID:5,
                    value:59
                }]
            }]
        },{
            categoryID:2,
            marketInfo:[{
                marketID:1,
                factoriesInfo:[{
                    factoriesID:1,
                    value:11
                },{
                    factoriesID:2,
                    value:21
                },{
                    factoriesID:3,
                    value:31
                },{
                    factoriesID:4,
                    value:41
                },{
                    factoriesID:5,
                    value:51
                }]
            },{
                marketID:2,
                factoriesInfo:[{
                    factoriesID:1,
                    value:16
                },{
                    factoriesID:2,
                    value:26
                },{
                    factoriesID:3,
                    value:36
                },{
                    factoriesID:4,
                    value:46
                },{
                    factoriesID:5,
                    value:56
                }]
            },{
                marketID:3,
                factoriesInfo:[{
                    factoriesID:1,
                    value:18
                },{
                    factoriesID:2,
                    value:28
                },{
                    factoriesID:3,
                    value:38
                },{
                    factoriesID:4,
                    value:48
                },{
                    factoriesID:5,
                    value:58
                }]
            }]
        },{
            categoryID:3,
            marketInfo:[{
                marketID:1,
                factoriesInfo:[{
                    factoriesID:1,
                    value:12
                },{
                    factoriesID:2,
                    value:22
                },{
                    factoriesID:3,
                    value:32
                },{
                    factoriesID:4,
                    value:42
                },{
                    factoriesID:5,
                    value:52
                }]
            },{
                marketID:2,
                factoriesInfo:[{
                    factoriesID:1,
                    value:13
                },{
                    factoriesID:2,
                    value:23
                },{
                    factoriesID:3,
                    value:33
                },{
                    factoriesID:4,
                    value:43
                },{
                    factoriesID:5,
                    value:53
                }]
            },{
                marketID:3,
                factoriesInfo:[{
                    factoriesID:1,
                    value:17
                },{
                    factoriesID:2,
                    value:27
                },{
                    factoriesID:3,
                    value:37
                },{
                    factoriesID:4,
                    value:47
                },{
                    factoriesID:5,
                    value:57
                }]
            }]
        }],
        rcrps_NetSales                       : [{
            categoryID:1,
            marketInfo:[{
                marketID:1,
                factoriesInfo:[{
                    factoriesID:1,
                    value:10
                },{
                    factoriesID:2,
                    value:20
                },{
                    factoriesID:3,
                    value:30
                },{
                    factoriesID:4,
                    value:40
                },{
                    factoriesID:5,
                    value:50
                }]
            },{
                marketID:2,
                factoriesInfo:[{
                    factoriesID:1,
                    value:15
                },{
                    factoriesID:2,
                    value:25
                },{
                    factoriesID:3,
                    value:35
                },{
                    factoriesID:4,
                    value:45
                },{
                    factoriesID:5,
                    value:55
                }]
            },{
                marketID:3,
                factoriesInfo:[{
                    factoriesID:1,
                    value:19
                },{
                    factoriesID:2,
                    value:29
                },{
                    factoriesID:3,
                    value:39
                },{
                    factoriesID:4,
                    value:49
                },{
                    factoriesID:5,
                    value:59
                }]
            }]
        },{
            categoryID:2,
            marketInfo:[{
                marketID:1,
                factoriesInfo:[{
                    factoriesID:1,
                    value:11
                },{
                    factoriesID:2,
                    value:21
                },{
                    factoriesID:3,
                    value:31
                },{
                    factoriesID:4,
                    value:41
                },{
                    factoriesID:5,
                    value:51
                }]
            },{
                marketID:2,
                factoriesInfo:[{
                    factoriesID:1,
                    value:16
                },{
                    factoriesID:2,
                    value:26
                },{
                    factoriesID:3,
                    value:36
                },{
                    factoriesID:4,
                    value:46
                },{
                    factoriesID:5,
                    value:56
                }]
            },{
                marketID:3,
                factoriesInfo:[{
                    factoriesID:1,
                    value:18
                },{
                    factoriesID:2,
                    value:28
                },{
                    factoriesID:3,
                    value:38
                },{
                    factoriesID:4,
                    value:48
                },{
                    factoriesID:5,
                    value:58
                }]
            }]
        },{
            categoryID:3,
            marketInfo:[{
                marketID:1,
                factoriesInfo:[{
                    factoriesID:1,
                    value:12
                },{
                    factoriesID:2,
                    value:22
                },{
                    factoriesID:3,
                    value:32
                },{
                    factoriesID:4,
                    value:42
                },{
                    factoriesID:5,
                    value:52
                }]
            },{
                marketID:2,
                factoriesInfo:[{
                    factoriesID:1,
                    value:13
                },{
                    factoriesID:2,
                    value:23
                },{
                    factoriesID:3,
                    value:33
                },{
                    factoriesID:4,
                    value:43
                },{
                    factoriesID:5,
                    value:53
                }]
            },{
                marketID:3,
                factoriesInfo:[{
                    factoriesID:1,
                    value:17
                },{
                    factoriesID:2,
                    value:27
                },{
                    factoriesID:3,
                    value:37
                },{
                    factoriesID:4,
                    value:47
                },{
                    factoriesID:5,
                    value:57
                }]
            }]
        }],
        rcrps_NetSalesPerShelfSpace          : [{
            categoryID:1,
            marketInfo:[{
                marketID:1,
                factoriesInfo:[{
                    factoriesID:1,
                    value:10
                },{
                    factoriesID:2,
                    value:20
                },{
                    factoriesID:3,
                    value:30
                },{
                    factoriesID:4,
                    value:40
                },{
                    factoriesID:5,
                    value:50
                }]
            },{
                marketID:2,
                factoriesInfo:[{
                    factoriesID:1,
                    value:15
                },{
                    factoriesID:2,
                    value:25
                },{
                    factoriesID:3,
                    value:35
                },{
                    factoriesID:4,
                    value:45
                },{
                    factoriesID:5,
                    value:55
                }]
            },{
                marketID:3,
                factoriesInfo:[{
                    factoriesID:1,
                    value:19
                },{
                    factoriesID:2,
                    value:29
                },{
                    factoriesID:3,
                    value:39
                },{
                    factoriesID:4,
                    value:49
                },{
                    factoriesID:5,
                    value:59
                }]
            }]
        },{
            categoryID:2,
            marketInfo:[{
                marketID:1,
                factoriesInfo:[{
                    factoriesID:1,
                    value:11
                },{
                    factoriesID:2,
                    value:21
                },{
                    factoriesID:3,
                    value:31
                },{
                    factoriesID:4,
                    value:41
                },{
                    factoriesID:5,
                    value:51
                }]
            },{
                marketID:2,
                factoriesInfo:[{
                    factoriesID:1,
                    value:16
                },{
                    factoriesID:2,
                    value:26
                },{
                    factoriesID:3,
                    value:36
                },{
                    factoriesID:4,
                    value:46
                },{
                    factoriesID:5,
                    value:56
                }]
            },{
                marketID:3,
                factoriesInfo:[{
                    factoriesID:1,
                    value:18
                },{
                    factoriesID:2,
                    value:28
                },{
                    factoriesID:3,
                    value:38
                },{
                    factoriesID:4,
                    value:48
                },{
                    factoriesID:5,
                    value:58
                }]
            }]
        },{
            categoryID:3,
            marketInfo:[{
                marketID:1,
                factoriesInfo:[{
                    factoriesID:1,
                    value:12
                },{
                    factoriesID:2,
                    value:22
                },{
                    factoriesID:3,
                    value:32
                },{
                    factoriesID:4,
                    value:42
                },{
                    factoriesID:5,
                    value:52
                }]
            },{
                marketID:2,
                factoriesInfo:[{
                    factoriesID:1,
                    value:13
                },{
                    factoriesID:2,
                    value:23
                },{
                    factoriesID:3,
                    value:33
                },{
                    factoriesID:4,
                    value:43
                },{
                    factoriesID:5,
                    value:53
                }]
            },{
                marketID:3,
                factoriesInfo:[{
                    factoriesID:1,
                    value:17
                },{
                    factoriesID:2,
                    value:27
                },{
                    factoriesID:3,
                    value:37
                },{
                    factoriesID:4,
                    value:47
                },{
                    factoriesID:5,
                    value:57
                }]
            }]
        }],
        rcrps_NetSalesShare                  : [{
            categoryID:1,
            marketInfo:[{
                marketID:1,
                factoriesInfo:[{
                    factoriesID:1,
                    value:10
                },{
                    factoriesID:2,
                    value:20
                },{
                    factoriesID:3,
                    value:30
                },{
                    factoriesID:4,
                    value:40
                },{
                    factoriesID:5,
                    value:50
                }]
            },{
                marketID:2,
                factoriesInfo:[{
                    factoriesID:1,
                    value:15
                },{
                    factoriesID:2,
                    value:25
                },{
                    factoriesID:3,
                    value:35
                },{
                    factoriesID:4,
                    value:45
                },{
                    factoriesID:5,
                    value:55
                }]
            },{
                marketID:3,
                factoriesInfo:[{
                    factoriesID:1,
                    value:19
                },{
                    factoriesID:2,
                    value:29
                },{
                    factoriesID:3,
                    value:39
                },{
                    factoriesID:4,
                    value:49
                },{
                    factoriesID:5,
                    value:59
                }]
            }]
        },{
            categoryID:2,
            marketInfo:[{
                marketID:1,
                factoriesInfo:[{
                    factoriesID:1,
                    value:11
                },{
                    factoriesID:2,
                    value:21
                },{
                    factoriesID:3,
                    value:31
                },{
                    factoriesID:4,
                    value:41
                },{
                    factoriesID:5,
                    value:51
                }]
            },{
                marketID:2,
                factoriesInfo:[{
                    factoriesID:1,
                    value:16
                },{
                    factoriesID:2,
                    value:26
                },{
                    factoriesID:3,
                    value:36
                },{
                    factoriesID:4,
                    value:46
                },{
                    factoriesID:5,
                    value:56
                }]
            },{
                marketID:3,
                factoriesInfo:[{
                    factoriesID:1,
                    value:18
                },{
                    factoriesID:2,
                    value:28
                },{
                    factoriesID:3,
                    value:38
                },{
                    factoriesID:4,
                    value:48
                },{
                    factoriesID:5,
                    value:58
                }]
            }]
        },{
            categoryID:3,
            marketInfo:[{
                marketID:1,
                factoriesInfo:[{
                    factoriesID:1,
                    value:12
                },{
                    factoriesID:2,
                    value:22
                },{
                    factoriesID:3,
                    value:32
                },{
                    factoriesID:4,
                    value:42
                },{
                    factoriesID:5,
                    value:52
                }]
            },{
                marketID:2,
                factoriesInfo:[{
                    factoriesID:1,
                    value:13
                },{
                    factoriesID:2,
                    value:23
                },{
                    factoriesID:3,
                    value:33
                },{
                    factoriesID:4,
                    value:43
                },{
                    factoriesID:5,
                    value:53
                }]
            },{
                marketID:3,
                factoriesInfo:[{
                    factoriesID:1,
                    value:17
                },{
                    factoriesID:2,
                    value:27
                },{
                    factoriesID:3,
                    value:37
                },{
                    factoriesID:4,
                    value:47
                },{
                    factoriesID:5,
                    value:57
                }]
            }]
        }],
        rcrps_GrossContribution              : [{
            categoryID:1,
            marketInfo:[{
                marketID:1,
                factoriesInfo:[{
                    factoriesID:1,
                    value:10
                },{
                    factoriesID:2,
                    value:20
                },{
                    factoriesID:3,
                    value:30
                },{
                    factoriesID:4,
                    value:40
                },{
                    factoriesID:5,
                    value:50
                }]
            },{
                marketID:2,
                factoriesInfo:[{
                    factoriesID:1,
                    value:15
                },{
                    factoriesID:2,
                    value:25
                },{
                    factoriesID:3,
                    value:35
                },{
                    factoriesID:4,
                    value:45
                },{
                    factoriesID:5,
                    value:55
                }]
            },{
                marketID:3,
                factoriesInfo:[{
                    factoriesID:1,
                    value:19
                },{
                    factoriesID:2,
                    value:29
                },{
                    factoriesID:3,
                    value:39
                },{
                    factoriesID:4,
                    value:49
                },{
                    factoriesID:5,
                    value:59
                }]
            }]
        },{
            categoryID:2,
            marketInfo:[{
                marketID:1,
                factoriesInfo:[{
                    factoriesID:1,
                    value:11
                },{
                    factoriesID:2,
                    value:21
                },{
                    factoriesID:3,
                    value:31
                },{
                    factoriesID:4,
                    value:41
                },{
                    factoriesID:5,
                    value:51
                }]
            },{
                marketID:2,
                factoriesInfo:[{
                    factoriesID:1,
                    value:16
                },{
                    factoriesID:2,
                    value:26
                },{
                    factoriesID:3,
                    value:36
                },{
                    factoriesID:4,
                    value:46
                },{
                    factoriesID:5,
                    value:56
                }]
            },{
                marketID:3,
                factoriesInfo:[{
                    factoriesID:1,
                    value:18
                },{
                    factoriesID:2,
                    value:28
                },{
                    factoriesID:3,
                    value:38
                },{
                    factoriesID:4,
                    value:48
                },{
                    factoriesID:5,
                    value:58
                }]
            }]
        },{
            categoryID:3,
            marketInfo:[{
                marketID:1,
                factoriesInfo:[{
                    factoriesID:1,
                    value:12
                },{
                    factoriesID:2,
                    value:22
                },{
                    factoriesID:3,
                    value:32
                },{
                    factoriesID:4,
                    value:42
                },{
                    factoriesID:5,
                    value:52
                }]
            },{
                marketID:2,
                factoriesInfo:[{
                    factoriesID:1,
                    value:13
                },{
                    factoriesID:2,
                    value:23
                },{
                    factoriesID:3,
                    value:33
                },{
                    factoriesID:4,
                    value:43
                },{
                    factoriesID:5,
                    value:53
                }]
            },{
                marketID:3,
                factoriesInfo:[{
                    factoriesID:1,
                    value:17
                },{
                    factoriesID:2,
                    value:27
                },{
                    factoriesID:3,
                    value:37
                },{
                    factoriesID:4,
                    value:47
                },{
                    factoriesID:5,
                    value:57
                }]
            }]
        }],
        rcrps_GrossContributionPerShelfSpace : [{
            categoryID:1,
            marketInfo:[{
                marketID:1,
                factoriesInfo:[{
                    factoriesID:1,
                    value:10
                },{
                    factoriesID:2,
                    value:20
                },{
                    factoriesID:3,
                    value:30
                },{
                    factoriesID:4,
                    value:40
                },{
                    factoriesID:5,
                    value:50
                }]
            },{
                marketID:2,
                factoriesInfo:[{
                    factoriesID:1,
                    value:15
                },{
                    factoriesID:2,
                    value:25
                },{
                    factoriesID:3,
                    value:35
                },{
                    factoriesID:4,
                    value:45
                },{
                    factoriesID:5,
                    value:55
                }]
            },{
                marketID:3,
                factoriesInfo:[{
                    factoriesID:1,
                    value:19
                },{
                    factoriesID:2,
                    value:29
                },{
                    factoriesID:3,
                    value:39
                },{
                    factoriesID:4,
                    value:49
                },{
                    factoriesID:5,
                    value:59
                }]
            }]
        },{
            categoryID:2,
            marketInfo:[{
                marketID:1,
                factoriesInfo:[{
                    factoriesID:1,
                    value:11
                },{
                    factoriesID:2,
                    value:21
                },{
                    factoriesID:3,
                    value:31
                },{
                    factoriesID:4,
                    value:41
                },{
                    factoriesID:5,
                    value:51
                }]
            },{
                marketID:2,
                factoriesInfo:[{
                    factoriesID:1,
                    value:16
                },{
                    factoriesID:2,
                    value:26
                },{
                    factoriesID:3,
                    value:36
                },{
                    factoriesID:4,
                    value:46
                },{
                    factoriesID:5,
                    value:56
                }]
            },{
                marketID:3,
                factoriesInfo:[{
                    factoriesID:1,
                    value:18
                },{
                    factoriesID:2,
                    value:28
                },{
                    factoriesID:3,
                    value:38
                },{
                    factoriesID:4,
                    value:48
                },{
                    factoriesID:5,
                    value:58
                }]
            }]
        },{
            categoryID:3,
            marketInfo:[{
                marketID:1,
                factoriesInfo:[{
                    factoriesID:1,
                    value:12
                },{
                    factoriesID:2,
                    value:22
                },{
                    factoriesID:3,
                    value:32
                },{
                    factoriesID:4,
                    value:42
                },{
                    factoriesID:5,
                    value:52
                }]
            },{
                marketID:2,
                factoriesInfo:[{
                    factoriesID:1,
                    value:13
                },{
                    factoriesID:2,
                    value:23
                },{
                    factoriesID:3,
                    value:33
                },{
                    factoriesID:4,
                    value:43
                },{
                    factoriesID:5,
                    value:53
                }]
            },{
                marketID:3,
                factoriesInfo:[{
                    factoriesID:1,
                    value:17
                },{
                    factoriesID:2,
                    value:27
                },{
                    factoriesID:3,
                    value:37
                },{
                    factoriesID:4,
                    value:47
                },{
                    factoriesID:5,
                    value:57
                }]
            }]
        }],
        rcrps_GrossContributionMargin        : [{
            categoryID:1,
            marketInfo:[{
                marketID:1,
                factoriesInfo:[{
                    factoriesID:1,
                    value:10
                },{
                    factoriesID:2,
                    value:20
                },{
                    factoriesID:3,
                    value:30
                },{
                    factoriesID:4,
                    value:40
                },{
                    factoriesID:5,
                    value:50
                }]
            },{
                marketID:2,
                factoriesInfo:[{
                    factoriesID:1,
                    value:15
                },{
                    factoriesID:2,
                    value:25
                },{
                    factoriesID:3,
                    value:35
                },{
                    factoriesID:4,
                    value:45
                },{
                    factoriesID:5,
                    value:55
                }]
            },{
                marketID:3,
                factoriesInfo:[{
                    factoriesID:1,
                    value:19
                },{
                    factoriesID:2,
                    value:29
                },{
                    factoriesID:3,
                    value:39
                },{
                    factoriesID:4,
                    value:49
                },{
                    factoriesID:5,
                    value:59
                }]
            }]
        },{
            categoryID:2,
            marketInfo:[{
                marketID:1,
                factoriesInfo:[{
                    factoriesID:1,
                    value:11
                },{
                    factoriesID:2,
                    value:21
                },{
                    factoriesID:3,
                    value:31
                },{
                    factoriesID:4,
                    value:41
                },{
                    factoriesID:5,
                    value:51
                }]
            },{
                marketID:2,
                factoriesInfo:[{
                    factoriesID:1,
                    value:16
                },{
                    factoriesID:2,
                    value:26
                },{
                    factoriesID:3,
                    value:36
                },{
                    factoriesID:4,
                    value:46
                },{
                    factoriesID:5,
                    value:56
                }]
            },{
                marketID:3,
                factoriesInfo:[{
                    factoriesID:1,
                    value:18
                },{
                    factoriesID:2,
                    value:28
                },{
                    factoriesID:3,
                    value:38
                },{
                    factoriesID:4,
                    value:48
                },{
                    factoriesID:5,
                    value:58
                }]
            }]
        },{
            categoryID:3,
            marketInfo:[{
                marketID:1,
                factoriesInfo:[{
                    factoriesID:1,
                    value:12
                },{
                    factoriesID:2,
                    value:22
                },{
                    factoriesID:3,
                    value:32
                },{
                    factoriesID:4,
                    value:42
                },{
                    factoriesID:5,
                    value:52
                }]
            },{
                marketID:2,
                factoriesInfo:[{
                    factoriesID:1,
                    value:13
                },{
                    factoriesID:2,
                    value:23
                },{
                    factoriesID:3,
                    value:33
                },{
                    factoriesID:4,
                    value:43
                },{
                    factoriesID:5,
                    value:53
                }]
            },{
                marketID:3,
                factoriesInfo:[{
                    factoriesID:1,
                    value:17
                },{
                    factoriesID:2,
                    value:27
                },{
                    factoriesID:3,
                    value:37
                },{
                    factoriesID:4,
                    value:47
                },{
                    factoriesID:5,
                    value:57
                }]
            }]
        }],
        rcrps_GrossContributionShare         : [{
            categoryID:1,
            marketInfo:[{
                marketID:1,
                factoriesInfo:[{
                    factoriesID:1,
                    value:10
                },{
                    factoriesID:2,
                    value:20
                },{
                    factoriesID:3,
                    value:30
                },{
                    factoriesID:4,
                    value:40
                },{
                    factoriesID:5,
                    value:50
                }]
            },{
                marketID:2,
                factoriesInfo:[{
                    factoriesID:1,
                    value:15
                },{
                    factoriesID:2,
                    value:25
                },{
                    factoriesID:3,
                    value:35
                },{
                    factoriesID:4,
                    value:45
                },{
                    factoriesID:5,
                    value:55
                }]
            },{
                marketID:3,
                factoriesInfo:[{
                    factoriesID:1,
                    value:19
                },{
                    factoriesID:2,
                    value:29
                },{
                    factoriesID:3,
                    value:39
                },{
                    factoriesID:4,
                    value:49
                },{
                    factoriesID:5,
                    value:59
                }]
            }]
        },{
            categoryID:2,
            marketInfo:[{
                marketID:1,
                factoriesInfo:[{
                    factoriesID:1,
                    value:11
                },{
                    factoriesID:2,
                    value:21
                },{
                    factoriesID:3,
                    value:31
                },{
                    factoriesID:4,
                    value:41
                },{
                    factoriesID:5,
                    value:51
                }]
            },{
                marketID:2,
                factoriesInfo:[{
                    factoriesID:1,
                    value:16
                },{
                    factoriesID:2,
                    value:26
                },{
                    factoriesID:3,
                    value:36
                },{
                    factoriesID:4,
                    value:46
                },{
                    factoriesID:5,
                    value:56
                }]
            },{
                marketID:3,
                factoriesInfo:[{
                    factoriesID:1,
                    value:18
                },{
                    factoriesID:2,
                    value:28
                },{
                    factoriesID:3,
                    value:38
                },{
                    factoriesID:4,
                    value:48
                },{
                    factoriesID:5,
                    value:58
                }]
            }]
        },{
            categoryID:3,
            marketInfo:[{
                marketID:1,
                factoriesInfo:[{
                    factoriesID:1,
                    value:12
                },{
                    factoriesID:2,
                    value:22
                },{
                    factoriesID:3,
                    value:32
                },{
                    factoriesID:4,
                    value:42
                },{
                    factoriesID:5,
                    value:52
                }]
            },{
                marketID:2,
                factoriesInfo:[{
                    factoriesID:1,
                    value:13
                },{
                    factoriesID:2,
                    value:23
                },{
                    factoriesID:3,
                    value:33
                },{
                    factoriesID:4,
                    value:43
                },{
                    factoriesID:5,
                    value:53
                }]
            },{
                marketID:3,
                factoriesInfo:[{
                    factoriesID:1,
                    value:17
                },{
                    factoriesID:2,
                    value:27
                },{
                    factoriesID:3,
                    value:37
                },{
                    factoriesID:4,
                    value:47
                },{
                    factoriesID:5,
                    value:57
                }]
            }]
        }],
        rcrps_PaymentTerms                   : [{
            categoryID:1,
            marketInfo:[{
                marketID:1,
                factoriesInfo:[{
                    factoriesID:1,
                    value:10
                },{
                    factoriesID:2,
                    value:20
                },{
                    factoriesID:3,
                    value:30
                },{
                    factoriesID:4,
                    value:40
                },{
                    factoriesID:5,
                    value:50
                }]
            },{
                marketID:2,
                factoriesInfo:[{
                    factoriesID:1,
                    value:15
                },{
                    factoriesID:2,
                    value:25
                },{
                    factoriesID:3,
                    value:35
                },{
                    factoriesID:4,
                    value:45
                },{
                    factoriesID:5,
                    value:55
                }]
            },{
                marketID:3,
                factoriesInfo:[{
                    factoriesID:1,
                    value:19
                },{
                    factoriesID:2,
                    value:29
                },{
                    factoriesID:3,
                    value:39
                },{
                    factoriesID:4,
                    value:49
                },{
                    factoriesID:5,
                    value:59
                }]
            }]
        },{
            categoryID:2,
            marketInfo:[{
                marketID:1,
                factoriesInfo:[{
                    factoriesID:1,
                    value:11
                },{
                    factoriesID:2,
                    value:21
                },{
                    factoriesID:3,
                    value:31
                },{
                    factoriesID:4,
                    value:41
                },{
                    factoriesID:5,
                    value:51
                }]
            },{
                marketID:2,
                factoriesInfo:[{
                    factoriesID:1,
                    value:16
                },{
                    factoriesID:2,
                    value:26
                },{
                    factoriesID:3,
                    value:36
                },{
                    factoriesID:4,
                    value:46
                },{
                    factoriesID:5,
                    value:56
                }]
            },{
                marketID:3,
                factoriesInfo:[{
                    factoriesID:1,
                    value:18
                },{
                    factoriesID:2,
                    value:28
                },{
                    factoriesID:3,
                    value:38
                },{
                    factoriesID:4,
                    value:48
                },{
                    factoriesID:5,
                    value:58
                }]
            }]
        },{
            categoryID:3,
            marketInfo:[{
                marketID:1,
                factoriesInfo:[{
                    factoriesID:1,
                    value:12
                },{
                    factoriesID:2,
                    value:22
                },{
                    factoriesID:3,
                    value:32
                },{
                    factoriesID:4,
                    value:42
                },{
                    factoriesID:5,
                    value:52
                }]
            },{
                marketID:2,
                factoriesInfo:[{
                    factoriesID:1,
                    value:13
                },{
                    factoriesID:2,
                    value:23
                },{
                    factoriesID:3,
                    value:33
                },{
                    factoriesID:4,
                    value:43
                },{
                    factoriesID:5,
                    value:53
                }]
            },{
                marketID:3,
                factoriesInfo:[{
                    factoriesID:1,
                    value:17
                },{
                    factoriesID:2,
                    value:27
                },{
                    factoriesID:3,
                    value:37
                },{
                    factoriesID:4,
                    value:47
                },{
                    factoriesID:5,
                    value:57
                }]
            }]
        }]
    });
    newRCR_profitabilityBySupplier.save(function(err) {
        if(!err){
            res.send(200,newRCR_profitabilityBySupplier);
            console.log("created new GeneralReport:"+newRCR_profitabilityBySupplier);
        } else {
            res.send(400,"failed.");
        }
    }); 
}

exports.getRCR_profitabilityBySupplier=function(req,res,next){
    var data={
        'seminar':req.params.seminar,
        'period':req.params.period,
        'retailerID':req.params.retailerID
    };
    RCR_profitabilityBySupplier.find(data,function(err,docs){
        if(docs){
            res.send(200,docs);
        }else{
            res.send(404,'failed');
        }
    })    
}
