var mongoose = require('mongoose'),
	http = require('http'),
	util = require('util'),
	_ = require('underscore'),
	request = require('request'),
	q = require('q');

//TActiveActors : 1~(3+2)
//TActors : 1~(4+3)
// new schema, 2014-Apr-17:
var SCR_sharesCrossSegmentSchema = mongoose.Schema({
    period : Number,
    seminar : String,
    producerID  : Number, //TAllProducer : 1~4 (ProsMaxPlus)
    absoluteValue     : [variantCrossSegmentDetailSchema],
    valueChange       : [variantCrossSegmentDetailSchema],
    absoluteVolume    : [variantCrossSegmentDetailSchema],
    volumeChange      : [variantCrossSegmentDetailSchema],
})

var variantCrossSegmentDetailSchema = mongoose.Schema({
    variantName       : String,
    parentBrandName   : String,
    parentCategoryID  : Number,
    marketID : Number,
    segmentInfo : [segmentInfoSchema]
})

var segmentInfoSchema = mongoose.Schema({
    segmentID : Number, //TSegmentsTotal : 1~(4+1),
    /*
        Elecssories:
        1-PriceSensitive
        2-Value for Money
        3-Fashion
        4-Freaks
        5-Total

        HealthBeauties:
        1-PriceSensitive
        2-Value for Money
        3-Health Conscious
        4-Impatient      
        5-Total
    */
    shopperInfo : [shopperInfoSchema]
})

var shopperInfoSchema = mongoose.Schema({
    shoperKind : String, // BMS, NETIZENS, MIXED, ALLSHOPPERS
    value : Number
})


var SCR_sharesCrossSegment=mongoose.model('SCR_sharesCrossSegment',SCR_sharesCrossSegmentSchema);

exports.addReports = function(options){
    var deferred = q.defer();
    var startFrom = options.startFrom,
    endWith = options.endWith;

   (function sendRequest(currentPeriod){        
      var reqOptions = {
          hostname: options.cgiHost,
          port: options.cgiPort,
          path: options.cgiPath + '?period=' + currentPeriod + '&seminar=' + options.seminar + '&producerID=' + options.producerID
      };

      http.get(reqOptions, function(response) { 
        var data = '';
        response.setEncoding('utf8');
        response.on('data', function(chunk){
          data += chunk;
        }).on('end', function(){
          //ask Oleg to fix here, should return 404 when result beyound the existed period.
          //console.log('response statusCode from CGI(' + options.cgiPath + ') for period ' + currentPeriod + ': ' + response.statusCode);
          if ( response.statusCode === (404 || 500) ) 
            deferred.reject({msg:'Get 404||500 error from CGI server, reqOptions:' + JSON.stringify(reqOptions)});
          else {
            try {
              var singleReport = JSON.parse(data);
            } catch(e) {
              deferred.reject({msg: 'cannot parse JSON data from CGI:' + data, options:options});
            }
          }      
          if (!singleReport) return; 
         // console.log(util.inspect(singleReport, {depth:null}));

          SCR_sharesCrossSegment.update({seminar    : singleReport.seminar, 
                                            period     : singleReport.period,
                                            producerID : singleReport.producerID},
                                {
                                absoluteValue     : singleReport.absoluteValue,
                                valueChange       : singleReport.valueChange,   
                                absoluteVolume    : singleReport.absoluteVolume,
                                volumeChange      : singleReport.volumeChange,  
                                },
                                {upsert: true},
                                function(err, numberAffected, raw){
                                  if(err) deferred.reject({msg:err, options: options});                                  
                                  currentPeriod--;
                                  if (currentPeriod >= startFrom) {
                                     sendRequest(currentPeriod);
                                  } else {
                                     deferred.resolve({msg: options.schemaName + ' (seminar:' + options.seminar + ', producer:' + options.producerID+ ') import done. from period ' + startFrom + ' to ' + endWith, options: options});
                                  }
                                });   

        });
      }).on('error', function(e){
        deferred.reject({msg:'errorFrom add ' + options.schemaName + ': ' + e.message + ', requestOptions:' + JSON.stringify(reqOptions),options: options});
      });
    })(endWith);

    return deferred.promise;
}



exports.addSCR_sharesCrossSegment=function(req,res,next){
    var newSCR_sharesCrossSegment=SCR_sharesCrossSegment({
        period : 0,
        seminar : 'MAY',
        producerID  : 1, //TAllProducer : 1~4 (ProsMaxPlus)
        absoluteValue     : [{
            variantName:'_A',
            parentBrandName:'ELAN1',
            parentCategoryID:1,
            marketID:1,
            segmentInfo:[{
                segmentID:1,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            },{
                segmentID:2,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:50
                },{
                    shoperKind:'NETIZENS',
                    value:60
                },{
                    shoperKind:'MIXED',
                    value:70
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:80
                }]
            },{
                segmentID:3,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            },{
                segmentID:4,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:50
                },{
                    shoperKind:'NETIZENS',
                    value:60
                },{
                    shoperKind:'MIXED',
                    value:70
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:80
                }]
            },{
                segmentID:5,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            }]
        },{
            variantName:'_B',
            parentBrandName:'HLAN1',
            parentCategoryID:2,
            marketID:1,
            segmentInfo:[{
                segmentID:1,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            },{
                segmentID:2,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:50
                },{
                    shoperKind:'NETIZENS',
                    value:60
                },{
                    shoperKind:'MIXED',
                    value:70
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:80
                }]
            },{
                segmentID:3,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            },{
                segmentID:4,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:50
                },{
                    shoperKind:'NETIZENS',
                    value:60
                },{
                    shoperKind:'MIXED',
                    value:70
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:80
                }]
            },{
                segmentID:5,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            }]
        },{
            variantName:'_A',
            parentBrandName:'ELAN1',
            parentCategoryID:1,
            marketID:2,
            segmentInfo:[{
                segmentID:1,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            },{
                segmentID:2,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:50
                },{
                    shoperKind:'NETIZENS',
                    value:60
                },{
                    shoperKind:'MIXED',
                    value:70
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:80
                }]
            },{
                segmentID:3,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            },{
                segmentID:4,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:50
                },{
                    shoperKind:'NETIZENS',
                    value:60
                },{
                    shoperKind:'MIXED',
                    value:70
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:80
                }]
            },{
                segmentID:5,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            }]
        },{
            variantName:'_B',
            parentBrandName:'HLAN1',
            parentCategoryID:2,
            marketID:2,
            segmentInfo:[{
                segmentID:1,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            },{
                segmentID:2,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:50
                },{
                    shoperKind:'NETIZENS',
                    value:60
                },{
                    shoperKind:'MIXED',
                    value:70
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:80
                }]
            },{
                segmentID:3,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            },{
                segmentID:4,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:50
                },{
                    shoperKind:'NETIZENS',
                    value:60
                },{
                    shoperKind:'MIXED',
                    value:70
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:80
                }]
            },{
                segmentID:5,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            }]
        }],
        valueChange       : [{
            variantName:'_A',
            parentBrandName:'ELAN1',
            parentCategoryID:1,
            marketID:1,
            segmentInfo:[{
                segmentID:1,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            },{
                segmentID:2,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:50
                },{
                    shoperKind:'NETIZENS',
                    value:60
                },{
                    shoperKind:'MIXED',
                    value:70
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:80
                }]
            },{
                segmentID:3,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            },{
                segmentID:4,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:50
                },{
                    shoperKind:'NETIZENS',
                    value:60
                },{
                    shoperKind:'MIXED',
                    value:70
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:80
                }]
            },{
                segmentID:5,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            }]
        },{
            variantName:'_B',
            parentBrandName:'HLAN1',
            parentCategoryID:2,
            marketID:1,
            segmentInfo:[{
                segmentID:1,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            },{
                segmentID:2,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:50
                },{
                    shoperKind:'NETIZENS',
                    value:60
                },{
                    shoperKind:'MIXED',
                    value:70
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:80
                }]
            },{
                segmentID:3,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            },{
                segmentID:4,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:50
                },{
                    shoperKind:'NETIZENS',
                    value:60
                },{
                    shoperKind:'MIXED',
                    value:70
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:80
                }]
            },{
                segmentID:5,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            }]
        },{
            variantName:'_A',
            parentBrandName:'ELAN1',
            parentCategoryID:1,
            marketID:2,
            segmentInfo:[{
                segmentID:1,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            },{
                segmentID:2,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:50
                },{
                    shoperKind:'NETIZENS',
                    value:60
                },{
                    shoperKind:'MIXED',
                    value:70
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:80
                }]
            },{
                segmentID:3,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            },{
                segmentID:4,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:50
                },{
                    shoperKind:'NETIZENS',
                    value:60
                },{
                    shoperKind:'MIXED',
                    value:70
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:80
                }]
            },{
                segmentID:5,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            }]
        },{
            variantName:'_B',
            parentBrandName:'HLAN1',
            parentCategoryID:2,
            marketID:2,
            segmentInfo:[{
                segmentID:1,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            },{
                segmentID:2,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:50
                },{
                    shoperKind:'NETIZENS',
                    value:60
                },{
                    shoperKind:'MIXED',
                    value:70
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:80
                }]
            },{
                segmentID:3,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            },{
                segmentID:4,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:50
                },{
                    shoperKind:'NETIZENS',
                    value:60
                },{
                    shoperKind:'MIXED',
                    value:70
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:80
                }]
            },{
                segmentID:5,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            }]
        }],
        absoluteVolume    : [{
            variantName:'_A',
            parentBrandName:'ELAN1',
            parentCategoryID:1,
            marketID:1,
            segmentInfo:[{
                segmentID:1,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            },{
                segmentID:2,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:50
                },{
                    shoperKind:'NETIZENS',
                    value:60
                },{
                    shoperKind:'MIXED',
                    value:70
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:80
                }]
            },{
                segmentID:3,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            },{
                segmentID:4,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:50
                },{
                    shoperKind:'NETIZENS',
                    value:60
                },{
                    shoperKind:'MIXED',
                    value:70
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:80
                }]
            },{
                segmentID:5,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            }]
        },{
            variantName:'_B',
            parentBrandName:'HLAN1',
            parentCategoryID:2,
            marketID:1,
            segmentInfo:[{
                segmentID:1,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            },{
                segmentID:2,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:50
                },{
                    shoperKind:'NETIZENS',
                    value:60
                },{
                    shoperKind:'MIXED',
                    value:70
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:80
                }]
            },{
                segmentID:3,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            },{
                segmentID:4,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:50
                },{
                    shoperKind:'NETIZENS',
                    value:60
                },{
                    shoperKind:'MIXED',
                    value:70
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:80
                }]
            },{
                segmentID:5,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            }]
        },{
            variantName:'_A',
            parentBrandName:'ELAN1',
            parentCategoryID:1,
            marketID:2,
            segmentInfo:[{
                segmentID:1,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            },{
                segmentID:2,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:50
                },{
                    shoperKind:'NETIZENS',
                    value:60
                },{
                    shoperKind:'MIXED',
                    value:70
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:80
                }]
            },{
                segmentID:3,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            },{
                segmentID:4,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:50
                },{
                    shoperKind:'NETIZENS',
                    value:60
                },{
                    shoperKind:'MIXED',
                    value:70
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:80
                }]
            },{
                segmentID:5,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            }]
        },{
            variantName:'_B',
            parentBrandName:'HLAN1',
            parentCategoryID:2,
            marketID:2,
            segmentInfo:[{
                segmentID:1,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            },{
                segmentID:2,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:50
                },{
                    shoperKind:'NETIZENS',
                    value:60
                },{
                    shoperKind:'MIXED',
                    value:70
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:80
                }]
            },{
                segmentID:3,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            },{
                segmentID:4,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:50
                },{
                    shoperKind:'NETIZENS',
                    value:60
                },{
                    shoperKind:'MIXED',
                    value:70
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:80
                }]
            },{
                segmentID:5,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            }]
        }],
        volumeChange      : [{
            variantName:'_A',
            parentBrandName:'ELAN1',
            parentCategoryID:1,
            marketID:1,
            segmentInfo:[{
                segmentID:1,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            },{
                segmentID:2,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:50
                },{
                    shoperKind:'NETIZENS',
                    value:60
                },{
                    shoperKind:'MIXED',
                    value:70
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:80
                }]
            },{
                segmentID:3,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            },{
                segmentID:4,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:50
                },{
                    shoperKind:'NETIZENS',
                    value:60
                },{
                    shoperKind:'MIXED',
                    value:70
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:80
                }]
            },{
                segmentID:5,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            }]
        },{
            variantName:'_B',
            parentBrandName:'HLAN1',
            parentCategoryID:2,
            marketID:1,
            segmentInfo:[{
                segmentID:1,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            },{
                segmentID:2,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:50
                },{
                    shoperKind:'NETIZENS',
                    value:60
                },{
                    shoperKind:'MIXED',
                    value:70
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:80
                }]
            },{
                segmentID:3,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            },{
                segmentID:4,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:50
                },{
                    shoperKind:'NETIZENS',
                    value:60
                },{
                    shoperKind:'MIXED',
                    value:70
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:80
                }]
            },{
                segmentID:5,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            }]
        },{
            variantName:'_A',
            parentBrandName:'ELAN1',
            parentCategoryID:1,
            marketID:2,
            segmentInfo:[{
                segmentID:1,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            },{
                segmentID:2,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:50
                },{
                    shoperKind:'NETIZENS',
                    value:60
                },{
                    shoperKind:'MIXED',
                    value:70
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:80
                }]
            },{
                segmentID:3,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            },{
                segmentID:4,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:50
                },{
                    shoperKind:'NETIZENS',
                    value:60
                },{
                    shoperKind:'MIXED',
                    value:70
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:80
                }]
            },{
                segmentID:5,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            }]
        },{
            variantName:'_B',
            parentBrandName:'HLAN1',
            parentCategoryID:2,
            marketID:2,
            segmentInfo:[{
                segmentID:1,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            },{
                segmentID:2,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:50
                },{
                    shoperKind:'NETIZENS',
                    value:60
                },{
                    shoperKind:'MIXED',
                    value:70
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:80
                }]
            },{
                segmentID:3,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            },{
                segmentID:4,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:50
                },{
                    shoperKind:'NETIZENS',
                    value:60
                },{
                    shoperKind:'MIXED',
                    value:70
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:80
                }]
            },{
                segmentID:5,
                shopperInfo:[{
                    shoperKind:'BMS',
                    value:10
                },{
                    shoperKind:'NETIZENS',
                    value:20
                },{
                    shoperKind:'MIXED',
                    value:30
                },{
                    shoperKind:'ALLSHOPPERS',
                    value:40
                }]
            }]
        }]
    });
    newSCR_sharesCrossSegment.save(function(err) {
        if(!err){
            res.send(200,newSCR_sharesCrossSegment);
            console.log("created new GeneralReport:"+newSCR_sharesCrossSegment);
        } else {
            res.send(400,"failed.");
        }
    });  
}

exports.getSCR_sharesCrossSegment=function(req,res,next){
    var data={
        'seminar':req.params.seminar,
        'period':req.params.period,
        'producerID':req.params.producerID
    };
    SCR_sharesCrossSegment.find(data,function(err,docs){
        if(docs){
            res.send(200,docs);
        }else{
            res.send(404,'failed');
        }
    })  
}
