var mongoose = require('mongoose'),
	http = require('http'),
	util = require('util'),
	_ = require('underscore'),
	request = require('request'),
	q = require('q');

//TActiveActors : 1~(3+2)
//TActors : 1~(4+3)

var SCR_sharesCrossSegmentSchema = mongoose.Schema({
    period : Number,
    seminar : String,
    producerID  : Number, //TAllProducer : 1~4 (ProsMaxPlus)
    absoluteValue     : [variantInfoSchema],
    valueChange       : [variantInfoSchema],
    absoluteVolume    : [variantInfoSchema],
    volumeChange      : [variantInfoSchema],
})

var variantInfoSchema = mongoose.Schema({
    variantName       : String,
    parentBrandName   : String,
    parentCategoryID  : Number,
    marketInfo: [marketInfoSchema]
})

var marketInfoSchema = mongoose.Schema({
    marketID : Number, //TMarkets : 1~2
    segmentInfo : [segmentInfoSchema]
})

var segmentInfoSchema = mongoose.Schema({
    segmentID : Number, //TSegmentsTotal : 1~(4+1),
    /*
        Elecssories:
        1-PriceSensitive
        2-Value for Money
        3-Fashion
        4-Freaks
        5-Total

        HealthBeauties:
        1-PriceSensitive
        2-Value for Money
        3-Health Conscious
        4-Impatient      
        5-Total
    */
    shopperInfo : [shopperInfoSchema]
})

var shopperInfoSchema = mongoose.Schema({
    shoperKind : String, // BMS, NETIZENS, MIXED, ALLSHOPPERS
    value : Number
})

// new schema, 2014-Apr-17:
// var SCR_sharesCrossSegmentSchema = mongoose.Schema({
//     period : Number,
//     seminar : String,
//     producerID  : Number, //TAllProducer : 1~4 (ProsMaxPlus)
//     absoluteValue     : [variantCrossSegmentDetailSchema],
//     valueChange       : [variantCrossSegmentDetailSchema],
//     absoluteVolume    : [variantCrossSegmentDetailSchema],
//     volumeChange      : [variantCrossSegmentDetailSchema],
// })

// var variantCrossSegmentDetailSchema = mongoose.Schema({
//     variantName       : String,
//     parentBrandName   : String,
//     parentCategoryID  : Number,
//     marketID : Number,
//     segmentInfo : [segmentInfoSchema]
// })

// var segmentInfoSchema = mongoose.Schema({
//     segmentID : Number, //TSegmentsTotal : 1~(4+1),
//     /*
//         Elecssories:
//         1-PriceSensitive
//         2-Value for Money
//         3-Fashion
//         4-Freaks
//         5-Total

//         HealthBeauties:
//         1-PriceSensitive
//         2-Value for Money
//         3-Health Conscious
//         4-Impatient      
//         5-Total
//     */
//     shopperInfo : [shopperInfoSchema]
// })

// var shopperInfoSchema = mongoose.Schema({
//     shoperKind : String, // BMS, NETIZENS, MIXED, ALLSHOPPERS
//     value : Number
// })


var SCR_sharesCrossSegment=mongoose.model('SCR_sharesCrossSegment',SCR_sharesCrossSegmentSchema);

exports.addSCR_sharesCrossSegment=function(req,res,next){
    var newSCR_sharesCrossSegment=SCR_sharesCrossSegment({
        period : 0,
        seminar : 'MAY',
        producerID  : 1, //TAllProducer : 1~4 (ProsMaxPlus)
        absoluteValue     : [{
            variantName:'_A',
            parentBrandName:'ELAN1',
            parentCategoryID:1,
            marketInfo:[{
                marketID:1,
                segmentInfo:[{
                    segmentID:1,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                },{
                    segmentID:2,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:50
                    },{
                        shoperKind:'NETIZENS',
                        value:60
                    },{
                        shoperKind:'MIXED',
                        value:70
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:80
                    }]
                },{
                    segmentID:3,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                },{
                    segmentID:4,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:50
                    },{
                        shoperKind:'NETIZENS',
                        value:60
                    },{
                        shoperKind:'MIXED',
                        value:70
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:80
                    }]
                },{
                    segmentID:5,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                }]
            },{
                marketID:2,
                segmentInfo:[{
                    segmentID:1,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                },{
                    segmentID:2,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:50
                    },{
                        shoperKind:'NETIZENS',
                        value:60
                    },{
                        shoperKind:'MIXED',
                        value:70
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:80
                    }]
                },{
                    segmentID:3,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                },{
                    segmentID:4,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:50
                    },{
                        shoperKind:'NETIZENS',
                        value:60
                    },{
                        shoperKind:'MIXED',
                        value:70
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:80
                    }]
                },{
                    segmentID:5,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                }]
            }]
        },{
            variantName:'_B',
            parentBrandName:'HLAN1',
            parentCategoryID:2,
            marketInfo:[{
                marketID:1,
                segmentInfo:[{
                    segmentID:1,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                },{
                    segmentID:2,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:50
                    },{
                        shoperKind:'NETIZENS',
                        value:60
                    },{
                        shoperKind:'MIXED',
                        value:70
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:80
                    }]
                },{
                    segmentID:3,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                },{
                    segmentID:4,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:50
                    },{
                        shoperKind:'NETIZENS',
                        value:60
                    },{
                        shoperKind:'MIXED',
                        value:70
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:80
                    }]
                },{
                    segmentID:5,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                }]
            },{
                marketID:2,
                segmentInfo:[{
                    segmentID:1,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                },{
                    segmentID:2,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:50
                    },{
                        shoperKind:'NETIZENS',
                        value:60
                    },{
                        shoperKind:'MIXED',
                        value:70
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:80
                    }]
                },{
                    segmentID:3,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                },{
                    segmentID:4,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:50
                    },{
                        shoperKind:'NETIZENS',
                        value:60
                    },{
                        shoperKind:'MIXED',
                        value:70
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:80
                    }]
                },{
                    segmentID:5,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                }]
            }]
        }],
        valueChange       : [{
            variantName:'_A',
            parentBrandName:'ELAN1',
            parentCategoryID:1,
            marketInfo:[{
                marketID:1,
                segmentInfo:[{
                    segmentID:1,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                },{
                    segmentID:2,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:50
                    },{
                        shoperKind:'NETIZENS',
                        value:60
                    },{
                        shoperKind:'MIXED',
                        value:70
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:80
                    }]
                },{
                    segmentID:3,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                },{
                    segmentID:4,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:50
                    },{
                        shoperKind:'NETIZENS',
                        value:60
                    },{
                        shoperKind:'MIXED',
                        value:70
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:80
                    }]
                },{
                    segmentID:5,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                }]
            },{
                marketID:2,
                segmentInfo:[{
                    segmentID:1,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                },{
                    segmentID:2,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:50
                    },{
                        shoperKind:'NETIZENS',
                        value:60
                    },{
                        shoperKind:'MIXED',
                        value:70
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:80
                    }]
                },{
                    segmentID:3,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                },{
                    segmentID:4,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:50
                    },{
                        shoperKind:'NETIZENS',
                        value:60
                    },{
                        shoperKind:'MIXED',
                        value:70
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:80
                    }]
                },{
                    segmentID:5,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                }]
            }]
        },{
            variantName:'_B',
            parentBrandName:'HLAN1',
            parentCategoryID:2,
            marketInfo:[{
                marketID:1,
                segmentInfo:[{
                    segmentID:1,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                },{
                    segmentID:2,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:50
                    },{
                        shoperKind:'NETIZENS',
                        value:60
                    },{
                        shoperKind:'MIXED',
                        value:70
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:80
                    }]
                },{
                    segmentID:3,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                },{
                    segmentID:4,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:50
                    },{
                        shoperKind:'NETIZENS',
                        value:60
                    },{
                        shoperKind:'MIXED',
                        value:70
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:80
                    }]
                },{
                    segmentID:5,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                }]
            },{
                marketID:2,
                segmentInfo:[{
                    segmentID:1,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                },{
                    segmentID:2,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:50
                    },{
                        shoperKind:'NETIZENS',
                        value:60
                    },{
                        shoperKind:'MIXED',
                        value:70
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:80
                    }]
                },{
                    segmentID:3,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                },{
                    segmentID:4,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:50
                    },{
                        shoperKind:'NETIZENS',
                        value:60
                    },{
                        shoperKind:'MIXED',
                        value:70
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:80
                    }]
                },{
                    segmentID:5,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                }]
            }]
        }],
        absoluteVolume    : [{
            variantName:'_A',
            parentBrandName:'ELAN1',
            parentCategoryID:1,
            marketInfo:[{
                marketID:1,
                segmentInfo:[{
                    segmentID:1,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                },{
                    segmentID:2,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:50
                    },{
                        shoperKind:'NETIZENS',
                        value:60
                    },{
                        shoperKind:'MIXED',
                        value:70
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:80
                    }]
                },{
                    segmentID:3,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                },{
                    segmentID:4,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:50
                    },{
                        shoperKind:'NETIZENS',
                        value:60
                    },{
                        shoperKind:'MIXED',
                        value:70
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:80
                    }]
                },{
                    segmentID:5,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                }]
            },{
                marketID:2,
                segmentInfo:[{
                    segmentID:1,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                },{
                    segmentID:2,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:50
                    },{
                        shoperKind:'NETIZENS',
                        value:60
                    },{
                        shoperKind:'MIXED',
                        value:70
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:80
                    }]
                },{
                    segmentID:3,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                },{
                    segmentID:4,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:50
                    },{
                        shoperKind:'NETIZENS',
                        value:60
                    },{
                        shoperKind:'MIXED',
                        value:70
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:80
                    }]
                },{
                    segmentID:5,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                }]
            }]
        },{
            variantName:'_B',
            parentBrandName:'HLAN1',
            parentCategoryID:2,
            marketInfo:[{
                marketID:1,
                segmentInfo:[{
                    segmentID:1,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                },{
                    segmentID:2,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:50
                    },{
                        shoperKind:'NETIZENS',
                        value:60
                    },{
                        shoperKind:'MIXED',
                        value:70
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:80
                    }]
                },{
                    segmentID:3,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                },{
                    segmentID:4,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:50
                    },{
                        shoperKind:'NETIZENS',
                        value:60
                    },{
                        shoperKind:'MIXED',
                        value:70
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:80
                    }]
                },{
                    segmentID:5,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                }]
            },{
                marketID:2,
                segmentInfo:[{
                    segmentID:1,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                },{
                    segmentID:2,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:50
                    },{
                        shoperKind:'NETIZENS',
                        value:60
                    },{
                        shoperKind:'MIXED',
                        value:70
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:80
                    }]
                },{
                    segmentID:3,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                },{
                    segmentID:4,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:50
                    },{
                        shoperKind:'NETIZENS',
                        value:60
                    },{
                        shoperKind:'MIXED',
                        value:70
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:80
                    }]
                },{
                    segmentID:5,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                }]
            }]
        }],
        volumeChange      : [{
            variantName:'_A',
            parentBrandName:'ELAN1',
            parentCategoryID:1,
            marketInfo:[{
                marketID:1,
                segmentInfo:[{
                    segmentID:1,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                },{
                    segmentID:2,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:50
                    },{
                        shoperKind:'NETIZENS',
                        value:60
                    },{
                        shoperKind:'MIXED',
                        value:70
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:80
                    }]
                },{
                    segmentID:3,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                },{
                    segmentID:4,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:50
                    },{
                        shoperKind:'NETIZENS',
                        value:60
                    },{
                        shoperKind:'MIXED',
                        value:70
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:80
                    }]
                },{
                    segmentID:5,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                }]
            },{
                marketID:2,
                segmentInfo:[{
                    segmentID:1,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                },{
                    segmentID:2,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:50
                    },{
                        shoperKind:'NETIZENS',
                        value:60
                    },{
                        shoperKind:'MIXED',
                        value:70
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:80
                    }]
                },{
                    segmentID:3,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                },{
                    segmentID:4,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:50
                    },{
                        shoperKind:'NETIZENS',
                        value:60
                    },{
                        shoperKind:'MIXED',
                        value:70
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:80
                    }]
                },{
                    segmentID:5,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                }]
            }]
        },{
            variantName:'_B',
            parentBrandName:'HLAN1',
            parentCategoryID:2,
            marketInfo:[{
                marketID:1,
                segmentInfo:[{
                    segmentID:1,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                },{
                    segmentID:2,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:50
                    },{
                        shoperKind:'NETIZENS',
                        value:60
                    },{
                        shoperKind:'MIXED',
                        value:70
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:80
                    }]
                },{
                    segmentID:3,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                },{
                    segmentID:4,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:50
                    },{
                        shoperKind:'NETIZENS',
                        value:60
                    },{
                        shoperKind:'MIXED',
                        value:70
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:80
                    }]
                },{
                    segmentID:5,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                }]
            },{
                marketID:2,
                segmentInfo:[{
                    segmentID:1,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                },{
                    segmentID:2,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:50
                    },{
                        shoperKind:'NETIZENS',
                        value:60
                    },{
                        shoperKind:'MIXED',
                        value:70
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:80
                    }]
                },{
                    segmentID:3,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                },{
                    segmentID:4,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:50
                    },{
                        shoperKind:'NETIZENS',
                        value:60
                    },{
                        shoperKind:'MIXED',
                        value:70
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:80
                    }]
                },{
                    segmentID:5,
                    shopperInfo:[{
                        shoperKind:'BMS',
                        value:10
                    },{
                        shoperKind:'NETIZENS',
                        value:20
                    },{
                        shoperKind:'MIXED',
                        value:30
                    },{
                        shoperKind:'ALLSHOPPERS',
                        value:40
                    }]
                }]
            }]
        }]
    });
    newSCR_sharesCrossSegment.save(function(err) {
        if(!err){
            res.send(200,newSCR_sharesCrossSegment);
            console.log("created new GeneralReport:"+newSCR_sharesCrossSegment);
        } else {
            res.send(400,"failed.");
        }
    });  
}

exports.getSCR_sharesCrossSegment=function(req,res,next){
    var data={
        'seminar':req.params.seminar,
        'period':req.params.period,
        'producerID':req.params.producerID
    };
    SCR_sharesCrossSegment.find(data,function(err,docs){
        if(docs){
            res.send(200,docs);
        }else{
            res.send(404,'failed');
        }
    })  
}
